local definitions = {
  {
    ["id"] = "morebuilds:wall_mirror:large",
    ["sortKey"] = 1730,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_mirror_large",
    ["descriptionKey"] = "Tooltip_MoreBuild_WallMirror",
    ["recipeId"] = "MoreBuilds.DecorationGlass",
    ["previewSprite"] = "walls_decoration_01_4",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["eastSprite"] = "walls_decoration_01_30",
        ["health"] = 25,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "walls_decoration_01_5",
        ["southSprite"] = "walls_decoration_01_31",
        ["sprite"] = "walls_decoration_01_4",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_trophy:mounted_deer",
    ["sortKey"] = 1735,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_trophy_mounted_deer",
    ["descriptionKey"] = "Tooltip_MoreBuild_MountedDeerTrophy",
    ["recipeId"] = "MoreBuilds.SkullTrophyStag",
    ["previewSprite"] = "camping_01_17",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["eastSprite"] = "camping_01_22",
        ["health"] = 25,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "camping_01_21",
        ["southSprite"] = "camping_01_18",
        ["sprite"] = "camping_01_17",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_mirror:wood_framed",
    ["sortKey"] = 1740,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_mirror_wood_framed",
    ["descriptionKey"] = "Tooltip_MoreBuild_WallMirror",
    ["recipeId"] = "MoreBuilds.DecorationGlass",
    ["previewSprite"] = "walls_decoration_01_6",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["eastSprite"] = "walls_decoration_01_28",
        ["health"] = 25,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "walls_decoration_01_7",
        ["southSprite"] = "walls_decoration_01_29",
        ["sprite"] = "walls_decoration_01_6",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_mirror:tall",
    ["sortKey"] = 1750,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_mirror_tall",
    ["descriptionKey"] = "Tooltip_MoreBuild_WallMirror",
    ["recipeId"] = "MoreBuilds.DecorationGlass",
    ["previewSprite"] = "walls_decoration_01_8",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["eastSprite"] = "walls_decoration_01_26",
        ["health"] = 25,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "walls_decoration_01_9",
        ["southSprite"] = "walls_decoration_01_27",
        ["sprite"] = "walls_decoration_01_8",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_mirror:small",
    ["sortKey"] = 1760,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_mirror_small",
    ["descriptionKey"] = "Tooltip_MoreBuild_WallMirror",
    ["recipeId"] = "MoreBuilds.DecorationGlass",
    ["previewSprite"] = "walls_decoration_01_11",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["eastSprite"] = "walls_decoration_01_25",
        ["health"] = 25,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "walls_decoration_01_10",
        ["southSprite"] = "walls_decoration_01_24",
        ["sprite"] = "walls_decoration_01_11",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_mirror:victorian",
    ["sortKey"] = 1770,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_mirror_victorian",
    ["descriptionKey"] = "Tooltip_MoreBuild_WallMirror",
    ["recipeId"] = "MoreBuilds.DecorationGlass",
    ["previewSprite"] = "walls_decoration_01_37",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["eastSprite"] = "walls_decoration_01_39",
        ["health"] = 25,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "walls_decoration_01_36",
        ["southSprite"] = "walls_decoration_01_38",
        ["sprite"] = "walls_decoration_01_37",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_painting:lighthouse",
    ["sortKey"] = 1780,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_painting_lighthouse",
    ["descriptionKey"] = "Tooltip_MoreBuild_GalleryPainting",
    ["recipeId"] = "MoreBuilds.DecorationWood",
    ["previewSprite"] = "walls_decoration_01_43",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 25,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "walls_decoration_01_42",
        ["sprite"] = "walls_decoration_01_43",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_decoration:square_wall_clock",
    ["sortKey"] = 1790,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_decoration_square_wall_clock",
    ["descriptionKey"] = "Tooltip_MoreBuild_SquareWallClock",
    ["recipeId"] = "MoreBuilds.ElectronicDecoration",
    ["previewSprite"] = "walls_decoration_01_104",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["eastSprite"] = "walls_decoration_01_107",
        ["health"] = 25,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "walls_decoration_01_105",
        ["southSprite"] = "walls_decoration_01_106",
        ["sprite"] = "walls_decoration_01_104",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:gallery_painting:abe_lincoln",
    ["sortKey"] = 1980,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_gallery_painting_abe_lincoln",
    ["descriptionKey"] = "Tooltip_MoreBuild_GalleryPainting",
    ["recipeId"] = "MoreBuilds.DecorationWood",
    ["previewSprite"] = "location_entertainment_gallery_01_97",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 25,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "location_entertainment_gallery_01_44",
        ["sprite"] = "location_entertainment_gallery_01_97",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:gallery_painting:apple_faced_man",
    ["sortKey"] = 1990,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_gallery_painting_apple_faced_man",
    ["descriptionKey"] = "Tooltip_MoreBuild_GalleryPainting",
    ["recipeId"] = "MoreBuilds.DecorationWood",
    ["previewSprite"] = "location_entertainment_gallery_01_87",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 25,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "location_entertainment_gallery_01_34",
        ["sprite"] = "location_entertainment_gallery_01_87",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:gallery_painting:benjamin_franklin",
    ["sortKey"] = 2000,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_gallery_painting_benjamin_franklin",
    ["descriptionKey"] = "Tooltip_MoreBuild_GalleryPainting",
    ["recipeId"] = "MoreBuilds.DecorationWood",
    ["previewSprite"] = "location_entertainment_gallery_01_92",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 25,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "location_entertainment_gallery_01_43",
        ["sprite"] = "location_entertainment_gallery_01_92",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:gallery_painting:calvinist",
    ["sortKey"] = 2010,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_gallery_painting_calvinist",
    ["descriptionKey"] = "Tooltip_MoreBuild_GalleryPainting",
    ["recipeId"] = "MoreBuilds.DecorationWood",
    ["previewSprite"] = "location_entertainment_gallery_01_93",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 25,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "location_entertainment_gallery_01_28",
        ["sprite"] = "location_entertainment_gallery_01_93",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:gallery_painting:configuration_ii",
    ["sortKey"] = 2020,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_gallery_painting_configuration_ii",
    ["descriptionKey"] = "Tooltip_MoreBuild_GalleryPainting",
    ["recipeId"] = "MoreBuilds.DecorationWood",
    ["previewSprite"] = "location_entertainment_gallery_01_108",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 25,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "location_entertainment_gallery_01_49",
        ["sprite"] = "location_entertainment_gallery_01_108",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:gallery_painting:configuration_no_10",
    ["sortKey"] = 2030,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_gallery_painting_configuration_no_10",
    ["descriptionKey"] = "Tooltip_MoreBuild_GalleryPainting",
    ["recipeId"] = "MoreBuilds.DecorationWood",
    ["previewSprite"] = "location_entertainment_gallery_01_109",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 25,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "location_entertainment_gallery_01_50",
        ["sprite"] = "location_entertainment_gallery_01_109",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:gallery_painting:flowers_on_table",
    ["sortKey"] = 2040,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_gallery_painting_flowers_on_table",
    ["descriptionKey"] = "Tooltip_MoreBuild_GalleryPainting",
    ["recipeId"] = "MoreBuilds.DecorationWood",
    ["previewSprite"] = "location_entertainment_gallery_01_101",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 25,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "location_entertainment_gallery_01_40",
        ["sprite"] = "location_entertainment_gallery_01_101",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:gallery_painting:george_washington",
    ["sortKey"] = 2050,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_gallery_painting_george_washington",
    ["descriptionKey"] = "Tooltip_MoreBuild_GalleryPainting",
    ["recipeId"] = "MoreBuilds.DecorationWood",
    ["previewSprite"] = "location_entertainment_gallery_01_90",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 25,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "location_entertainment_gallery_01_41",
        ["sprite"] = "location_entertainment_gallery_01_90",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:gallery_painting:helianthus",
    ["sortKey"] = 2060,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_gallery_painting_helianthus",
    ["descriptionKey"] = "Tooltip_MoreBuild_GalleryPainting",
    ["recipeId"] = "MoreBuilds.DecorationWood",
    ["previewSprite"] = "location_entertainment_gallery_01_82",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 25,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "location_entertainment_gallery_01_38",
        ["sprite"] = "location_entertainment_gallery_01_82",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:gallery_painting:john_adams",
    ["sortKey"] = 2070,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_gallery_painting_john_adams",
    ["descriptionKey"] = "Tooltip_MoreBuild_GalleryPainting",
    ["recipeId"] = "MoreBuilds.DecorationWood",
    ["previewSprite"] = "location_entertainment_gallery_01_91",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 25,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "location_entertainment_gallery_01_42",
        ["sprite"] = "location_entertainment_gallery_01_91",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:gallery_painting:layout_i",
    ["sortKey"] = 2080,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_gallery_painting_layout_i",
    ["descriptionKey"] = "Tooltip_MoreBuild_GalleryPainting",
    ["recipeId"] = "MoreBuilds.DecorationWood",
    ["previewSprite"] = "location_entertainment_gallery_01_107",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 25,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "location_entertainment_gallery_01_48",
        ["sprite"] = "location_entertainment_gallery_01_107",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:gallery_painting:man_with_one_ear",
    ["sortKey"] = 2090,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_gallery_painting_man_with_one_ear",
    ["descriptionKey"] = "Tooltip_MoreBuild_GalleryPainting",
    ["recipeId"] = "MoreBuilds.DecorationWood",
    ["previewSprite"] = "location_entertainment_gallery_01_86",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 25,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "location_entertainment_gallery_01_36",
        ["sprite"] = "location_entertainment_gallery_01_86",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:gallery_painting:margarite",
    ["sortKey"] = 2100,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_gallery_painting_margarite",
    ["descriptionKey"] = "Tooltip_MoreBuild_GalleryPainting",
    ["recipeId"] = "MoreBuilds.DecorationWood",
    ["previewSprite"] = "location_entertainment_gallery_01_96",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 25,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "location_entertainment_gallery_01_29",
        ["sprite"] = "location_entertainment_gallery_01_96",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:gallery_painting:riverside",
    ["sortKey"] = 2110,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_gallery_painting_riverside",
    ["descriptionKey"] = "Tooltip_MoreBuild_GalleryPainting",
    ["recipeId"] = "MoreBuilds.DecorationWood",
    ["previewSprite"] = "location_entertainment_gallery_01_102",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 25,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "location_entertainment_gallery_01_32",
        ["sprite"] = "location_entertainment_gallery_01_102",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:gallery_painting:sir_brakefire",
    ["sortKey"] = 2120,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_gallery_painting_sir_brakefire",
    ["descriptionKey"] = "Tooltip_MoreBuild_GalleryPainting",
    ["recipeId"] = "MoreBuilds.DecorationWood",
    ["previewSprite"] = "location_entertainment_gallery_01_85",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 25,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "location_entertainment_gallery_01_35",
        ["sprite"] = "location_entertainment_gallery_01_85",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:gallery_painting:thomas_jefferson",
    ["sortKey"] = 2130,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_gallery_painting_thomas_jefferson",
    ["descriptionKey"] = "Tooltip_MoreBuild_GalleryPainting",
    ["recipeId"] = "MoreBuilds.DecorationWood",
    ["previewSprite"] = "location_entertainment_gallery_01_98",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 25,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "location_entertainment_gallery_01_45",
        ["sprite"] = "location_entertainment_gallery_01_98",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:gallery_painting:two_frame",
    ["sortKey"] = 2140,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_gallery_painting_two_frame",
    ["descriptionKey"] = "Tooltip_MoreBuild_GalleryPainting",
    ["recipeId"] = "MoreBuilds.DecorationWood",
    ["previewSprite"] = "location_entertainment_gallery_01_75",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 25,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "location_entertainment_gallery_01_67",
        ["sprite"] = "location_entertainment_gallery_01_75",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:gallery_painting:violetta",
    ["sortKey"] = 2150,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_gallery_painting_violetta",
    ["descriptionKey"] = "Tooltip_MoreBuild_GalleryPainting",
    ["recipeId"] = "MoreBuilds.DecorationWood",
    ["previewSprite"] = "location_entertainment_gallery_01_95",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 25,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "location_entertainment_gallery_01_39",
        ["sprite"] = "location_entertainment_gallery_01_95",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:gallery_painting:waterfall",
    ["sortKey"] = 2160,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_gallery_painting_waterfall",
    ["descriptionKey"] = "Tooltip_MoreBuild_GalleryPainting",
    ["recipeId"] = "MoreBuilds.DecorationWood",
    ["previewSprite"] = "location_entertainment_gallery_01_103",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 25,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "location_entertainment_gallery_01_33",
        ["sprite"] = "location_entertainment_gallery_01_103",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:gallery_painting:aaaaah",
    ["sortKey"] = 2170,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_gallery_painting_aaaaah",
    ["descriptionKey"] = "Tooltip_MoreBuild_GalleryPainting",
    ["recipeId"] = "MoreBuilds.DecorationWood",
    ["previewSprite"] = "location_entertainment_gallery_01_94",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 25,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "location_entertainment_gallery_01_37",
        ["sprite"] = "location_entertainment_gallery_01_94",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_decoration:1:1",
    ["sortKey"] = 4640,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_decoration_1_1",
    ["descriptionKey"] = "Tooltip_MoreBuild_DecorationMetal",
    ["recipeId"] = "MoreBuilds.DecorationWood",
    ["previewSprite"] = "location_restaurant_pie_01_15",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 50,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "location_restaurant_pie_01_14",
        ["sprite"] = "location_restaurant_pie_01_15",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_decoration:1:2",
    ["sortKey"] = 4650,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_decoration_1_2",
    ["descriptionKey"] = "Tooltip_MoreBuild_DecorationMetal",
    ["recipeId"] = "MoreBuilds.DecorationPaper",
    ["previewSprite"] = "location_restaurant_pie_01_63",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 50,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "location_restaurant_pie_01_56",
        ["sprite"] = "location_restaurant_pie_01_63",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_decoration:1:3",
    ["sortKey"] = 4660,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_decoration_1_3",
    ["descriptionKey"] = "Tooltip_MoreBuild_DecorationMetal",
    ["recipeId"] = "MoreBuilds.DecorationPaper",
    ["previewSprite"] = "location_restaurant_pie_01_62",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 50,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "location_restaurant_pie_01_57",
        ["sprite"] = "location_restaurant_pie_01_62",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_decoration:1:4",
    ["sortKey"] = 4670,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_decoration_1_4",
    ["descriptionKey"] = "Tooltip_MoreBuild_DecorationMetal",
    ["recipeId"] = "MoreBuilds.DecorationPaper",
    ["previewSprite"] = "location_restaurant_pie_01_61",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 50,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "location_restaurant_pie_01_58",
        ["sprite"] = "location_restaurant_pie_01_61",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_decoration:1:5",
    ["sortKey"] = 4680,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_decoration_1_5",
    ["descriptionKey"] = "Tooltip_MoreBuild_DecorationMetal",
    ["recipeId"] = "MoreBuilds.DecorationPaper",
    ["previewSprite"] = "location_restaurant_pie_01_60",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 50,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "location_restaurant_pie_01_59",
        ["sprite"] = "location_restaurant_pie_01_60",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_decoration:1:6",
    ["sortKey"] = 4690,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_decoration_1_6",
    ["descriptionKey"] = "Tooltip_MoreBuild_DecorationMetal",
    ["recipeId"] = "MoreBuilds.DecorationPaper",
    ["previewSprite"] = "location_shop_accessories_01_26",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 50,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "location_shop_accessories_01_27",
        ["sprite"] = "location_shop_accessories_01_26",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_decoration:2:1",
    ["sortKey"] = 4700,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_decoration_2_1",
    ["descriptionKey"] = "Tooltip_MoreBuild_DecorationPaper",
    ["recipeId"] = "MoreBuilds.DecorationPaper",
    ["previewSprite"] = "location_entertainment_theatre_01_80",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 50,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "location_entertainment_theatre_01_83",
        ["sprite"] = "location_entertainment_theatre_01_80",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_decoration:2:2",
    ["sortKey"] = 4710,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_decoration_2_2",
    ["descriptionKey"] = "Tooltip_MoreBuild_DecorationPaper",
    ["recipeId"] = "MoreBuilds.DecorationPaper",
    ["previewSprite"] = "location_entertainment_theatre_01_81",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 50,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "location_entertainment_theatre_01_84",
        ["sprite"] = "location_entertainment_theatre_01_81",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_decoration:2:3",
    ["sortKey"] = 4720,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_decoration_2_3",
    ["descriptionKey"] = "Tooltip_MoreBuild_DecorationPaper",
    ["recipeId"] = "MoreBuilds.DecorationPaper",
    ["previewSprite"] = "location_entertainment_theatre_01_82",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 50,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "location_entertainment_theatre_01_85",
        ["sprite"] = "location_entertainment_theatre_01_82",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_decoration:3:1",
    ["sortKey"] = 4730,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_decoration_3_1",
    ["descriptionKey"] = "Tooltip_MoreBuild_DecorationMetal",
    ["recipeId"] = "MoreBuilds.DecorationPaper",
    ["previewSprite"] = "location_community_medical_01_12",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 50,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "location_community_medical_01_11",
        ["sprite"] = "location_community_medical_01_12",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_decoration:3:2",
    ["sortKey"] = 4740,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_decoration_3_2",
    ["descriptionKey"] = "Tooltip_MoreBuild_DecorationMetal",
    ["recipeId"] = "MoreBuilds.DecorationPaper",
    ["previewSprite"] = "location_community_medical_01_13",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 50,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "location_community_medical_01_14",
        ["sprite"] = "location_community_medical_01_13",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_decoration:3:3",
    ["sortKey"] = 4750,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_decoration_3_3",
    ["descriptionKey"] = "Tooltip_MoreBuild_DecorationMetal",
    ["recipeId"] = "MoreBuilds.DecorationWood",
    ["previewSprite"] = "location_community_medical_01_30",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 50,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "location_community_medical_01_31",
        ["sprite"] = "location_community_medical_01_30",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_decoration:3:4",
    ["sortKey"] = 4760,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_decoration_3_4",
    ["descriptionKey"] = "Tooltip_MoreBuild_DecorationMetal",
    ["recipeId"] = "MoreBuilds.DecorationPaper",
    ["previewSprite"] = "location_community_medical_01_28",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 50,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "location_community_medical_01_29",
        ["sprite"] = "location_community_medical_01_28",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_decoration:4:1",
    ["sortKey"] = 4770,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_decoration_4_1",
    ["descriptionKey"] = "Tooltip_MoreBuild_DecorationWood",
    ["recipeId"] = "MoreBuilds.DecorationWood",
    ["previewSprite"] = "walls_decoration_01_32",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 50,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "walls_decoration_01_33",
        ["sprite"] = "walls_decoration_01_32",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_decoration:4:2",
    ["sortKey"] = 4780,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_decoration_4_2",
    ["descriptionKey"] = "Tooltip_MoreBuild_DecorationWood",
    ["recipeId"] = "MoreBuilds.DecorationWood",
    ["previewSprite"] = "walls_decoration_01_34",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 50,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "walls_decoration_01_35",
        ["sprite"] = "walls_decoration_01_34",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_decoration:4:3",
    ["sortKey"] = 4790,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_decoration_4_3",
    ["descriptionKey"] = "Tooltip_MoreBuild_DecorationWood",
    ["recipeId"] = "MoreBuilds.DecorationWood",
    ["previewSprite"] = "walls_decoration_01_47",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 50,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "walls_decoration_01_46",
        ["sprite"] = "walls_decoration_01_47",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_decoration:4:4",
    ["sortKey"] = 4800,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_decoration_4_4",
    ["descriptionKey"] = "Tooltip_MoreBuild_DecorationPaper",
    ["recipeId"] = "MoreBuilds.DecorationPaper",
    ["previewSprite"] = "walls_decoration_01_49",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 50,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "walls_decoration_01_48",
        ["sprite"] = "walls_decoration_01_49",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_decoration:4:5",
    ["sortKey"] = 4810,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_decoration_4_5",
    ["descriptionKey"] = "Tooltip_MoreBuild_DecorationPaper",
    ["recipeId"] = "MoreBuilds.DecorationPaper",
    ["previewSprite"] = "walls_decoration_01_51",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 50,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "walls_decoration_01_50",
        ["sprite"] = "walls_decoration_01_51",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_decoration:4:6",
    ["sortKey"] = 4820,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_decoration_4_6",
    ["descriptionKey"] = "Tooltip_MoreBuild_DecorationWood",
    ["recipeId"] = "MoreBuilds.DecorationWood",
    ["previewSprite"] = "walls_decoration_01_56",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 50,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "walls_decoration_01_57",
        ["sprite"] = "walls_decoration_01_56",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_decoration:5:1",
    ["sortKey"] = 4830,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_decoration_5_1",
    ["descriptionKey"] = "Tooltip_MoreBuild_DecorationMetal",
    ["recipeId"] = "MoreBuilds.DecorationFabric",
    ["previewSprite"] = "walls_decoration_01_17",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 50,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "walls_decoration_01_16",
        ["sprite"] = "walls_decoration_01_17",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_decoration:5:2",
    ["sortKey"] = 4840,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_decoration_5_2",
    ["descriptionKey"] = "Tooltip_MoreBuild_DecorationMetal",
    ["recipeId"] = "MoreBuilds.DecorationFabric",
    ["previewSprite"] = "walls_decoration_01_19",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 50,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "walls_decoration_01_18",
        ["sprite"] = "walls_decoration_01_19",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_decoration:5:3",
    ["sortKey"] = 4850,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_decoration_5_3",
    ["descriptionKey"] = "Tooltip_MoreBuild_DecorationMetal",
    ["recipeId"] = "MoreBuilds.DecorationPaper",
    ["previewSprite"] = "location_shop_accessories_01_24",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 50,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "location_shop_accessories_01_25",
        ["sprite"] = "location_shop_accessories_01_24",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_decoration:5:4",
    ["sortKey"] = 4860,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_decoration_5_4",
    ["descriptionKey"] = "Tooltip_MoreBuild_DecorationMetal",
    ["recipeId"] = "MoreBuilds.ElectronicDecoration",
    ["previewSprite"] = "location_community_school_01_33",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["eastSprite"] = "location_community_school_01_35",
        ["health"] = 50,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "location_community_school_01_32",
        ["southSprite"] = "location_community_school_01_34",
        ["sprite"] = "location_community_school_01_33",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_decoration:5:5",
    ["sortKey"] = 4870,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_MenRoom_Sign",
    ["descriptionKey"] = "Tooltip_MoreBuild_DecorationPlastic",
    ["recipeId"] = "MoreBuilds.DecorationPlastic",
    ["previewSprite"] = "fixtures_bathroom_01_18",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 50,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "fixtures_bathroom_01_20",
        ["sprite"] = "fixtures_bathroom_01_18",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_decoration:5:6",
    ["sortKey"] = 4880,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_LadyRoom_Sign",
    ["descriptionKey"] = "Tooltip_MoreBuild_DecorationPlastic",
    ["recipeId"] = "MoreBuilds.DecorationPlastic",
    ["previewSprite"] = "fixtures_bathroom_01_19",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 50,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "fixtures_bathroom_01_21",
        ["sprite"] = "fixtures_bathroom_01_19",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_decoration:6:1",
    ["sortKey"] = 4890,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_decoration_6_1",
    ["descriptionKey"] = "Tooltip_MoreBuild_DecorationPaper",
    ["recipeId"] = "MoreBuilds.DecorationPaper",
    ["previewSprite"] = "papernotices_01_0",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 50,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "papernotices_01_3",
        ["sprite"] = "papernotices_01_0",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_decoration:6:2",
    ["sortKey"] = 4900,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_decoration_6_2",
    ["descriptionKey"] = "Tooltip_MoreBuild_DecorationPaper",
    ["recipeId"] = "MoreBuilds.DecorationPaper",
    ["previewSprite"] = "papernotices_01_1",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 50,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "papernotices_01_2",
        ["sprite"] = "papernotices_01_1",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_decoration:6:3",
    ["sortKey"] = 4910,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_decoration_6_3",
    ["descriptionKey"] = "Tooltip_MoreBuild_DecorationPaper",
    ["recipeId"] = "MoreBuilds.DecorationPaper",
    ["previewSprite"] = "papernotices_01_4",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 50,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "papernotices_01_7",
        ["sprite"] = "papernotices_01_4",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_decoration:6:4",
    ["sortKey"] = 4920,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_decoration_6_4",
    ["descriptionKey"] = "Tooltip_MoreBuild_DecorationPaper",
    ["recipeId"] = "MoreBuilds.DecorationPaper",
    ["previewSprite"] = "papernotices_01_5",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 50,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "papernotices_01_6",
        ["sprite"] = "papernotices_01_5",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_decoration:6:5",
    ["sortKey"] = 4930,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_decoration_6_5",
    ["descriptionKey"] = "Tooltip_MoreBuild_DecorationPaper",
    ["recipeId"] = "MoreBuilds.DecorationPaper",
    ["previewSprite"] = "papernotices_01_8",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 50,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "papernotices_01_9",
        ["sprite"] = "papernotices_01_8",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:furniture:weighing_scale",
    ["sortKey"] = 7570,
    ["categoryId"] = "utilities:water-sanitation",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_furniture_weighing_scale",
    ["descriptionKey"] = "Tooltip_MoreBuild_WeighingScale",
    ["recipeId"] = "MoreBuilds.DecorationMetal",
    ["previewSprite"] = "location_community_medical_01_9",
    ["placement"] = {
      ["kind"] = "morebuilds:furniture",
      ["data"] = {
        ["blockAllTheSquare"] = false,
        ["canBeAlwaysPlaced"] = false,
        ["canPassThrough"] = true,
        ["eastSprite"] = "location_community_medical_01_9",
        ["health"] = 25,
        ["isThumpable"] = false,
        ["northSprite"] = "location_community_medical_01_8",
        ["southSprite"] = "location_community_medical_01_8",
        ["sprite"] = "location_community_medical_01_9",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_decoration:operation_fort_knox_poster",
    ["sortKey"] = 7700,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_decoration_operation_fort_knox_poster",
    ["descriptionKey"] = "Tooltip_MoreBuild_PaperPoster",
    ["recipeId"] = "MoreBuilds.DecorationPaper",
    ["previewSprite"] = "walls_decoration_03_44",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 10,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "walls_decoration_03_36",
        ["sprite"] = "walls_decoration_03_44",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_decoration:forgotten_element_poster",
    ["sortKey"] = 7710,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_decoration_forgotten_element_poster",
    ["descriptionKey"] = "Tooltip_MoreBuild_PaperPoster",
    ["recipeId"] = "MoreBuilds.DecorationPaper",
    ["previewSprite"] = "walls_decoration_04_12",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 10,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "walls_decoration_04_4",
        ["sprite"] = "walls_decoration_04_12",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:gallery_painting:chromatic_accident",
    ["sortKey"] = 7720,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_gallery_painting_chromatic_accident",
    ["descriptionKey"] = "Tooltip_MoreBuild_GalleryPainting",
    ["recipeId"] = "MoreBuilds.GalleryPaintingPanoramic",
    ["previewSprite"] = "location_entertainment_gallery_01_119",
    ["placement"] = {
      ["kind"] = "morebuilds:multi-wall-decoration",
      ["data"] = {
        ["health"] = 25,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "location_entertainment_gallery_01_56",
        ["sprite"] = "location_entertainment_gallery_01_119",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:gallery_painting:desert_landscape",
    ["sortKey"] = 7730,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_gallery_painting_desert_landscape",
    ["descriptionKey"] = "Tooltip_MoreBuild_GalleryPainting",
    ["recipeId"] = "MoreBuilds.GalleryPaintingWide",
    ["previewSprite"] = "location_entertainment_gallery_01_84",
    ["placement"] = {
      ["kind"] = "morebuilds:multi-wall-decoration",
      ["data"] = {
        ["health"] = 25,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "location_entertainment_gallery_01_20",
        ["sprite"] = "location_entertainment_gallery_01_84",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:gallery_painting:lillys_waterpond",
    ["sortKey"] = 7740,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_gallery_painting_lillys_waterpond",
    ["descriptionKey"] = "Tooltip_MoreBuild_GalleryPainting",
    ["recipeId"] = "MoreBuilds.GalleryPaintingWide",
    ["previewSprite"] = "location_entertainment_gallery_01_89",
    ["placement"] = {
      ["kind"] = "morebuilds:multi-wall-decoration",
      ["data"] = {
        ["health"] = 25,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "location_entertainment_gallery_01_26",
        ["sprite"] = "location_entertainment_gallery_01_89",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:gallery_painting:mount_never_rest",
    ["sortKey"] = 7750,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_gallery_painting_mount_never_rest",
    ["descriptionKey"] = "Tooltip_MoreBuild_GalleryPainting",
    ["recipeId"] = "MoreBuilds.GalleryPaintingPanoramic",
    ["previewSprite"] = "location_entertainment_gallery_01_106",
    ["placement"] = {
      ["kind"] = "morebuilds:multi-wall-decoration",
      ["data"] = {
        ["health"] = 25,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "location_entertainment_gallery_01_64",
        ["sprite"] = "location_entertainment_gallery_01_106",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:gallery_painting:night_with_stars",
    ["sortKey"] = 7760,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_gallery_painting_night_with_stars",
    ["descriptionKey"] = "Tooltip_MoreBuild_GalleryPainting",
    ["recipeId"] = "MoreBuilds.GalleryPaintingWide",
    ["previewSprite"] = "location_entertainment_gallery_01_81",
    ["placement"] = {
      ["kind"] = "morebuilds:multi-wall-decoration",
      ["data"] = {
        ["health"] = 25,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "location_entertainment_gallery_01_30",
        ["sprite"] = "location_entertainment_gallery_01_81",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:gallery_painting:nomad_above_the_gloom",
    ["sortKey"] = 7770,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_gallery_painting_nomad_above_the_gloom",
    ["descriptionKey"] = "Tooltip_MoreBuild_GalleryPainting",
    ["recipeId"] = "MoreBuilds.GalleryPaintingWide",
    ["previewSprite"] = "location_entertainment_gallery_01_100",
    ["placement"] = {
      ["kind"] = "morebuilds:multi-wall-decoration",
      ["data"] = {
        ["health"] = 25,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "location_entertainment_gallery_01_24",
        ["sprite"] = "location_entertainment_gallery_01_100",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:gallery_painting:shes_got_it",
    ["sortKey"] = 7780,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_gallery_painting_shes_got_it",
    ["descriptionKey"] = "Tooltip_MoreBuild_GalleryPainting",
    ["recipeId"] = "MoreBuilds.GalleryPaintingWide",
    ["previewSprite"] = "location_entertainment_gallery_01_111",
    ["placement"] = {
      ["kind"] = "morebuilds:multi-wall-decoration",
      ["data"] = {
        ["health"] = 25,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "location_entertainment_gallery_01_22",
        ["sprite"] = "location_entertainment_gallery_01_111",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_mirror:gym_left",
    ["sortKey"] = 7960,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_mirror_gym_left",
    ["descriptionKey"] = "Tooltip_MoreBuild_WallMirror",
    ["recipeId"] = "MoreBuilds.DecorationGlass",
    ["previewSprite"] = "recreational_sports_01_74",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 25,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "recreational_sports_01_78",
        ["sprite"] = "recreational_sports_01_74",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_mirror:gym_middle",
    ["sortKey"] = 7970,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_mirror_gym_middle",
    ["descriptionKey"] = "Tooltip_MoreBuild_WallMirror",
    ["recipeId"] = "MoreBuilds.DecorationGlass",
    ["previewSprite"] = "recreational_sports_01_76",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 25,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "recreational_sports_01_77",
        ["sprite"] = "recreational_sports_01_76",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_mirror:gym_right",
    ["sortKey"] = 7980,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_mirror_gym_right",
    ["descriptionKey"] = "Tooltip_MoreBuild_WallMirror",
    ["recipeId"] = "MoreBuilds.DecorationGlass",
    ["previewSprite"] = "recreational_sports_01_75",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 25,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "recreational_sports_01_79",
        ["sprite"] = "recreational_sports_01_75",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
}

for _, definition in ipairs(definitions) do
  definition.sortKey = definition.sortKey + 70000
end

return definitions
