local definitions = {
  {
    ["id"] = "morebuilds:wall_decoration:satellite_dish",
    ["sortKey"] = 1800,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_decoration_satellite_dish",
    ["descriptionKey"] = "Tooltip_MoreBuild_SatelliteDish",
    ["recipeId"] = "MoreBuilds.SatelliteDish",
    ["previewSprite"] = "appliances_com_01_21",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 25,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "appliances_com_01_20",
        ["sprite"] = "appliances_com_01_21",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_decoration:air_conditioner",
    ["sortKey"] = 1810,
    ["categoryId"] = "utilities:appliances",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_decoration_air_conditioner",
    ["descriptionKey"] = "Tooltip_MoreBuild_WallAirConditioner",
    ["recipeId"] = "MoreBuilds.AirConditioner",
    ["previewSprite"] = "industry_01_5",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["eastSprite"] = "industry_01_15",
        ["health"] = 25,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "industry_01_4",
        ["southSprite"] = "industry_01_14",
        ["sprite"] = "industry_01_5",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_decoration:hand_dryer",
    ["sortKey"] = 1820,
    ["categoryId"] = "utilities:water-sanitation",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_decoration_hand_dryer",
    ["descriptionKey"] = "Tooltip_MoreBuild_PaperTowelDispenser",
    ["recipeId"] = "MoreBuilds.ElectronicDecoration",
    ["previewSprite"] = "fixtures_bathroom_01_17",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["eastSprite"] = "fixtures_bathroom_01_15",
        ["health"] = 25,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "fixtures_bathroom_01_16",
        ["southSprite"] = "fixtures_bathroom_01_14",
        ["sprite"] = "fixtures_bathroom_01_17",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_decoration:coat_rack",
    ["sortKey"] = 1830,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_decoration_coat_rack",
    ["descriptionKey"] = "Tooltip_MoreBuild_WallCoatRack",
    ["recipeId"] = "MoreBuilds.WallRackWood",
    ["previewSprite"] = "location_community_school_01_37",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["eastSprite"] = "location_community_school_01_39",
        ["health"] = 25,
        ["healthFromCarpentry"] = true,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "location_community_school_01_36",
        ["southSprite"] = "location_community_school_01_38",
        ["sprite"] = "location_community_school_01_37",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_decoration:pool_cue_rack",
    ["sortKey"] = 1840,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_decoration_pool_cue_rack",
    ["descriptionKey"] = "Tooltip_MoreBuild_WallPoolCueRack",
    ["recipeId"] = "MoreBuilds.WallRackWood",
    ["previewSprite"] = "recreational_01_4",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["eastSprite"] = "recreational_01_46",
        ["health"] = 25,
        ["healthFromCarpentry"] = true,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "recreational_01_5",
        ["southSprite"] = "recreational_01_47",
        ["sprite"] = "recreational_01_4",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_trophy:bull_skull",
    ["sortKey"] = 1850,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_trophy_bull_skull",
    ["descriptionKey"] = "Tooltip_MoreBuild_BullSkullTrophy",
    ["recipeId"] = "MoreBuilds.SkullTrophyBull",
    ["previewSprite"] = "constructedobjects_signs_01_48",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 25,
        ["healthFromCarpentry"] = true,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "constructedobjects_signs_01_49",
        ["sprite"] = "constructedobjects_signs_01_48",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_trophy:cow_skull",
    ["sortKey"] = 1860,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_trophy_cow_skull",
    ["descriptionKey"] = "Tooltip_MoreBuild_CowSkullTrophy",
    ["recipeId"] = "MoreBuilds.SkullTrophyCow",
    ["previewSprite"] = "constructedobjects_signs_01_56",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 25,
        ["healthFromCarpentry"] = true,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "constructedobjects_signs_01_57",
        ["sprite"] = "constructedobjects_signs_01_56",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_trophy:doe_skull",
    ["sortKey"] = 1870,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_trophy_doe_skull",
    ["descriptionKey"] = "Tooltip_MoreBuild_DoeSkullTrophy",
    ["recipeId"] = "MoreBuilds.SkullTrophyDoe",
    ["previewSprite"] = "constructedobjects_signs_01_72",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 25,
        ["healthFromCarpentry"] = true,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "constructedobjects_signs_01_73",
        ["sprite"] = "constructedobjects_signs_01_72",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_trophy:pig_skull",
    ["sortKey"] = 1880,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_trophy_pig_skull",
    ["descriptionKey"] = "Tooltip_MoreBuild_PigSkullTrophy",
    ["recipeId"] = "MoreBuilds.SkullTrophyPig",
    ["previewSprite"] = "constructedobjects_signs_01_80",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 25,
        ["healthFromCarpentry"] = true,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "constructedobjects_signs_01_81",
        ["sprite"] = "constructedobjects_signs_01_80",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_trophy:sheep_skull",
    ["sortKey"] = 1890,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_trophy_sheep_skull",
    ["descriptionKey"] = "Tooltip_MoreBuild_SheepSkullTrophy",
    ["recipeId"] = "MoreBuilds.SkullTrophySheep",
    ["previewSprite"] = "constructedobjects_signs_01_88",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 25,
        ["healthFromCarpentry"] = true,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "constructedobjects_signs_01_89",
        ["sprite"] = "constructedobjects_signs_01_88",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_trophy:stag_skull",
    ["sortKey"] = 1900,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_trophy_stag_skull",
    ["descriptionKey"] = "Tooltip_MoreBuild_StagSkullTrophy",
    ["recipeId"] = "MoreBuilds.SkullTrophyStag",
    ["previewSprite"] = "constructedobjects_signs_01_64",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 25,
        ["healthFromCarpentry"] = true,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "constructedobjects_signs_01_65",
        ["sprite"] = "constructedobjects_signs_01_64",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:tabletop_decoration:black_rotary_phone",
    ["sortKey"] = 1930,
    ["categoryId"] = "decorations:objects",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_tabletop_decoration_black_rotary_phone",
    ["descriptionKey"] = "Tooltip_MoreBuild_BlackRotaryPhone",
    ["recipeId"] = "MoreBuilds.ElectronicDecoration",
    ["previewSprite"] = "location_business_office_generic_02_4",
    ["placement"] = {
      ["kind"] = "morebuilds:table-decoration",
      ["data"] = {
        ["eastSprite"] = "location_business_office_generic_02_6",
        ["health"] = 25,
        ["northSprite"] = "location_business_office_generic_02_5",
        ["southSprite"] = "location_business_office_generic_02_7",
        ["sprite"] = "location_business_office_generic_02_4",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:tabletop_decoration:beige_rotary_phone",
    ["sortKey"] = 1932,
    ["categoryId"] = "decorations:objects",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_tabletop_decoration_beige_rotary_phone",
    ["descriptionKey"] = "Tooltip_MoreBuild_BlackRotaryPhone",
    ["recipeId"] = "MoreBuilds.ElectronicDecoration",
    ["previewSprite"] = "location_business_office_generic_02_0",
    ["placement"] = {
      ["kind"] = "morebuilds:table-decoration",
      ["data"] = {
        ["eastSprite"] = "location_business_office_generic_02_2",
        ["health"] = 25,
        ["northSprite"] = "location_business_office_generic_02_1",
        ["southSprite"] = "location_business_office_generic_02_3",
        ["sprite"] = "location_business_office_generic_02_0",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:tabletop_decoration:red_rotary_phone",
    ["sortKey"] = 1934,
    ["categoryId"] = "decorations:objects",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_tabletop_decoration_red_rotary_phone",
    ["descriptionKey"] = "Tooltip_MoreBuild_BlackRotaryPhone",
    ["recipeId"] = "MoreBuilds.ElectronicDecoration",
    ["previewSprite"] = "location_business_office_generic_02_8",
    ["placement"] = {
      ["kind"] = "morebuilds:table-decoration",
      ["data"] = {
        ["eastSprite"] = "location_business_office_generic_02_10",
        ["health"] = 25,
        ["northSprite"] = "location_business_office_generic_02_9",
        ["southSprite"] = "location_business_office_generic_02_11",
        ["sprite"] = "location_business_office_generic_02_8",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:tabletop_decoration:white_rotary_phone",
    ["sortKey"] = 1936,
    ["categoryId"] = "decorations:objects",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_tabletop_decoration_white_rotary_phone",
    ["descriptionKey"] = "Tooltip_MoreBuild_BlackRotaryPhone",
    ["recipeId"] = "MoreBuilds.ElectronicDecoration",
    ["previewSprite"] = "location_business_office_generic_02_12",
    ["placement"] = {
      ["kind"] = "morebuilds:table-decoration",
      ["data"] = {
        ["eastSprite"] = "location_business_office_generic_02_14",
        ["health"] = 25,
        ["northSprite"] = "location_business_office_generic_02_13",
        ["southSprite"] = "location_business_office_generic_02_15",
        ["sprite"] = "location_business_office_generic_02_12",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:tabletop_decoration:black_modern_phone",
    ["sortKey"] = 1938,
    ["categoryId"] = "decorations:objects",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_tabletop_decoration_black_modern_phone",
    ["descriptionKey"] = "Tooltip_MoreBuild_WhitePushButtonPhone",
    ["recipeId"] = "MoreBuilds.ElectronicDecoration",
    ["previewSprite"] = "location_business_office_generic_02_23",
    ["placement"] = {
      ["kind"] = "morebuilds:table-decoration",
      ["data"] = {
        ["eastSprite"] = "location_business_office_generic_02_21",
        ["health"] = 25,
        ["northSprite"] = "location_business_office_generic_02_20",
        ["southSprite"] = "location_business_office_generic_02_22",
        ["sprite"] = "location_business_office_generic_02_23",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:tabletop_decoration:white_push_button_phone",
    ["sortKey"] = 1940,
    ["categoryId"] = "decorations:objects",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_tabletop_decoration_white_push_button_phone",
    ["descriptionKey"] = "Tooltip_MoreBuild_WhitePushButtonPhone",
    ["recipeId"] = "MoreBuilds.ElectronicDecoration",
    ["previewSprite"] = "location_business_office_generic_02_19",
    ["placement"] = {
      ["kind"] = "morebuilds:table-decoration",
      ["data"] = {
        ["eastSprite"] = "location_business_office_generic_02_17",
        ["health"] = 25,
        ["northSprite"] = "location_business_office_generic_02_16",
        ["southSprite"] = "location_business_office_generic_02_18",
        ["sprite"] = "location_business_office_generic_02_19",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:tabletop_decoration:guitar_amplifier",
    ["sortKey"] = 1950,
    ["categoryId"] = "furniture:bedroom-leisure",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_tabletop_decoration_guitar_amplifier",
    ["descriptionKey"] = "Tooltip_MoreBuild_GuitarAmplifier",
    ["recipeId"] = "MoreBuilds.MusicEquipment",
    ["previewSprite"] = "recreational_01_72",
    ["placement"] = {
      ["kind"] = "morebuilds:table-decoration",
      ["data"] = {
        ["eastSprite"] = "recreational_01_73",
        ["health"] = 25,
        ["northSprite"] = "recreational_01_75",
        ["southSprite"] = "recreational_01_74",
        ["sprite"] = "recreational_01_72",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_decoration:blue_striped_awning",
    ["sortKey"] = 7580,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_decoration_blue_striped_awning",
    ["descriptionKey"] = "Tooltip_MoreBuild_FabricCanopy",
    ["recipeId"] = "MoreBuilds.FabricCanopy",
    ["previewSprite"] = "walls_decoration_01_85",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["eastSprite"] = "walls_decoration_01_93",
        ["health"] = 50,
        ["healthFromCarpentry"] = true,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "walls_decoration_01_84",
        ["southSprite"] = "walls_decoration_01_92",
        ["sprite"] = "walls_decoration_01_85",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:tabletop_decoration:laboratory_microscope",
    ["sortKey"] = 7590,
    ["categoryId"] = "decorations:objects",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_tabletop_decoration_laboratory_microscope",
    ["descriptionKey"] = "Tooltip_MoreBuild_LaboratoryMicroscope",
    ["recipeId"] = "MoreBuilds.LaboratoryMicroscope",
    ["previewSprite"] = "location_community_medical_01_137",
    ["placement"] = {
      ["kind"] = "morebuilds:table-decoration",
      ["data"] = {
        ["eastSprite"] = "location_community_medical_01_138",
        ["health"] = 25,
        ["northSprite"] = "location_community_medical_01_136",
        ["southSprite"] = "location_community_medical_01_139",
        ["sprite"] = "location_community_medical_01_137",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:tabletop_decoration:venus_flytrap",
    ["sortKey"] = 7640,
    ["categoryId"] = "decorations:objects",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_tabletop_decoration_venus_flytrap",
    ["descriptionKey"] = "Tooltip_MoreBuild_VenusFlytrap",
    ["recipeId"] = "MoreBuilds.PottedPlant",
    ["previewSprite"] = "vegetation_indoor_01_0",
    ["placement"] = {
      ["kind"] = "morebuilds:table-decoration",
      ["data"] = {
        ["health"] = 25,
        ["sprite"] = "vegetation_indoor_01_0",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:tabletop_decoration:rose_bouquet",
    ["sortKey"] = 7650,
    ["categoryId"] = "decorations:objects",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_tabletop_decoration_rose_bouquet",
    ["descriptionKey"] = "Tooltip_MoreBuild_PlasticRoseBouquet",
    ["recipeId"] = "MoreBuilds.PlasticFlowerArrangement",
    ["previewSprite"] = "vegetation_indoor_01_5",
    ["placement"] = {
      ["kind"] = "morebuilds:table-decoration",
      ["data"] = {
        ["eastSprite"] = "vegetation_indoor_01_5",
        ["health"] = 25,
        ["northSprite"] = "vegetation_indoor_01_4",
        ["southSprite"] = "vegetation_indoor_01_4",
        ["sprite"] = "vegetation_indoor_01_5",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_decoration:beige_awning",
    ["sortKey"] = 7660,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_decoration_beige_awning",
    ["descriptionKey"] = "Tooltip_MoreBuild_FabricCanopy",
    ["recipeId"] = "MoreBuilds.FabricCanopy",
    ["previewSprite"] = "walls_decoration_01_71",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 50,
        ["healthFromCarpentry"] = true,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "walls_decoration_01_70",
        ["sprite"] = "walls_decoration_01_71",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_decoration:black_awning",
    ["sortKey"] = 7670,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_decoration_black_awning",
    ["descriptionKey"] = "Tooltip_MoreBuild_FabricCanopy",
    ["recipeId"] = "MoreBuilds.FabricCanopy",
    ["previewSprite"] = "walls_decoration_01_117",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["eastSprite"] = "walls_decoration_01_125",
        ["health"] = 50,
        ["healthFromCarpentry"] = true,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "walls_decoration_01_116",
        ["southSprite"] = "walls_decoration_01_124",
        ["sprite"] = "walls_decoration_01_117",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_decoration:red_awning",
    ["sortKey"] = 7680,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_decoration_red_awning",
    ["descriptionKey"] = "Tooltip_MoreBuild_FabricCanopy",
    ["recipeId"] = "MoreBuilds.FabricCanopy",
    ["previewSprite"] = "walls_decoration_01_129",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["eastSprite"] = "walls_decoration_01_137",
        ["health"] = 50,
        ["healthFromCarpentry"] = true,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "walls_decoration_01_128",
        ["southSprite"] = "walls_decoration_01_136",
        ["sprite"] = "walls_decoration_01_129",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_decoration:orange_awning",
    ["sortKey"] = 7690,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_decoration_orange_awning",
    ["descriptionKey"] = "Tooltip_MoreBuild_FabricCanopy",
    ["recipeId"] = "MoreBuilds.FabricCanopy",
    ["previewSprite"] = "walls_decoration_01_133",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["eastSprite"] = "walls_decoration_01_141",
        ["health"] = 50,
        ["healthFromCarpentry"] = true,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "walls_decoration_01_132",
        ["southSprite"] = "walls_decoration_01_140",
        ["sprite"] = "walls_decoration_01_133",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_decoration:teal_striped_awning",
    ["sortKey"] = 7691,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_decoration_teal_striped_awning",
    ["descriptionKey"] = "Tooltip_MoreBuild_FabricCanopy",
    ["recipeId"] = "MoreBuilds.FabricCanopy",
    ["previewSprite"] = "walls_decoration_01_69",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 50,
        ["healthFromCarpentry"] = true,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "walls_decoration_01_68",
        ["sprite"] = "walls_decoration_01_69",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_decoration:red_white_striped_awning",
    ["sortKey"] = 7693,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_decoration_red_white_striped_awning",
    ["descriptionKey"] = "Tooltip_MoreBuild_FabricCanopy",
    ["recipeId"] = "MoreBuilds.FabricCanopy",
    ["previewSprite"] = "walls_decoration_01_101",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["eastSprite"] = "walls_decoration_01_109",
        ["health"] = 50,
        ["healthFromCarpentry"] = true,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "walls_decoration_01_100",
        ["southSprite"] = "walls_decoration_01_108",
        ["sprite"] = "walls_decoration_01_101",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_decoration:dark_green_awning",
    ["sortKey"] = 7695,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_decoration_dark_green_awning",
    ["descriptionKey"] = "Tooltip_MoreBuild_FabricCanopy",
    ["recipeId"] = "MoreBuilds.FabricCanopy",
    ["previewSprite"] = "walls_decoration_01_113",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 50,
        ["healthFromCarpentry"] = true,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "walls_decoration_01_112",
        ["sprite"] = "walls_decoration_01_113",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_decoration:black_white_striped_awning",
    ["sortKey"] = 7696,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_decoration_black_white_striped_awning",
    ["descriptionKey"] = "Tooltip_MoreBuild_FabricCanopy",
    ["recipeId"] = "MoreBuilds.FabricCanopy",
    ["previewSprite"] = "walls_decoration_01_115",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 50,
        ["healthFromCarpentry"] = true,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "walls_decoration_01_114",
        ["sprite"] = "walls_decoration_01_115",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_decoration:grey_white_awning",
    ["sortKey"] = 7698,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_decoration_grey_white_awning",
    ["descriptionKey"] = "Tooltip_MoreBuild_FabricCanopy",
    ["recipeId"] = "MoreBuilds.FabricCanopy",
    ["previewSprite"] = "walls_decoration_01_121",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["health"] = 50,
        ["healthFromCarpentry"] = true,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "walls_decoration_01_120",
        ["sprite"] = "walls_decoration_01_121",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_decoration:scarlet_awning",
    ["sortKey"] = 7702,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_decoration_scarlet_awning",
    ["descriptionKey"] = "Tooltip_MoreBuild_FabricCanopy",
    ["recipeId"] = "MoreBuilds.FabricCanopy",
    ["previewSprite"] = "walls_decoration_01_145",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["eastSprite"] = "walls_decoration_01_148",
        ["health"] = 50,
        ["healthFromCarpentry"] = true,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "walls_decoration_01_144",
        ["southSprite"] = "walls_decoration_01_149",
        ["sprite"] = "walls_decoration_01_145",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_decoration:light_blue_awning",
    ["sortKey"] = 7704,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_decoration_light_blue_awning",
    ["descriptionKey"] = "Tooltip_MoreBuild_FabricCanopy",
    ["recipeId"] = "MoreBuilds.FabricCanopy",
    ["previewSprite"] = "walls_decoration_01_153",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["eastSprite"] = "walls_decoration_01_156",
        ["health"] = 50,
        ["healthFromCarpentry"] = true,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "walls_decoration_01_152",
        ["southSprite"] = "walls_decoration_01_157",
        ["sprite"] = "walls_decoration_01_153",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_decoration:green_white_striped_awning",
    ["sortKey"] = 7705,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_decoration_green_white_striped_awning",
    ["descriptionKey"] = "Tooltip_MoreBuild_FabricCanopy",
    ["recipeId"] = "MoreBuilds.FabricCanopy",
    ["previewSprite"] = "walls_decoration_01_161",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["eastSprite"] = "walls_decoration_01_164",
        ["health"] = 50,
        ["healthFromCarpentry"] = true,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "walls_decoration_01_160",
        ["southSprite"] = "walls_decoration_01_165",
        ["sprite"] = "walls_decoration_01_161",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:tabletop_decoration:antique_bar_tap",
    ["sortKey"] = 7700,
    ["categoryId"] = "decorations:objects",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_tabletop_decoration_antique_bar_tap",
    ["descriptionKey"] = "Tooltip_MoreBuild_AntiqueBarTap",
    ["recipeId"] = "MoreBuilds.DecorationMetal",
    ["previewSprite"] = "location_restaurant_bar_01_32",
    ["placement"] = {
      ["kind"] = "morebuilds:table-decoration",
      ["data"] = {
        ["eastSprite"] = "location_restaurant_bar_01_34",
        ["health"] = 25,
        ["northSprite"] = "location_restaurant_bar_01_33",
        ["southSprite"] = "location_restaurant_bar_01_35",
        ["sprite"] = "location_restaurant_bar_01_32",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:tabletop_decoration:cinema_projector",
    ["sortKey"] = 7710,
    ["categoryId"] = "decorations:objects",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_tabletop_decoration_cinema_projector",
    ["descriptionKey"] = "Tooltip_MoreBuild_CinemaProjector",
    ["recipeId"] = "MoreBuilds.CinemaProjector",
    ["previewSprite"] = "appliances_com_01_84",
    ["placement"] = {
      ["kind"] = "morebuilds:table-decoration",
      ["data"] = {
        ["eastSprite"] = "appliances_com_01_86",
        ["health"] = 50,
        ["northSprite"] = "appliances_com_01_85",
        ["southSprite"] = "appliances_com_01_87",
        ["sprite"] = "appliances_com_01_84",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:furniture:dr_oids_arcade_machine",
    ["sortKey"] = 7720,
    ["categoryId"] = "furniture:bedroom-leisure",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_furniture_dr_oids_arcade_machine",
    ["descriptionKey"] = "Tooltip_MoreBuild_ArcadeMachine",
    ["recipeId"] = "MoreBuilds.ArcadeMachine",
    ["previewSprite"] = "recreational_01_16",
    ["placement"] = {
      ["kind"] = "morebuilds:furniture",
      ["data"] = {
        ["canBeAlwaysPlaced"] = false,
        ["eastSprite"] = "recreational_01_18",
        ["health"] = 100,
        ["northSprite"] = "recreational_01_17",
        ["southSprite"] = "recreational_01_19",
        ["sprite"] = "recreational_01_16",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:furniture:kaboom_arcade_machine",
    ["sortKey"] = 7730,
    ["categoryId"] = "furniture:bedroom-leisure",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_furniture_kaboom_arcade_machine",
    ["descriptionKey"] = "Tooltip_MoreBuild_ArcadeMachine",
    ["recipeId"] = "MoreBuilds.ArcadeMachine",
    ["previewSprite"] = "recreational_01_20",
    ["placement"] = {
      ["kind"] = "morebuilds:furniture",
      ["data"] = {
        ["canBeAlwaysPlaced"] = false,
        ["eastSprite"] = "recreational_01_22",
        ["health"] = 100,
        ["northSprite"] = "recreational_01_21",
        ["southSprite"] = "recreational_01_23",
        ["sprite"] = "recreational_01_20",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_decoration:barber_pole",
    ["sortKey"] = 7740,
    ["categoryId"] = "decorations:wall-decor",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_decoration_barber_pole",
    ["descriptionKey"] = "Tooltip_MoreBuild_BarberPole",
    ["recipeId"] = "MoreBuilds.ElectronicDecoration",
    ["previewSprite"] = "location_services_beauty_01_4",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["eastSprite"] = "location_services_beauty_01_6",
        ["health"] = 25,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "location_services_beauty_01_5",
        ["southSprite"] = "location_services_beauty_01_7",
        ["sprite"] = "location_services_beauty_01_4",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:furniture:paws_pinball_machine",
    ["sortKey"] = 7820,
    ["categoryId"] = "furniture:bedroom-leisure",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_furniture_paws_pinball_machine",
    ["descriptionKey"] = "Tooltip_MoreBuild_PinballMachine",
    ["recipeId"] = "MoreBuilds.PinballMachine",
    ["previewSprite"] = "recreational_01_25",
    ["placement"] = {
      ["kind"] = "morebuilds:multi-furniture",
      ["data"] = {
        ["health"] = 100,
        ["northSprite"] = "recreational_01_26",
        ["sprite"] = "recreational_01_25",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:tabletop_decoration:desktop_computer",
    ["sortKey"] = 7900,
    ["categoryId"] = "decorations:objects",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_tabletop_decoration_desktop_computer",
    ["descriptionKey"] = "Tooltip_MoreBuild_DesktopComputer",
    ["recipeId"] = "MoreBuilds.DesktopComputer",
    ["previewSprite"] = "appliances_com_01_73",
    ["placement"] = {
      ["kind"] = "morebuilds:table-decoration",
      ["data"] = {
        ["eastSprite"] = "appliances_com_01_72",
        ["health"] = 25,
        ["northSprite"] = "appliances_com_01_74",
        ["southSprite"] = "appliances_com_01_75",
        ["sprite"] = "appliances_com_01_73",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:furniture:black_grand_piano",
    ["sortKey"] = 7910,
    ["categoryId"] = "furniture:bedroom-leisure",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_furniture_black_grand_piano",
    ["descriptionKey"] = "Tooltip_MoreBuild_GrandPiano",
    ["recipeId"] = "MoreBuilds.GrandPianoWood",
    ["previewSprite"] = "recreational_01_45",
    ["placement"] = {
      ["kind"] = "morebuilds:multi-furniture",
      ["data"] = {
        ["eastSprite"] = "recreational_01_53",
        ["health"] = 400,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "recreational_01_101",
        ["southSprite"] = "recreational_01_109",
        ["sprite"] = "recreational_01_45",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:furniture:fitness_wheel",
    ["sortKey"] = 8200,
    ["categoryId"] = "furniture:bedroom-leisure",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_furniture_fitness_wheel",
    ["descriptionKey"] = "Tooltip_MoreBuild_SportsMachine",
    ["recipeId"] = "MoreBuilds.SportsMachine",
    ["previewSprite"] = "recreational_sports_01_39",
    ["placement"] = {
      ["kind"] = "morebuilds:multi-furniture",
      ["data"] = {
        ["eastSprite"] = "recreational_sports_01_36",
        ["health"] = 100,
        ["northSprite"] = "recreational_sports_01_31",
        ["southSprite"] = "recreational_sports_01_28",
        ["sprite"] = "recreational_sports_01_39",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:furniture:bowling_rack",
    ["sortKey"] = 8210,
    ["categoryId"] = "furniture:bedroom-leisure",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_furniture_bowling_rack",
    ["descriptionKey"] = "Tooltip_MoreBuild_SportsFixture",
    ["recipeId"] = "MoreBuilds.SportsMetalFixture",
    ["previewSprite"] = "recreational_sports_01_61",
    ["placement"] = {
      ["kind"] = "morebuilds:furniture",
      ["data"] = {
        ["health"] = 75,
        ["sprite"] = "recreational_sports_01_61",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:furniture:bowling_machine",
    ["sortKey"] = 8220,
    ["categoryId"] = "furniture:bedroom-leisure",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_furniture_bowling_machine",
    ["descriptionKey"] = "Tooltip_MoreBuild_SportsFixture",
    ["recipeId"] = "MoreBuilds.SportsMetalFixture",
    ["previewSprite"] = "recreational_sports_01_62",
    ["placement"] = {
      ["kind"] = "morebuilds:furniture",
      ["data"] = {
        ["health"] = 75,
        ["sprite"] = "recreational_sports_01_62",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:medical:patient_chair_wood",
    ["sortKey"] = 8230,
    ["categoryId"] = "furniture:seating",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_medical_patient_chair_wood",
    ["descriptionKey"] = "Tooltip_MoreBuild_MedicalPatientChair",
    ["recipeId"] = "MoreBuilds.MedicalPatientChairWood",
    ["previewSprite"] = "location_community_medical_01_1",
    ["placement"] = {
      ["kind"] = "morebuilds:multi-container",
      ["data"] = {
        ["canBeLockedByPadlock"] = false,
        ["containerCapacity"] = 20,
        ["containerType"] = "counter",
        ["eastSprite"] = "location_community_medical_01_5",
        ["eastSprite2"] = "location_community_medical_01_4",
        ["eastTileOffsets"] = {
          { ["x"] = 0, ["y"] = 0 },
          { ["x"] = 0, ["y"] = 1 },
        },
        ["health"] = 175,
        ["northSprite"] = "location_community_medical_01_2",
        ["northSprite2"] = "location_community_medical_01_3",
        ["northTileOffsets"] = {
          { ["x"] = 0, ["y"] = 0 },
          { ["x"] = 1, ["y"] = 0 },
        },
        ["southSprite"] = "location_community_medical_01_6",
        ["southSprite2"] = "location_community_medical_01_7",
        ["southTileOffsets"] = {
          { ["x"] = 0, ["y"] = 0 },
          { ["x"] = 1, ["y"] = 0 },
        },
        ["sprite"] = "location_community_medical_01_1",
        ["sprite2"] = "location_community_medical_01_0",
        ["tileOffsets"] = {
          { ["x"] = 0, ["y"] = 0 },
          { ["x"] = 0, ["y"] = 1 },
        },
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:medical:patient_chair_metal",
    ["sortKey"] = 8240,
    ["categoryId"] = "furniture:seating",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_medical_patient_chair_metal",
    ["descriptionKey"] = "Tooltip_MoreBuild_MedicalPatientChairMetal",
    ["recipeId"] = "MoreBuilds.MedicalPatientChairMetal",
    ["previewSprite"] = "location_community_medical_01_33",
    ["placement"] = {
      ["kind"] = "morebuilds:multi-furniture",
      ["data"] = {
        ["northSprite2"] = "location_community_medical_01_35",
        ["northTileOffsets"] = {
          { ["x"] = 0, ["y"] = 0 },
          { ["x"] = 1, ["y"] = 0 },
        },
        ["health"] = 225,
        ["northSprite"] = "location_community_medical_01_34",
        ["sprite"] = "location_community_medical_01_33",
        ["sprite2"] = "location_community_medical_01_32",
        ["tileOffsets"] = {
          { ["x"] = 0, ["y"] = 0 },
          { ["x"] = 0, ["y"] = 1 },
        },
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:medical:morgue_table",
    ["sortKey"] = 8250,
    ["categoryId"] = "furniture:tables",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_medical_morgue_table",
    ["descriptionKey"] = "Tooltip_MoreBuild_MorgueTable",
    ["recipeId"] = "MoreBuilds.MedicalMorgueTable",
    ["previewSprite"] = "location_community_medical_01_79",
    ["placement"] = {
      ["kind"] = "morebuilds:multi-furniture",
      ["data"] = {
        ["northSprite2"] = "location_community_medical_01_77",
        ["northTileOffsets"] = {
          { ["x"] = 0, ["y"] = 0 },
          { ["x"] = 1, ["y"] = 0 },
        },
        ["health"] = 225,
        ["northSprite"] = "location_community_medical_01_76",
        ["sprite"] = "location_community_medical_01_79",
        ["sprite2"] = "location_community_medical_01_78",
        ["tileOffsets"] = {
          { ["x"] = 0, ["y"] = 0 },
          { ["x"] = 0, ["y"] = 1 },
        },
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:furniture:electric_chair",
    ["sortKey"] = 8260,
    ["categoryId"] = "furniture:seating",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_furniture_electric_chair",
    ["descriptionKey"] = "Tooltip_MoreBuild_ElectricChair",
    ["recipeId"] = "MoreBuilds.ElectricChair",
    ["previewSprite"] = "location_community_police_01_44",
    ["placement"] = {
      ["kind"] = "morebuilds:furniture",
      ["data"] = {
        ["health"] = 225,
        ["northSprite"] = "location_community_police_01_46",
        ["eastSprite"] = "location_community_police_01_47",
        ["southSprite"] = "location_community_police_01_45",
        ["sprite"] = "location_community_police_01_44",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:furniture:piano_stool",
    ["sortKey"] = 8270,
    ["categoryId"] = "furniture:seating",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_furniture_piano_stool",
    ["descriptionKey"] = "Tooltip_MoreBuild_PianoStool",
    ["recipeId"] = "MoreBuilds.PianoStoolWood",
    ["previewSprite"] = "recreational_01_10",
    ["placement"] = {
      ["kind"] = "morebuilds:multi-furniture",
      ["data"] = {
        ["health"] = 75,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "recreational_01_15",
        ["sprite"] = "recreational_01_10",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:furniture:pool_table",
    ["sortKey"] = 8280,
    ["categoryId"] = "furniture:tables",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_furniture_pool_table",
    ["descriptionKey"] = "Tooltip_MoreBuild_PoolTable",
    ["recipeId"] = "MoreBuilds.PoolTableWood",
    ["previewSprite"] = "recreational_01_2",
    ["placement"] = {
      ["kind"] = "morebuilds:multi-furniture",
      ["data"] = {
        ["health"] = 350,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "recreational_01_7",
        ["sprite"] = "recreational_01_2",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
}

for _, definition in ipairs(definitions) do
  definition.sortKey = definition.sortKey + 90000
end

return definitions
