local definitions = {
  {
    ["id"] = "morebuilds:improvised:post_box",
    ["sortKey"] = 4450,
    ["categoryId"] = "outdoors:street",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_improvised_post_box",
    ["descriptionKey"] = "Tooltip_MoreBuild_MailboxMetal",
    ["recipeId"] = "MoreBuilds.MailboxMetal",
    ["previewSprite"] = "street_decoration_01_8",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "postbox",
        ["eastSprite"] = "street_decoration_01_10",
        ["health"] = 350,
        ["northSprite"] = "street_decoration_01_9",
        ["southSprite"] = "street_decoration_01_11",
        ["sprite"] = "street_decoration_01_8",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:roadway:1",
    ["sortKey"] = 4550,
    ["categoryId"] = "outdoors:street",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_roadway_1",
    ["descriptionKey"] = "Tooltip_MoreBuild_RoadGravel",
    ["recipeId"] = "MoreBuilds.MailboxWoodMetal",
    ["previewSprite"] = "street_decoration_01_19",
    ["placement"] = {
      ["kind"] = "morebuilds:furniture",
      ["data"] = {
        ["eastSprite"] = "street_decoration_01_21",
        ["health"] = 100,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "street_decoration_01_18",
        ["southSprite"] = "street_decoration_01_20",
        ["sprite"] = "street_decoration_01_19",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:roadway:2",
    ["sortKey"] = 4560,
    ["categoryId"] = "outdoors:street",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_roadway_2",
    ["descriptionKey"] = "Tooltip_MoreBuild_RoadGravel",
    ["recipeId"] = "MoreBuilds.FireHydrantMetal",
    ["previewSprite"] = "street_decoration_01_12",
    ["placement"] = {
      ["kind"] = "morebuilds:furniture",
      ["data"] = {
        ["eastSprite"] = "street_decoration_01_12",
        ["health"] = 100,
        ["southSprite"] = "street_decoration_01_12",
        ["sprite"] = "street_decoration_01_12",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:roadway:3",
    ["sortKey"] = 4570,
    ["categoryId"] = "outdoors:street",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_roadway_3",
    ["descriptionKey"] = "Tooltip_MoreBuild_RoadGravel",
    ["recipeId"] = "MoreBuilds.TrafficConePlastic",
    ["previewSprite"] = "street_decoration_01_26",
    ["placement"] = {
      ["kind"] = "morebuilds:furniture",
      ["data"] = {
        ["eastSprite"] = "street_decoration_01_26",
        ["health"] = 100,
        ["southSprite"] = "street_decoration_01_26",
        ["sprite"] = "street_decoration_01_26",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:roadway:4",
    ["sortKey"] = 4580,
    ["categoryId"] = "outdoors:street",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_roadway_4",
    ["descriptionKey"] = "Tooltip_MoreBuild_RoadGravel",
    ["recipeId"] = "MoreBuilds.TrafficConePlastic",
    ["previewSprite"] = "street_decoration_01_27",
    ["placement"] = {
      ["kind"] = "morebuilds:furniture",
      ["data"] = {
        ["eastSprite"] = "street_decoration_01_27",
        ["health"] = 100,
        ["southSprite"] = "street_decoration_01_27",
        ["sprite"] = "street_decoration_01_27",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:roadway:5",
    ["sortKey"] = 4590,
    ["categoryId"] = "outdoors:street",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_roadway_5",
    ["descriptionKey"] = "Tooltip_MoreBuild_RoadConcrete",
    ["recipeId"] = "MoreBuilds.RoadBarrierWood",
    ["previewSprite"] = "construction_01_9",
    ["placement"] = {
      ["kind"] = "morebuilds:furniture",
      ["data"] = {
        ["eastSprite"] = "construction_01_8",
        ["health"] = 100,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "construction_01_8",
        ["southSprite"] = "construction_01_9",
        ["sprite"] = "construction_01_9",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:sign:wood:1",
    ["sortKey"] = 4600,
    ["categoryId"] = "outdoors:street",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_sign_wood_1",
    ["descriptionKey"] = "Tooltip_MoreBuild_SignWood",
    ["recipeId"] = "MoreBuilds.SignElectric",
    ["previewSprite"] = "location_restaurant_spiffos_02_58",
    ["placement"] = {
      ["kind"] = "morebuilds:furniture",
      ["data"] = {
        ["eastSprite"] = "location_restaurant_spiffos_02_57",
        ["health"] = 100,
        ["northSprite"] = "location_restaurant_spiffos_02_59",
        ["southSprite"] = "location_restaurant_spiffos_02_56",
        ["sprite"] = "location_restaurant_spiffos_02_58",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:sign:wood:2",
    ["sortKey"] = 4610,
    ["categoryId"] = "outdoors:street",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_sign_wood_2",
    ["descriptionKey"] = "Tooltip_MoreBuild_SignWood",
    ["recipeId"] = "MoreBuilds.SignWood",
    ["previewSprite"] = "location_shop_accessories_genericsigns_01_7",
    ["placement"] = {
      ["kind"] = "morebuilds:furniture",
      ["data"] = {
        ["eastSprite"] = "location_shop_accessories_genericsigns_01_7",
        ["health"] = 100,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "location_shop_accessories_genericsigns_01_6",
        ["southSprite"] = "location_shop_accessories_genericsigns_01_6",
        ["sprite"] = "location_shop_accessories_genericsigns_01_7",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:sign:metal:1",
    ["sortKey"] = 4620,
    ["categoryId"] = "outdoors:street",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_sign_metal_1",
    ["descriptionKey"] = "Tooltip_MoreBuild_SignMetal",
    ["recipeId"] = "MoreBuilds.SignMetal",
    ["previewSprite"] = "street_decoration_01_1",
    ["placement"] = {
      ["kind"] = "morebuilds:wall",
      ["data"] = {
        ["canPassThrough"] = true,
        ["eastSprite"] = "street_decoration_01_3",
        ["health"] = 200,
        ["northSprite"] = "street_decoration_01_0",
        ["southSprite"] = "street_decoration_01_2",
        ["sprite"] = "street_decoration_01_1",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:sign:metal:2",
    ["sortKey"] = 4630,
    ["categoryId"] = "outdoors:street",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_sign_metal_2",
    ["descriptionKey"] = "Tooltip_MoreBuild_SignMetal",
    ["recipeId"] = "MoreBuilds.SignMetal",
    ["previewSprite"] = "street_decoration_01_5",
    ["placement"] = {
      ["kind"] = "morebuilds:wall",
      ["data"] = {
        ["canPassThrough"] = true,
        ["eastSprite"] = "street_decoration_01_7",
        ["health"] = 200,
        ["northSprite"] = "street_decoration_01_4",
        ["southSprite"] = "street_decoration_01_6",
        ["sprite"] = "street_decoration_01_5",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:flower_bed:flowers:1",
    ["sortKey"] = 4940,
    ["categoryId"] = "outdoors:garden",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_flower_bed_flowers_1",
    ["descriptionKey"] = "Tooltip_MoreBuild_FlowerBedSoil",
    ["recipeId"] = "MoreBuilds.FlowerBedSoil",
    ["previewSprite"] = "vegetation_ornamental_01_17",
    ["placement"] = {
      ["kind"] = "morebuilds:floor",
      ["data"] = {
        ["sprite"] = "vegetation_ornamental_01_17",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:flower_bed:flowers:2",
    ["sortKey"] = 4950,
    ["categoryId"] = "outdoors:garden",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_flower_bed_flowers_2",
    ["descriptionKey"] = "Tooltip_MoreBuild_FlowerBedSoil",
    ["recipeId"] = "MoreBuilds.FlowerBedSoil",
    ["previewSprite"] = "vegetation_ornamental_01_32",
    ["placement"] = {
      ["kind"] = "morebuilds:floor",
      ["data"] = {
        ["sprite"] = "vegetation_ornamental_01_32",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:flower_bed:flowers:3",
    ["sortKey"] = 4960,
    ["categoryId"] = "outdoors:garden",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_flower_bed_flowers_3",
    ["descriptionKey"] = "Tooltip_MoreBuild_FlowerBedSoil",
    ["recipeId"] = "MoreBuilds.FlowerBedSoil",
    ["previewSprite"] = "vegetation_ornamental_01_16",
    ["placement"] = {
      ["kind"] = "morebuilds:floor",
      ["data"] = {
        ["sprite"] = "vegetation_ornamental_01_16",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:flower_bed:flowers:4",
    ["sortKey"] = 4970,
    ["categoryId"] = "outdoors:garden",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_flower_bed_flowers_4",
    ["descriptionKey"] = "Tooltip_MoreBuild_FlowerBedSoil",
    ["recipeId"] = "MoreBuilds.FlowerBedSoil",
    ["previewSprite"] = "vegetation_ornamental_01_18",
    ["placement"] = {
      ["kind"] = "morebuilds:floor",
      ["data"] = {
        ["sprite"] = "vegetation_ornamental_01_18",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:flower_bed:flowers:5",
    ["sortKey"] = 4980,
    ["categoryId"] = "outdoors:garden",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_flower_bed_flowers_5",
    ["descriptionKey"] = "Tooltip_MoreBuild_FlowerBedSoil",
    ["recipeId"] = "MoreBuilds.FlowerBedSoil",
    ["previewSprite"] = "vegetation_ornamental_01_33",
    ["placement"] = {
      ["kind"] = "morebuilds:floor",
      ["data"] = {
        ["sprite"] = "vegetation_ornamental_01_33",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:flower_bed:flowers:6",
    ["sortKey"] = 4990,
    ["categoryId"] = "outdoors:garden",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_flower_bed_flowers_6",
    ["descriptionKey"] = "Tooltip_MoreBuild_FlowerBedSoil",
    ["recipeId"] = "MoreBuilds.FlowerBedSoil",
    ["previewSprite"] = "vegetation_ornamental_01_34",
    ["placement"] = {
      ["kind"] = "morebuilds:floor",
      ["data"] = {
        ["sprite"] = "vegetation_ornamental_01_34",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:flower_bed:stone:1",
    ["sortKey"] = 5000,
    ["categoryId"] = "outdoors:garden",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_flower_bed_stone_1",
    ["descriptionKey"] = "Tooltip_MoreBuild_FlowerBedStone",
    ["recipeId"] = "MoreBuilds.FlowerBedStone",
    ["previewSprite"] = "vegetation_ornamental_01_19",
    ["placement"] = {
      ["kind"] = "morebuilds:floor",
      ["data"] = {
        ["eastSprite"] = "vegetation_ornamental_01_29",
        ["northSprite"] = "vegetation_ornamental_01_21",
        ["southSprite"] = "vegetation_ornamental_01_23",
        ["sprite"] = "vegetation_ornamental_01_19",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:flower_bed:stone:2",
    ["sortKey"] = 5010,
    ["categoryId"] = "outdoors:garden",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_flower_bed_stone_2",
    ["descriptionKey"] = "Tooltip_MoreBuild_FlowerBedStone",
    ["recipeId"] = "MoreBuilds.FlowerBedStone",
    ["previewSprite"] = "vegetation_ornamental_01_20",
    ["placement"] = {
      ["kind"] = "morebuilds:floor",
      ["data"] = {
        ["eastSprite"] = "vegetation_ornamental_01_28",
        ["northSprite"] = "vegetation_ornamental_01_22",
        ["southSprite"] = "vegetation_ornamental_01_30",
        ["sprite"] = "vegetation_ornamental_01_20",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:flower_bed:stone:3",
    ["sortKey"] = 5020,
    ["categoryId"] = "outdoors:garden",
    ["nameKey"] = "ContextMenu_MoreBuild_PurpleandPink_Post",
    ["descriptionKey"] = "Tooltip_MoreBuild_FlowerBedStone",
    ["recipeId"] = "MoreBuilds.FlowerBedStone",
    ["previewSprite"] = "f_flowerbed_1_3",
    ["placement"] = {
      ["kind"] = "morebuilds:floor",
      ["data"] = {
        ["eastSprite"] = "f_flowerbed_1_7",
        ["northSprite"] = "f_flowerbed_1_5",
        ["southSprite"] = "f_flowerbed_1_9",
        ["sprite"] = "f_flowerbed_1_3",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:flower_bed:stone:4",
    ["sortKey"] = 5030,
    ["categoryId"] = "outdoors:garden",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_flower_bed_stone_4",
    ["descriptionKey"] = "Tooltip_MoreBuild_FlowerBedStone",
    ["recipeId"] = "MoreBuilds.FlowerBedStone",
    ["previewSprite"] = "vegetation_ornamental_01_35",
    ["placement"] = {
      ["kind"] = "morebuilds:floor",
      ["data"] = {
        ["eastSprite"] = "vegetation_ornamental_01_39",
        ["northSprite"] = "vegetation_ornamental_01_37",
        ["southSprite"] = "vegetation_ornamental_01_45",
        ["sprite"] = "vegetation_ornamental_01_35",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:flower_bed:stone:5",
    ["sortKey"] = 5040,
    ["categoryId"] = "outdoors:garden",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_flower_bed_stone_5",
    ["descriptionKey"] = "Tooltip_MoreBuild_FlowerBedStone",
    ["recipeId"] = "MoreBuilds.FlowerBedStone",
    ["previewSprite"] = "vegetation_ornamental_01_36",
    ["placement"] = {
      ["kind"] = "morebuilds:floor",
      ["data"] = {
        ["eastSprite"] = "vegetation_ornamental_01_46",
        ["northSprite"] = "vegetation_ornamental_01_38",
        ["southSprite"] = "vegetation_ornamental_01_44",
        ["sprite"] = "vegetation_ornamental_01_36",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:flower_bed:stone:6",
    ["sortKey"] = 5050,
    ["categoryId"] = "outdoors:garden",
    ["nameKey"] = "ContextMenu_MoreBuild_GrayandWhite_Post",
    ["descriptionKey"] = "Tooltip_MoreBuild_FlowerBedStone",
    ["recipeId"] = "MoreBuilds.FlowerBedStone",
    ["previewSprite"] = "f_flowerbed_1_15",
    ["placement"] = {
      ["kind"] = "morebuilds:floor",
      ["data"] = {
        ["eastSprite"] = "f_flowerbed_1_19",
        ["northSprite"] = "f_flowerbed_1_17",
        ["southSprite"] = "f_flowerbed_1_21",
        ["sprite"] = "f_flowerbed_1_15",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:bench:park",
    ["sortKey"] = 5240,
    ["categoryId"] = "outdoors:furnishings",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_bench_park",
    ["descriptionKey"] = "Tooltip_MoreBuild_BenchWood",
    ["recipeId"] = "MoreBuilds.BenchWoodMetal",
    ["previewSprite"] = "furniture_seating_outdoor_01_1",
    ["placement"] = {
      ["kind"] = "morebuilds:multi-furniture",
      ["data"] = {
        ["canPassThrough"] = true,
        ["eastSprite"] = "furniture_seating_outdoor_01_5",
        ["eastSprite2"] = "furniture_seating_outdoor_01_4",
        ["eastTileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = -1,
            ["y"] = 0,
          },
        },
        ["health"] = 150,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "furniture_seating_outdoor_01_2",
        ["sprite"] = "furniture_seating_outdoor_01_1",
        ["northSprite2"] = "furniture_seating_outdoor_01_3",
        ["northTileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = 0,
            ["y"] = -1,
          },
        },
        ["sprite2"] = "furniture_seating_outdoor_01_0",
        ["southSprite"] = "furniture_seating_outdoor_01_6",
        ["southSprite2"] = "furniture_seating_outdoor_01_7",
        ["southTileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = 0,
            ["y"] = -1,
          },
        },
        ["tileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = -1,
            ["y"] = 0,
          },
        },
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:bench:ornate_garden",
    ["sortKey"] = 5250,
    ["categoryId"] = "outdoors:furnishings",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_bench_ornate_garden",
    ["descriptionKey"] = "Tooltip_MoreBuild_BenchWood",
    ["recipeId"] = "MoreBuilds.BenchWoodMetal",
    ["previewSprite"] = "furniture_seating_outdoor_01_10",
    ["placement"] = {
      ["kind"] = "morebuilds:multi-furniture",
      ["data"] = {
        ["canPassThrough"] = true,
        ["eastSprite"] = "furniture_seating_outdoor_01_13",
        ["eastSprite2"] = "furniture_seating_outdoor_01_12",
        ["eastTileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = -1,
            ["y"] = 0,
          },
        },
        ["health"] = 150,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "furniture_seating_outdoor_01_8",
        ["sprite"] = "furniture_seating_outdoor_01_10",
        ["northSprite2"] = "furniture_seating_outdoor_01_9",
        ["northTileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = 0,
            ["y"] = -1,
          },
        },
        ["southSprite"] = "furniture_seating_outdoor_01_14",
        ["southSprite2"] = "furniture_seating_outdoor_01_15",
        ["southTileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = 0,
            ["y"] = -1,
          },
        },
        ["sprite2"] = "furniture_seating_outdoor_01_11",
        ["tileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = -1,
            ["y"] = 0,
          },
        },
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:bench:oak_garden",
    ["sortKey"] = 5260,
    ["categoryId"] = "outdoors:furnishings",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_bench_oak_garden",
    ["descriptionKey"] = "Tooltip_MoreBuild_BenchWood",
    ["recipeId"] = "MoreBuilds.BenchWoodMetal",
    ["previewSprite"] = "furniture_seating_outdoor_01_21",
    ["placement"] = {
      ["kind"] = "morebuilds:multi-furniture",
      ["data"] = {
        ["canPassThrough"] = true,
        ["health"] = 150,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "furniture_seating_outdoor_01_22",
        ["sprite"] = "furniture_seating_outdoor_01_21",
        ["northSprite2"] = "furniture_seating_outdoor_01_23",
        ["northTileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = 0,
            ["y"] = -1,
          },
        },
        ["sprite2"] = "furniture_seating_outdoor_01_20",
        ["tileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = -1,
            ["y"] = 0,
          },
        },
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:chair:canvas_beach",
    ["sortKey"] = 5280,
    ["categoryId"] = "outdoors:furnishings",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_chair_canvas_beach",
    ["descriptionKey"] = "Tooltip_MoreBuild_BeachChair",
    ["recipeId"] = "MoreBuilds.BeachChair",
    ["previewSprite"] = "furniture_seating_outdoor_01_24",
    ["placement"] = {
      ["kind"] = "morebuilds:multi-furniture",
      ["data"] = {
        ["canPassThrough"] = true,
        ["eastSprite"] = "furniture_seating_outdoor_01_28",
        ["eastSprite2"] = "furniture_seating_outdoor_01_29",
        ["eastTileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = 0,
            ["y"] = -1,
          },
        },
        ["health"] = 100,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "furniture_seating_outdoor_01_27",
        ["sprite"] = "furniture_seating_outdoor_01_24",
        ["northSprite2"] = "furniture_seating_outdoor_01_26",
        ["northTileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = -1,
            ["y"] = 0,
          },
        },
        ["southSprite"] = "furniture_seating_outdoor_01_31",
        ["southSprite2"] = "furniture_seating_outdoor_01_30",
        ["southTileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = -1,
            ["y"] = 0,
          },
        },
        ["sprite2"] = "furniture_seating_outdoor_01_25",
        ["tileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = 0,
            ["y"] = -1,
          },
        },
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:garden:stone_bird_bath",
    ["sortKey"] = 6070,
    ["categoryId"] = "outdoors:furnishings",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_garden_stone_bird_bath",
    ["descriptionKey"] = "Tooltip_MoreBuild_BirdBathStone",
    ["recipeId"] = "MoreBuilds.BirdBathStone",
    ["previewSprite"] = "vegetation_ornamental_01_50",
    ["placement"] = {
      ["kind"] = "morebuilds:furniture",
      ["data"] = {
        ["health"] = 200,
        ["northSprite"] = "vegetation_ornamental_01_51",
        ["sprite"] = "vegetation_ornamental_01_50",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:bench:sports",
    ["sortKey"] = 7090,
    ["categoryId"] = "outdoors:furnishings",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_bench_sports",
    ["descriptionKey"] = "Tooltip_MoreBuild_SportsBench",
    ["recipeId"] = "MoreBuilds.BenchWoodMetal",
    ["previewSprite"] = "furniture_seating_indoor_03_1",
    ["placement"] = {
      ["kind"] = "morebuilds:multi-furniture",
      ["data"] = {
        ["canPassThrough"] = true,
        ["health"] = 150,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "furniture_seating_indoor_03_2",
        ["sprite"] = "furniture_seating_indoor_03_1",
        ["northSprite2"] = "furniture_seating_indoor_03_3",
        ["northTileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = 0,
            ["y"] = -1,
          },
        },
        ["sprite2"] = "furniture_seating_indoor_03_0",
        ["tileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = -1,
            ["y"] = 0,
          },
        },
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:bench:wooden",
    ["sortKey"] = 7100,
    ["categoryId"] = "outdoors:furnishings",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_bench_wooden",
    ["descriptionKey"] = "Tooltip_MoreBuild_WoodenBench",
    ["recipeId"] = "MoreBuilds.BenchWoodUpholstered",
    ["previewSprite"] = "furniture_seating_indoor_03_64",
    ["placement"] = {
      ["kind"] = "morebuilds:multi-furniture",
      ["data"] = {
        ["canPassThrough"] = true,
        ["health"] = 150,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "furniture_seating_indoor_03_67",
        ["sprite"] = "furniture_seating_indoor_03_64",
        ["northSprite2"] = "furniture_seating_indoor_03_66",
        ["northTileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = -1,
            ["y"] = 0,
          },
        },
        ["sprite2"] = "furniture_seating_indoor_03_65",
        ["tileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = 0,
            ["y"] = -1,
          },
        },
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:bench:sturdy",
    ["sortKey"] = 7110,
    ["categoryId"] = "outdoors:furnishings",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_bench_sturdy",
    ["descriptionKey"] = "Tooltip_MoreBuild_WoodenBench",
    ["recipeId"] = "MoreBuilds.BenchWoodUpholstered",
    ["previewSprite"] = "furniture_seating_indoor_03_52",
    ["placement"] = {
      ["kind"] = "morebuilds:multi-furniture",
      ["data"] = {
        ["canPassThrough"] = true,
        ["health"] = 150,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "furniture_seating_indoor_03_55",
        ["sprite"] = "furniture_seating_indoor_03_52",
        ["northSprite2"] = "furniture_seating_indoor_03_54",
        ["northTileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = -1,
            ["y"] = 0,
          },
        },
        ["sprite2"] = "furniture_seating_indoor_03_53",
        ["tileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = 0,
            ["y"] = -1,
          },
        },
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:playground:slide",
    ["sortKey"] = 13600,
    ["categoryId"] = "outdoors:furnishings",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_playground_slide",
    ["descriptionKey"] = "Tooltip_MoreBuild_PlaygroundSlide",
    ["recipeId"] = "MoreBuilds.PlaygroundSlide",
    ["previewSprite"] = "location_community_park_01_18",
    ["placement"] = {
      ["kind"] = "morebuilds:multi-furniture",
      ["data"] = {
        ["eastSprite"] = "location_community_park_01_38",
        ["health"] = 500,
        ["northSprite"] = "location_community_park_01_17",
        ["southSprite"] = "location_community_park_01_31",
        ["sprite"] = "location_community_park_01_18",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:playground:play_castle",
    ["sortKey"] = 13610,
    ["categoryId"] = "outdoors:furnishings",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_playground_play_castle",
    ["descriptionKey"] = "Tooltip_MoreBuild_PlayCastle",
    ["recipeId"] = "MoreBuilds.PlayCastle",
    ["previewSprite"] = "location_community_park_01_51",
    ["placement"] = {
      ["kind"] = "morebuilds:multi-furniture",
      ["data"] = {
        ["health"] = 500,
        ["northSprite"] = "location_community_park_01_51",
        ["sprite"] = "location_community_park_01_51",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:playground:merry_go_round",
    ["sortKey"] = 13620,
    ["categoryId"] = "outdoors:furnishings",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_playground_merry_go_round",
    ["descriptionKey"] = "Tooltip_MoreBuild_MerryGoRound",
    ["recipeId"] = "MoreBuilds.MerryGoRound",
    ["previewSprite"] = "location_community_park_01_23",
    ["placement"] = {
      ["kind"] = "morebuilds:multi-furniture",
      ["data"] = {
        ["health"] = 600,
        ["northSprite"] = "location_community_park_01_23",
        ["sprite"] = "location_community_park_01_23",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:street:concrete_barrier",
    ["sortKey"] = 13630,
    ["categoryId"] = "outdoors:street",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_street_concrete_barrier",
    ["descriptionKey"] = "Tooltip_MoreBuild_ConcreteBarrier",
    ["recipeId"] = "MoreBuilds.ConcreteBarrier",
    ["previewSprite"] = "street_decoration_01_29",
    ["placement"] = {
      ["kind"] = "morebuilds:fence",
      ["data"] = {
        ["health"] = 600,
        ["northSprite"] = "street_decoration_01_28",
        ["sprite"] = "street_decoration_01_29",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:street:barrier_post",
    ["sortKey"] = 13640,
    ["categoryId"] = "outdoors:street",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_street_barrier_post",
    ["descriptionKey"] = "Tooltip_MoreBuild_BarrierPost",
    ["recipeId"] = "MoreBuilds.BarrierPostWoodMetal",
    ["previewSprite"] = "street_decoration_01_64",
    ["placement"] = {
      ["kind"] = "morebuilds:multi-furniture",
      ["data"] = {
        ["eastSprite"] = "street_decoration_01_60",
        ["health"] = 300,
        ["northSprite"] = "street_decoration_01_71",
        ["southSprite"] = "street_decoration_01_59",
        ["sprite"] = "street_decoration_01_64",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:outdoor:picnic_table_brown",
    ["sortKey"] = 13650,
    ["categoryId"] = "outdoors:furnishings",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_outdoor_picnic_table_brown",
    ["descriptionKey"] = "Tooltip_MoreBuild_PicnicTable",
    ["recipeId"] = "MoreBuilds.LargeWoodTable",
    ["previewSprite"] = "location_restaurant_generic_01_7",
    ["placement"] = {
      ["kind"] = "morebuilds:multi-furniture",
      ["data"] = {
        ["health"] = 300,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "location_restaurant_generic_01_1",
        ["sprite"] = "location_restaurant_generic_01_7",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:outdoor:picnic_table_blue",
    ["sortKey"] = 13660,
    ["categoryId"] = "outdoors:furnishings",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_outdoor_picnic_table_blue",
    ["descriptionKey"] = "Tooltip_MoreBuild_PicnicTable",
    ["recipeId"] = "MoreBuilds.LargeWoodTable",
    ["previewSprite"] = "location_restaurant_generic_01_15",
    ["placement"] = {
      ["kind"] = "morebuilds:multi-furniture",
      ["data"] = {
        ["health"] = 300,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "location_restaurant_generic_01_9",
        ["sprite"] = "location_restaurant_generic_01_15",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:outdoor:picnic_table_metal_braced",
    ["sortKey"] = 13670,
    ["categoryId"] = "outdoors:furnishings",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_outdoor_picnic_table_metal_braced",
    ["descriptionKey"] = "Tooltip_MoreBuild_MetalBracedPicnicTable",
    ["recipeId"] = "MoreBuilds.PicnicTableMetalBraced",
    ["previewSprite"] = "camping_01_15",
    ["placement"] = {
      ["kind"] = "morebuilds:multi-furniture",
      ["data"] = {
        ["health"] = 400,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "camping_01_9",
        ["sprite"] = "camping_01_15",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
}

for _, definition in ipairs(definitions) do
  definition.sortKey = definition.sortKey + 100000
end

return definitions
