local definitions = {
  {
    ["id"] = "morebuilds:dresser:1",
    ["sortKey"] = 3730,
    ["categoryId"] = "storage:cabinets-wardrobes",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_dresser_1",
    ["descriptionKey"] = "Tooltip_MoreBuild_StorageWood",
    ["recipeId"] = "MoreBuilds.StorageWood",
    ["previewSprite"] = "furniture_storage_01_46",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["canBeLockedByPadlock"] = false,
        ["containerType"] = "dresser",
        ["eastSprite"] = "furniture_storage_01_44",
        ["health"] = 200,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "furniture_storage_01_47",
        ["southSprite"] = "furniture_storage_01_45",
        ["sprite"] = "furniture_storage_01_46",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:dresser:2",
    ["sortKey"] = 3740,
    ["categoryId"] = "storage:cabinets-wardrobes",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_dresser_2",
    ["descriptionKey"] = "Tooltip_MoreBuild_StorageWood",
    ["recipeId"] = "MoreBuilds.StorageWood",
    ["previewSprite"] = "furniture_storage_01_49",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["canBeLockedByPadlock"] = false,
        ["containerType"] = "sidetable",
        ["eastSprite"] = "furniture_storage_01_50",
        ["health"] = 200,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "furniture_storage_01_48",
        ["southSprite"] = "furniture_storage_01_51",
        ["sprite"] = "furniture_storage_01_49",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:dresser:3",
    ["sortKey"] = 3750,
    ["categoryId"] = "storage:cabinets-wardrobes",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_dresser_3",
    ["descriptionKey"] = "Tooltip_MoreBuild_StorageWood",
    ["recipeId"] = "MoreBuilds.StorageWood",
    ["previewSprite"] = "furniture_storage_01_12",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["canBeLockedByPadlock"] = false,
        ["containerType"] = "dresser",
        ["eastSprite"] = "furniture_storage_01_14",
        ["health"] = 200,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "furniture_storage_01_13",
        ["southSprite"] = "furniture_storage_01_15",
        ["sprite"] = "furniture_storage_01_12",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:dresser:4",
    ["sortKey"] = 3760,
    ["categoryId"] = "storage:cabinets-wardrobes",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_dresser_4",
    ["descriptionKey"] = "Tooltip_MoreBuild_StorageWood",
    ["recipeId"] = "MoreBuilds.StorageWood",
    ["previewSprite"] = "furniture_storage_01_32",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["canBeLockedByPadlock"] = false,
        ["containerType"] = "dresser",
        ["eastSprite"] = "furniture_storage_01_34",
        ["health"] = 200,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "furniture_storage_01_33",
        ["southSprite"] = "furniture_storage_01_35",
        ["sprite"] = "furniture_storage_01_32",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:dresser:5",
    ["sortKey"] = 3770,
    ["categoryId"] = "storage:cabinets-wardrobes",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_dresser_5",
    ["descriptionKey"] = "Tooltip_MoreBuild_StorageWood",
    ["recipeId"] = "MoreBuilds.StorageWood",
    ["previewSprite"] = "furniture_storage_01_8",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["canBeLockedByPadlock"] = false,
        ["containerType"] = "dresser",
        ["eastSprite"] = "furniture_storage_01_10",
        ["health"] = 200,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "furniture_storage_01_9",
        ["southSprite"] = "furniture_storage_01_11",
        ["sprite"] = "furniture_storage_01_8",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:other_furniture:1",
    ["sortKey"] = 3780,
    ["categoryId"] = "storage:cabinets-wardrobes",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_other_furniture_1",
    ["descriptionKey"] = "Tooltip_MoreBuild_StorageWood",
    ["recipeId"] = "MoreBuilds.FileCabinetMetal",
    ["previewSprite"] = "location_business_office_generic_01_16",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["canBeLockedByPadlock"] = false,
        ["containerType"] = "filingcabinet",
        ["eastSprite"] = "location_business_office_generic_01_24",
        ["health"] = 200,
        ["northSprite"] = "location_business_office_generic_01_17",
        ["southSprite"] = "location_business_office_generic_01_25",
        ["sprite"] = "location_business_office_generic_01_16",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:other_furniture:2",
    ["sortKey"] = 3790,
    ["categoryId"] = "storage:cabinets-wardrobes",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_other_furniture_2",
    ["descriptionKey"] = "Tooltip_MoreBuild_StorageWood",
    ["recipeId"] = "MoreBuilds.FileCabinetMetal",
    ["previewSprite"] = "location_business_office_generic_01_32",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["canBeLockedByPadlock"] = false,
        ["containerType"] = "filingcabinet",
        ["eastSprite"] = "location_business_office_generic_01_34",
        ["health"] = 200,
        ["northSprite"] = "location_business_office_generic_01_33",
        ["southSprite"] = "location_business_office_generic_01_35",
        ["sprite"] = "location_business_office_generic_01_32",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:other_furniture:3",
    ["sortKey"] = 3800,
    ["categoryId"] = "storage:cabinets-wardrobes",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_other_furniture_3",
    ["descriptionKey"] = "Tooltip_MoreBuild_StorageWood",
    ["recipeId"] = "MoreBuilds.StorageWood",
    ["previewSprite"] = "location_community_medical_01_36",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["canBeLockedByPadlock"] = false,
        ["containerType"] = "sidetable",
        ["eastSprite"] = "location_community_medical_01_38",
        ["health"] = 200,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "location_community_medical_01_37",
        ["southSprite"] = "location_community_medical_01_39",
        ["sprite"] = "location_community_medical_01_36",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:other_furniture:4",
    ["sortKey"] = 3810,
    ["categoryId"] = "furniture:tables",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_other_furniture_4",
    ["descriptionKey"] = "Tooltip_MoreBuild_StorageWood",
    ["recipeId"] = "MoreBuilds.StorageWood",
    ["previewSprite"] = "furniture_storage_01_53",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["canBeLockedByPadlock"] = false,
        ["containerType"] = "sidetable",
        ["eastSprite"] = "furniture_storage_01_54",
        ["health"] = 200,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "furniture_storage_01_52",
        ["southSprite"] = "furniture_storage_01_55",
        ["sprite"] = "furniture_storage_01_53",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:other_furniture:5",
    ["sortKey"] = 3820,
    ["categoryId"] = "furniture:seating",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_other_furniture_5",
    ["descriptionKey"] = "Tooltip_MoreBuild_StorageWood",
    ["recipeId"] = "MoreBuilds.StorageWood",
    ["previewSprite"] = "location_community_school_01_4",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["canBeLockedByPadlock"] = false,
        ["containerType"] = "desk",
        ["eastSprite"] = "location_community_school_01_7",
        ["health"] = 200,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "location_community_school_01_5",
        ["southSprite"] = "location_community_school_01_6",
        ["sprite"] = "location_community_school_01_4",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:other_furniture:6",
    ["sortKey"] = 3830,
    ["categoryId"] = "furniture:seating",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_other_furniture_6",
    ["descriptionKey"] = "Tooltip_MoreBuild_StorageWood",
    ["recipeId"] = "MoreBuilds.StorageWood",
    ["previewSprite"] = "location_community_school_01_12",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["canBeLockedByPadlock"] = false,
        ["containerType"] = "desk",
        ["eastSprite"] = "location_community_school_01_15",
        ["health"] = 200,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "location_community_school_01_13",
        ["southSprite"] = "location_community_school_01_14",
        ["sprite"] = "location_community_school_01_12",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:other_furniture:7",
    ["sortKey"] = 3840,
    ["categoryId"] = "storage:cabinets-wardrobes",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_other_furniture_7",
    ["descriptionKey"] = "Tooltip_MoreBuild_StorageWood",
    ["recipeId"] = "MoreBuilds.StorageWood",
    ["previewSprite"] = "furniture_tables_low_01_12",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["canBeLockedByPadlock"] = false,
        ["containerType"] = "sidetable",
        ["eastSprite"] = "furniture_tables_low_01_12",
        ["health"] = 200,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "furniture_tables_low_01_13",
        ["southSprite"] = "furniture_tables_low_01_13",
        ["sprite"] = "furniture_tables_low_01_12",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:bookshelf:2",
    ["sortKey"] = 3860,
    ["categoryId"] = "storage:shelves-counters",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_bookshelf_2",
    ["descriptionKey"] = "Tooltip_MoreBuild_BookshelfWood",
    ["recipeId"] = "MoreBuilds.BookshelfWood",
    ["previewSprite"] = "furniture_shelving_01_45",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "shelves",
        ["eastSprite"] = "furniture_shelving_01_47",
        ["health"] = 250,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "furniture_shelving_01_44",
        ["southSprite"] = "furniture_shelving_01_46",
        ["sprite"] = "furniture_shelving_01_45",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:bar_element:1:1",
    ["sortKey"] = 3870,
    ["categoryId"] = "storage:shelves-counters",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_bar_element_1_1",
    ["descriptionKey"] = "Tooltip_MoreBuild_CounterWood",
    ["recipeId"] = "MoreBuilds.CounterWood",
    ["previewSprite"] = "location_restaurant_pizzawhirled_01_35",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "counter",
        ["eastSprite"] = "location_restaurant_pizzawhirled_01_39",
        ["health"] = 200,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "location_restaurant_pizzawhirled_01_37",
        ["southSprite"] = "location_restaurant_pizzawhirled_01_33",
        ["sprite"] = "location_restaurant_pizzawhirled_01_35",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:bar_element:1:2",
    ["sortKey"] = 3880,
    ["categoryId"] = "storage:shelves-counters",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_bar_element_1_2",
    ["descriptionKey"] = "Tooltip_MoreBuild_CounterWood",
    ["recipeId"] = "MoreBuilds.CounterWood",
    ["previewSprite"] = "location_restaurant_pizzawhirled_01_32",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "counter",
        ["eastSprite"] = "location_restaurant_pizzawhirled_01_38",
        ["health"] = 200,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "location_restaurant_pizzawhirled_01_36",
        ["southSprite"] = "location_restaurant_pizzawhirled_01_34",
        ["sprite"] = "location_restaurant_pizzawhirled_01_32",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:bar_element:1:3",
    ["sortKey"] = 3890,
    ["categoryId"] = "storage:shelves-counters",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_bar_element_1_3",
    ["descriptionKey"] = "Tooltip_MoreBuild_CounterWood",
    ["recipeId"] = "MoreBuilds.CounterWoodGlass",
    ["previewSprite"] = "location_restaurant_seahorse_01_45",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "counter",
        ["eastSprite"] = "location_restaurant_seahorse_01_41",
        ["health"] = 200,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "location_restaurant_seahorse_01_43",
        ["southSprite"] = "location_restaurant_seahorse_01_47",
        ["sprite"] = "location_restaurant_seahorse_01_45",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:bar_element:1:4",
    ["sortKey"] = 3900,
    ["categoryId"] = "storage:shelves-counters",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_bar_element_1_4",
    ["descriptionKey"] = "Tooltip_MoreBuild_CounterWood",
    ["recipeId"] = "MoreBuilds.CounterWoodGlass",
    ["previewSprite"] = "location_restaurant_seahorse_01_44",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "counter",
        ["eastSprite"] = "location_restaurant_seahorse_01_40",
        ["health"] = 200,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "location_restaurant_seahorse_01_42",
        ["southSprite"] = "location_restaurant_seahorse_01_46",
        ["sprite"] = "location_restaurant_seahorse_01_44",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:bar_element:1:5",
    ["sortKey"] = 3910,
    ["categoryId"] = "storage:shelves-counters",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_bar_element_1_5",
    ["descriptionKey"] = "Tooltip_MoreBuild_CounterWood",
    ["recipeId"] = "MoreBuilds.CounterWood",
    ["previewSprite"] = "location_restaurant_spiffos_01_59",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "counter",
        ["eastSprite"] = "location_restaurant_spiffos_01_63",
        ["health"] = 200,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "location_restaurant_spiffos_01_61",
        ["southSprite"] = "location_restaurant_spiffos_01_57",
        ["sprite"] = "location_restaurant_spiffos_01_59",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:bar_element:1:6",
    ["sortKey"] = 3920,
    ["categoryId"] = "storage:shelves-counters",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_bar_element_1_6",
    ["descriptionKey"] = "Tooltip_MoreBuild_CounterWood",
    ["recipeId"] = "MoreBuilds.CounterWood",
    ["previewSprite"] = "location_restaurant_spiffos_01_56",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "counter",
        ["eastSprite"] = "location_restaurant_spiffos_01_62",
        ["health"] = 200,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "location_restaurant_spiffos_01_60",
        ["southSprite"] = "location_restaurant_spiffos_01_58",
        ["sprite"] = "location_restaurant_spiffos_01_56",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:bar_element:1:7",
    ["sortKey"] = 3930,
    ["categoryId"] = "storage:shelves-counters",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_bar_element_1_7",
    ["descriptionKey"] = "Tooltip_MoreBuild_CounterWood",
    ["recipeId"] = "MoreBuilds.CounterWood",
    ["previewSprite"] = "location_restaurant_diner_01_27",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "counter",
        ["eastSprite"] = "location_restaurant_diner_01_31",
        ["health"] = 200,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "location_restaurant_diner_01_29",
        ["southSprite"] = "location_restaurant_diner_01_25",
        ["sprite"] = "location_restaurant_diner_01_27",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:bar_element:1:8",
    ["sortKey"] = 3940,
    ["categoryId"] = "storage:shelves-counters",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_bar_element_1_8",
    ["descriptionKey"] = "Tooltip_MoreBuild_CounterWood",
    ["recipeId"] = "MoreBuilds.CounterWood",
    ["previewSprite"] = "location_restaurant_diner_01_26",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "counter",
        ["eastSprite"] = "location_restaurant_diner_01_30",
        ["health"] = 200,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "location_restaurant_diner_01_28",
        ["southSprite"] = "location_restaurant_diner_01_24",
        ["sprite"] = "location_restaurant_diner_01_26",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:bar_element:1:9",
    ["sortKey"] = 3950,
    ["categoryId"] = "storage:shelves-counters",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_bar_element_1_9",
    ["descriptionKey"] = "Tooltip_MoreBuild_CounterWood",
    ["recipeId"] = "MoreBuilds.CounterWood",
    ["previewSprite"] = "location_shop_zippee_01_19",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "counter",
        ["eastSprite"] = "location_shop_zippee_01_23",
        ["health"] = 200,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "location_shop_zippee_01_21",
        ["southSprite"] = "location_shop_zippee_01_17",
        ["sprite"] = "location_shop_zippee_01_19",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:bar_element:1:10",
    ["sortKey"] = 3960,
    ["categoryId"] = "storage:shelves-counters",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_bar_element_1_10",
    ["descriptionKey"] = "Tooltip_MoreBuild_CounterWood",
    ["recipeId"] = "MoreBuilds.CounterWood",
    ["previewSprite"] = "location_shop_zippee_01_18",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "counter",
        ["eastSprite"] = "location_shop_zippee_01_22",
        ["health"] = 200,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "location_shop_zippee_01_20",
        ["southSprite"] = "location_shop_zippee_01_16",
        ["sprite"] = "location_shop_zippee_01_18",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:bar_element:2:1",
    ["sortKey"] = 3970,
    ["categoryId"] = "storage:shelves-counters",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_bar_element_2_1",
    ["descriptionKey"] = "Tooltip_MoreBuild_CounterWood",
    ["recipeId"] = "MoreBuilds.CounterWood",
    ["previewSprite"] = "fixtures_counters_01_3",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "counter",
        ["eastSprite"] = "fixtures_counters_01_7",
        ["health"] = 200,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "fixtures_counters_01_5",
        ["southSprite"] = "fixtures_counters_01_1",
        ["sprite"] = "fixtures_counters_01_3",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:bar_element:2:2",
    ["sortKey"] = 3980,
    ["categoryId"] = "storage:shelves-counters",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_bar_element_2_2",
    ["descriptionKey"] = "Tooltip_MoreBuild_CounterWood",
    ["recipeId"] = "MoreBuilds.CounterWood",
    ["previewSprite"] = "fixtures_counters_01_2",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "counter",
        ["eastSprite"] = "fixtures_counters_01_6",
        ["health"] = 200,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "fixtures_counters_01_4",
        ["southSprite"] = "fixtures_counters_01_0",
        ["sprite"] = "fixtures_counters_01_2",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:bar_element:2:3",
    ["sortKey"] = 3990,
    ["categoryId"] = "storage:shelves-counters",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_bar_element_2_3",
    ["descriptionKey"] = "Tooltip_MoreBuild_CounterWood",
    ["recipeId"] = "MoreBuilds.CounterWood",
    ["previewSprite"] = "fixtures_counters_01_43",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "counter",
        ["eastSprite"] = "fixtures_counters_01_47",
        ["health"] = 200,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "fixtures_counters_01_45",
        ["southSprite"] = "fixtures_counters_01_41",
        ["sprite"] = "fixtures_counters_01_43",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:bar_element:2:4",
    ["sortKey"] = 4000,
    ["categoryId"] = "storage:shelves-counters",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_bar_element_2_4",
    ["descriptionKey"] = "Tooltip_MoreBuild_CounterWood",
    ["recipeId"] = "MoreBuilds.CounterWood",
    ["previewSprite"] = "fixtures_counters_01_42",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "counter",
        ["eastSprite"] = "fixtures_counters_01_46",
        ["health"] = 200,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "fixtures_counters_01_44",
        ["southSprite"] = "fixtures_counters_01_40",
        ["sprite"] = "fixtures_counters_01_42",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:bar_element:2:5",
    ["sortKey"] = 4010,
    ["categoryId"] = "storage:shelves-counters",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_bar_element_2_5",
    ["descriptionKey"] = "Tooltip_MoreBuild_CounterWood",
    ["recipeId"] = "MoreBuilds.CounterWood",
    ["previewSprite"] = "fixtures_counters_01_51",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "counter",
        ["eastSprite"] = "fixtures_counters_01_55",
        ["health"] = 200,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "fixtures_counters_01_53",
        ["southSprite"] = "fixtures_counters_01_49",
        ["sprite"] = "fixtures_counters_01_51",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:bar_element:2:6",
    ["sortKey"] = 4020,
    ["categoryId"] = "storage:shelves-counters",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_bar_element_2_6",
    ["descriptionKey"] = "Tooltip_MoreBuild_CounterWood",
    ["recipeId"] = "MoreBuilds.CounterWood",
    ["previewSprite"] = "fixtures_counters_01_50",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "counter",
        ["eastSprite"] = "fixtures_counters_01_54",
        ["health"] = 200,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "fixtures_counters_01_52",
        ["southSprite"] = "fixtures_counters_01_48",
        ["sprite"] = "fixtures_counters_01_50",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:bar_element:2:7",
    ["sortKey"] = 4030,
    ["categoryId"] = "storage:shelves-counters",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_bar_element_2_7",
    ["descriptionKey"] = "Tooltip_MoreBuild_CounterWood",
    ["recipeId"] = "MoreBuilds.CounterWood",
    ["previewSprite"] = "fixtures_counters_01_59",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "counter",
        ["eastSprite"] = "fixtures_counters_01_63",
        ["health"] = 200,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "fixtures_counters_01_61",
        ["southSprite"] = "fixtures_counters_01_57",
        ["sprite"] = "fixtures_counters_01_59",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:bar_element:2:8",
    ["sortKey"] = 4040,
    ["categoryId"] = "storage:shelves-counters",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_bar_element_2_8",
    ["descriptionKey"] = "Tooltip_MoreBuild_CounterWood",
    ["recipeId"] = "MoreBuilds.CounterWood",
    ["previewSprite"] = "fixtures_counters_01_58",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "counter",
        ["eastSprite"] = "fixtures_counters_01_62",
        ["health"] = 200,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "fixtures_counters_01_60",
        ["southSprite"] = "fixtures_counters_01_56",
        ["sprite"] = "fixtures_counters_01_58",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:bar_element:2:9",
    ["sortKey"] = 4050,
    ["categoryId"] = "storage:shelves-counters",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_bar_element_2_9",
    ["descriptionKey"] = "Tooltip_MoreBuild_CounterWood",
    ["recipeId"] = "MoreBuilds.CounterWood",
    ["previewSprite"] = "fixtures_counters_01_67",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "counter",
        ["eastSprite"] = "fixtures_counters_01_71",
        ["health"] = 200,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "fixtures_counters_01_69",
        ["southSprite"] = "fixtures_counters_01_65",
        ["sprite"] = "fixtures_counters_01_67",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:bar_element:2:10",
    ["sortKey"] = 4060,
    ["categoryId"] = "storage:shelves-counters",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_bar_element_2_10",
    ["descriptionKey"] = "Tooltip_MoreBuild_CounterWood",
    ["recipeId"] = "MoreBuilds.CounterWood",
    ["previewSprite"] = "fixtures_counters_01_66",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "counter",
        ["eastSprite"] = "fixtures_counters_01_70",
        ["health"] = 200,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "fixtures_counters_01_68",
        ["southSprite"] = "fixtures_counters_01_64",
        ["sprite"] = "fixtures_counters_01_66",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:bar_element:3:1",
    ["sortKey"] = 4070,
    ["categoryId"] = "storage:shelves-counters",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_bar_element_3_1",
    ["descriptionKey"] = "Tooltip_MoreBuild_CounterWood",
    ["recipeId"] = "MoreBuilds.CounterWood",
    ["previewSprite"] = "location_restaurant_bar_01_6",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "counter",
        ["eastSprite"] = "location_restaurant_bar_01_2",
        ["health"] = 200,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "location_restaurant_bar_01_4",
        ["southSprite"] = "location_restaurant_bar_01_0",
        ["sprite"] = "location_restaurant_bar_01_6",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:bar_element:3:2",
    ["sortKey"] = 4080,
    ["categoryId"] = "storage:shelves-counters",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_bar_element_3_2",
    ["descriptionKey"] = "Tooltip_MoreBuild_CounterWood",
    ["recipeId"] = "MoreBuilds.CounterWood",
    ["previewSprite"] = "location_restaurant_bar_01_7",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "counter",
        ["eastSprite"] = "location_restaurant_bar_01_3",
        ["health"] = 200,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "location_restaurant_bar_01_5",
        ["southSprite"] = "location_restaurant_bar_01_1",
        ["sprite"] = "location_restaurant_bar_01_7",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:bar_element:3:3",
    ["sortKey"] = 4090,
    ["categoryId"] = "storage:shelves-counters",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_bar_element_3_3",
    ["descriptionKey"] = "Tooltip_MoreBuild_CounterWood",
    ["recipeId"] = "MoreBuilds.CounterWood",
    ["previewSprite"] = "location_restaurant_pie_01_43",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "counter",
        ["eastSprite"] = "location_restaurant_pie_01_47",
        ["health"] = 200,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "location_restaurant_pie_01_45",
        ["southSprite"] = "location_restaurant_pie_01_41",
        ["sprite"] = "location_restaurant_pie_01_43",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:bar_element:3:4",
    ["sortKey"] = 4100,
    ["categoryId"] = "storage:shelves-counters",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_bar_element_3_4",
    ["descriptionKey"] = "Tooltip_MoreBuild_CounterWood",
    ["recipeId"] = "MoreBuilds.CounterWood",
    ["previewSprite"] = "location_restaurant_pie_01_42",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "counter",
        ["eastSprite"] = "location_restaurant_pie_01_46",
        ["health"] = 200,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "location_restaurant_pie_01_44",
        ["southSprite"] = "location_restaurant_pie_01_40",
        ["sprite"] = "location_restaurant_pie_01_42",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:bar_element:3:5",
    ["sortKey"] = 4110,
    ["categoryId"] = "storage:shelves-counters",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_bar_element_3_5",
    ["descriptionKey"] = "Tooltip_MoreBuild_CounterWood",
    ["recipeId"] = "MoreBuilds.CounterWood",
    ["previewSprite"] = "location_entertainment_theatre_01_11",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "counter",
        ["eastSprite"] = "location_entertainment_theatre_01_15",
        ["health"] = 200,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "location_entertainment_theatre_01_13",
        ["southSprite"] = "location_entertainment_theatre_01_9",
        ["sprite"] = "location_entertainment_theatre_01_11",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:bar_element:3:6",
    ["sortKey"] = 4120,
    ["categoryId"] = "storage:shelves-counters",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_bar_element_3_6",
    ["descriptionKey"] = "Tooltip_MoreBuild_CounterWood",
    ["recipeId"] = "MoreBuilds.CounterWood",
    ["previewSprite"] = "location_entertainment_theatre_01_10",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "counter",
        ["eastSprite"] = "location_entertainment_theatre_01_14",
        ["health"] = 200,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "location_entertainment_theatre_01_12",
        ["southSprite"] = "location_entertainment_theatre_01_8",
        ["sprite"] = "location_entertainment_theatre_01_10",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:bar_element:3:7",
    ["sortKey"] = 4130,
    ["categoryId"] = "storage:shelves-counters",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_bar_element_3_7",
    ["descriptionKey"] = "Tooltip_MoreBuild_CounterWood",
    ["recipeId"] = "MoreBuilds.CounterWood",
    ["previewSprite"] = "location_shop_fossoil_01_19",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "counter",
        ["eastSprite"] = "location_shop_fossoil_01_23",
        ["health"] = 200,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "location_shop_fossoil_01_21",
        ["southSprite"] = "location_shop_fossoil_01_17",
        ["sprite"] = "location_shop_fossoil_01_19",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:bar_element:3:8",
    ["sortKey"] = 4140,
    ["categoryId"] = "storage:shelves-counters",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_bar_element_3_8",
    ["descriptionKey"] = "Tooltip_MoreBuild_CounterWood",
    ["recipeId"] = "MoreBuilds.CounterWood",
    ["previewSprite"] = "location_shop_fossoil_01_18",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "counter",
        ["eastSprite"] = "location_shop_fossoil_01_22",
        ["health"] = 200,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "location_shop_fossoil_01_20",
        ["southSprite"] = "location_shop_fossoil_01_16",
        ["sprite"] = "location_shop_fossoil_01_18",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:bar_element:3:9",
    ["sortKey"] = 4150,
    ["categoryId"] = "storage:shelves-counters",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_bar_element_3_9",
    ["descriptionKey"] = "Tooltip_MoreBuild_CounterWood",
    ["recipeId"] = "MoreBuilds.CounterWood",
    ["previewSprite"] = "location_shop_gas2go_01_19",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "counter",
        ["eastSprite"] = "location_shop_gas2go_01_23",
        ["health"] = 200,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "location_shop_gas2go_01_21",
        ["southSprite"] = "location_shop_gas2go_01_17",
        ["sprite"] = "location_shop_gas2go_01_19",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:bar_element:3:10",
    ["sortKey"] = 4160,
    ["categoryId"] = "storage:shelves-counters",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_bar_element_3_10",
    ["descriptionKey"] = "Tooltip_MoreBuild_CounterWood",
    ["recipeId"] = "MoreBuilds.CounterWood",
    ["previewSprite"] = "location_shop_gas2go_01_18",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "counter",
        ["eastSprite"] = "location_shop_gas2go_01_22",
        ["health"] = 200,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "location_shop_gas2go_01_20",
        ["southSprite"] = "location_shop_gas2go_01_16",
        ["sprite"] = "location_shop_gas2go_01_18",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:bar_element:4:1",
    ["sortKey"] = 4170,
    ["categoryId"] = "storage:shelves-counters",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_bar_element_4_1",
    ["descriptionKey"] = "Tooltip_MoreBuild_CounterWood",
    ["recipeId"] = "MoreBuilds.CounterWood",
    ["previewSprite"] = "fixtures_counters_01_75",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "counter",
        ["eastSprite"] = "fixtures_counters_01_79",
        ["health"] = 200,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "fixtures_counters_01_77",
        ["southSprite"] = "fixtures_counters_01_73",
        ["sprite"] = "fixtures_counters_01_75",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:bar_element:4:2",
    ["sortKey"] = 4180,
    ["categoryId"] = "storage:shelves-counters",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_bar_element_4_2",
    ["descriptionKey"] = "Tooltip_MoreBuild_CounterWood",
    ["recipeId"] = "MoreBuilds.CounterWood",
    ["previewSprite"] = "fixtures_counters_01_74",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "counter",
        ["eastSprite"] = "fixtures_counters_01_78",
        ["health"] = 200,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "fixtures_counters_01_76",
        ["southSprite"] = "fixtures_counters_01_72",
        ["sprite"] = "fixtures_counters_01_74",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:bar_element:4:3",
    ["sortKey"] = 4190,
    ["categoryId"] = "storage:shelves-counters",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_bar_element_4_3",
    ["descriptionKey"] = "Tooltip_MoreBuild_CounterWood",
    ["recipeId"] = "MoreBuilds.CounterWood",
    ["previewSprite"] = "location_trailer_02_19",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "counter",
        ["eastSprite"] = "location_trailer_02_21",
        ["health"] = 200,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "location_trailer_02_18",
        ["southSprite"] = "location_trailer_02_20",
        ["sprite"] = "location_trailer_02_19",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:bar_element:4:4",
    ["sortKey"] = 4200,
    ["categoryId"] = "storage:shelves-counters",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_bar_element_4_4",
    ["descriptionKey"] = "Tooltip_MoreBuild_CounterWood",
    ["recipeId"] = "MoreBuilds.CounterWood",
    ["previewSprite"] = "location_hospitality_sunstarmotel_02_13",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "counter",
        ["eastSprite"] = "location_hospitality_sunstarmotel_02_15",
        ["health"] = 200,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "location_hospitality_sunstarmotel_02_14",
        ["southSprite"] = "location_hospitality_sunstarmotel_02_12",
        ["sprite"] = "location_hospitality_sunstarmotel_02_13",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:bar_element:4:5",
    ["sortKey"] = 4210,
    ["categoryId"] = "storage:shelves-counters",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_bar_element_4_5",
    ["descriptionKey"] = "Tooltip_MoreBuild_CounterWood",
    ["recipeId"] = "MoreBuilds.CounterWood",
    ["previewSprite"] = "fixtures_counters_01_11",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "counter",
        ["eastSprite"] = "fixtures_counters_01_15",
        ["health"] = 200,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "fixtures_counters_01_13",
        ["southSprite"] = "fixtures_counters_01_9",
        ["sprite"] = "fixtures_counters_01_11",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:bar_element:4:6",
    ["sortKey"] = 4220,
    ["categoryId"] = "storage:shelves-counters",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_bar_element_4_6",
    ["descriptionKey"] = "Tooltip_MoreBuild_CounterWood",
    ["recipeId"] = "MoreBuilds.CounterWood",
    ["previewSprite"] = "fixtures_counters_01_10",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "counter",
        ["eastSprite"] = "fixtures_counters_01_14",
        ["health"] = 200,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "fixtures_counters_01_12",
        ["southSprite"] = "fixtures_counters_01_8",
        ["sprite"] = "fixtures_counters_01_10",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:metal_locker:lock_boxes",
    ["sortKey"] = 4270,
    ["categoryId"] = "storage:cabinets-wardrobes",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_metal_locker_lock_boxes",
    ["descriptionKey"] = "Tooltip_MoreBuild_LockerMetal",
    ["recipeId"] = "MoreBuilds.LockerMetal",
    ["previewSprite"] = "location_business_bank_01_43",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "vendingsnack",
        ["eastSprite"] = "location_business_bank_01_45",
        ["health"] = 350,
        ["northSprite"] = "location_business_bank_01_42",
        ["southSprite"] = "location_business_bank_01_44",
        ["sprite"] = "location_business_bank_01_43",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:metal_locker:blue",
    ["sortKey"] = 4280,
    ["categoryId"] = "storage:cabinets-wardrobes",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_metal_locker_blue",
    ["descriptionKey"] = "Tooltip_MoreBuild_LockerMetal",
    ["recipeId"] = "MoreBuilds.LockerMetal",
    ["previewSprite"] = "furniture_storage_02_4",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "locker",
        ["eastSprite"] = "furniture_storage_02_6",
        ["health"] = 350,
        ["northSprite"] = "furniture_storage_02_5",
        ["southSprite"] = "furniture_storage_02_7",
        ["sprite"] = "furniture_storage_02_4",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:metal_locker:yellow",
    ["sortKey"] = 4290,
    ["categoryId"] = "storage:cabinets-wardrobes",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_metal_locker_yellow",
    ["descriptionKey"] = "Tooltip_MoreBuild_LockerMetal",
    ["recipeId"] = "MoreBuilds.LockerMetal",
    ["previewSprite"] = "furniture_storage_02_12",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "locker",
        ["eastSprite"] = "furniture_storage_02_14",
        ["health"] = 350,
        ["northSprite"] = "furniture_storage_02_13",
        ["southSprite"] = "furniture_storage_02_15",
        ["sprite"] = "furniture_storage_02_12",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:metal_locker:military",
    ["sortKey"] = 4300,
    ["categoryId"] = "storage:cabinets-wardrobes",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_metal_locker_military",
    ["descriptionKey"] = "Tooltip_MoreBuild_LockerMetal",
    ["recipeId"] = "MoreBuilds.LockerMetal",
    ["previewSprite"] = "location_military_generic_01_23",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "militarylocker",
        ["eastSprite"] = "location_military_generic_01_30",
        ["health"] = 350,
        ["northSprite"] = "location_military_generic_01_22",
        ["southSprite"] = "location_military_generic_01_31",
        ["sprite"] = "location_military_generic_01_23",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:crate:half",
    ["sortKey"] = 4310,
    ["categoryId"] = "outdoors:furnishings",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_crate_half",
    ["descriptionKey"] = "Tooltip_MoreBuild_CrateWood",
    ["recipeId"] = "MoreBuilds.CrateWood",
    ["previewSprite"] = "location_shop_greenes_01_35",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "smallcrate",
        ["health"] = 200,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "location_shop_greenes_01_36",
        ["sprite"] = "location_shop_greenes_01_35",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:crate:grocery_box",
    ["sortKey"] = 4320,
    ["categoryId"] = "storage:containers",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_crate_grocery_box",
    ["descriptionKey"] = "Tooltip_MoreBuild_CratePlastic",
    ["recipeId"] = "MoreBuilds.CratePlastic",
    ["previewSprite"] = "location_shop_greenes_01_37",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["canPassThrough"] = true,
        ["containerType"] = "smallbox",
        ["health"] = 80,
        ["northSprite"] = "location_shop_greenes_01_38",
        ["sprite"] = "location_shop_greenes_01_37",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:crate:outhouse_box",
    ["sortKey"] = 4330,
    ["categoryId"] = "storage:containers",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_crate_outhouse_box",
    ["descriptionKey"] = "Tooltip_MoreBuild_CrateWood",
    ["recipeId"] = "MoreBuilds.CrateWood",
    ["previewSprite"] = "fixtures_bathroom_02_25",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["canPassThrough"] = true,
        ["containerType"] = "bin",
        ["eastSprite"] = "fixtures_bathroom_02_27",
        ["health"] = 200,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "fixtures_bathroom_02_24",
        ["southSprite"] = "fixtures_bathroom_02_26",
        ["sprite"] = "fixtures_bathroom_02_25",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:crate:theatre_storage",
    ["sortKey"] = 4340,
    ["categoryId"] = "storage:containers",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_crate_theatre_storage",
    ["descriptionKey"] = "Tooltip_MoreBuild_CrateWood",
    ["recipeId"] = "MoreBuilds.CrateWood",
    ["previewSprite"] = "location_entertainment_theatre_01_16",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "counter",
        ["health"] = 200,
        ["healthFromCarpentry"] = true,
        ["sprite"] = "location_entertainment_theatre_01_16",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:crate:dog_house",
    ["sortKey"] = 4350,
    ["categoryId"] = "storage:containers",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_crate_dog_house",
    ["descriptionKey"] = "Tooltip_MoreBuild_CrateWood",
    ["recipeId"] = "MoreBuilds.CrateWood",
    ["previewSprite"] = "location_farm_accesories_01_8",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "doghouse",
        ["eastSprite"] = "location_farm_accesories_01_10",
        ["health"] = 200,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "location_farm_accesories_01_9",
        ["southSprite"] = "location_farm_accesories_01_11",
        ["sprite"] = "location_farm_accesories_01_8",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:crate:military_green",
    ["sortKey"] = 4360,
    ["categoryId"] = "storage:containers",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_crate_military_green",
    ["descriptionKey"] = "Tooltip_MoreBuild_CrateMilitaryWood",
    ["recipeId"] = "MoreBuilds.CrateMilitaryMetal",
    ["previewSprite"] = "location_military_generic_01_0",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerCapacity"] = 100,
        ["containerType"] = "militarycrate",
        ["health"] = 200,
        ["northSprite"] = "location_military_generic_01_1",
        ["sprite"] = "location_military_generic_01_0",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:crate:military_gray",
    ["sortKey"] = 4370,
    ["categoryId"] = "storage:containers",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_crate_military_gray",
    ["descriptionKey"] = "Tooltip_MoreBuild_CrateMilitaryWood",
    ["recipeId"] = "MoreBuilds.CrateMilitaryMetal",
    ["previewSprite"] = "location_military_generic_01_8",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerCapacity"] = 100,
        ["containerType"] = "militarycrate",
        ["health"] = 200,
        ["northSprite"] = "location_military_generic_01_9",
        ["sprite"] = "location_military_generic_01_8",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:crate:cardboard:1",
    ["sortKey"] = 4380,
    ["categoryId"] = "storage:containers",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_crate_cardboard_1",
    ["descriptionKey"] = "Tooltip_MoreBuild_CrateCardboard",
    ["recipeId"] = "MoreBuilds.CrateCardboard",
    ["previewSprite"] = "trashcontainers_01_24",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "smallbox",
        ["health"] = 200,
        ["northSprite"] = "trashcontainers_01_25",
        ["sprite"] = "trashcontainers_01_24",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:crate:cardboard:2",
    ["sortKey"] = 4390,
    ["categoryId"] = "storage:containers",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_crate_cardboard_2",
    ["descriptionKey"] = "Tooltip_MoreBuild_CrateCardboard",
    ["recipeId"] = "MoreBuilds.CrateCardboard",
    ["previewSprite"] = "trashcontainers_01_26",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "smallbox",
        ["health"] = 200,
        ["northSprite"] = "trashcontainers_01_27",
        ["sprite"] = "trashcontainers_01_26",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:crate:cardboard:3",
    ["sortKey"] = 4400,
    ["categoryId"] = "storage:containers",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_crate_cardboard_3",
    ["descriptionKey"] = "Tooltip_MoreBuild_CrateCardboard",
    ["recipeId"] = "MoreBuilds.CrateCardboard",
    ["previewSprite"] = "furniture_storage_02_16",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "cardboardbox",
        ["health"] = 200,
        ["northSprite"] = "furniture_storage_02_17",
        ["sprite"] = "furniture_storage_02_16",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:crate:cardboard:4",
    ["sortKey"] = 4410,
    ["categoryId"] = "storage:containers",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_crate_cardboard_4",
    ["descriptionKey"] = "Tooltip_MoreBuild_CrateCardboard",
    ["recipeId"] = "MoreBuilds.CrateCardboard",
    ["previewSprite"] = "furniture_storage_02_18",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "cardboardbox",
        ["health"] = 200,
        ["northSprite"] = "furniture_storage_02_19",
        ["sprite"] = "furniture_storage_02_18",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:improvised:laundry_cart",
    ["sortKey"] = 4420,
    ["categoryId"] = "storage:containers",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_improvised_laundry_cart",
    ["descriptionKey"] = "Tooltip_MoreBuild_CartMetal",
    ["recipeId"] = "MoreBuilds.CartMetal",
    ["previewSprite"] = "appliances_laundry_01_24",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["canPassThrough"] = true,
        ["containerType"] = "clothingdryerbasic",
        ["health"] = 200,
        ["northSprite"] = "appliances_laundry_01_25",
        ["sprite"] = "appliances_laundry_01_24",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:improvised:pallet_bricks",
    ["sortKey"] = 4430,
    ["categoryId"] = "storage:containers",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_improvised_pallet_bricks",
    ["descriptionKey"] = "Tooltip_MoreBuild_PalletBrick",
    ["recipeId"] = "MoreBuilds.PalletBrick",
    ["previewSprite"] = "construction_01_4",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "fireplace",
        ["health"] = 250,
        ["sprite"] = "construction_01_4",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:improvised:metal_barrel",
    ["sortKey"] = 4440,
    ["categoryId"] = "storage:containers",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_improvised_metal_barrel",
    ["descriptionKey"] = "Tooltip_MoreBuild_BarrelMetal",
    ["recipeId"] = "MoreBuilds.BarrelMetal",
    ["previewSprite"] = "industry_01_22",
    ["placement"] = {
      ["kind"] = "morebuilds:furniture",
      ["data"] = {
        ["health"] = 350,
        ["northSprite"] = "industry_01_23",
        ["sprite"] = "industry_01_22",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wardrobe:fancy_white",
    ["sortKey"] = 5160,
    ["categoryId"] = "storage:cabinets-wardrobes",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wardrobe_fancy_white",
    ["descriptionKey"] = "Tooltip_MoreBuild_WardrobeWood",
    ["recipeId"] = "MoreBuilds.WardrobeWood",
    ["previewSprite"] = "furniture_storage_01_3",
    ["placement"] = {
      ["kind"] = "morebuilds:multi-container",
      ["data"] = {
        ["canBeLockedByPadlock"] = false,
        ["containerType"] = "wardrobe",
        ["eastSprite"] = "furniture_storage_01_7",
        ["eastSprite2"] = "furniture_storage_01_6",
        ["eastTileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = -1,
            ["y"] = 0,
          },
        },
        ["health"] = 250,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "furniture_storage_01_0",
        ["sprite"] = "furniture_storage_01_3",
        ["northSprite2"] = "furniture_storage_01_1",
        ["northTileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = 0,
            ["y"] = -1,
          },
        },
        ["southSprite"] = "furniture_storage_01_4",
        ["southSprite2"] = "furniture_storage_01_5",
        ["southTileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = 0,
            ["y"] = -1,
          },
        },
        ["sprite2"] = "furniture_storage_01_2",
        ["tileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = -1,
            ["y"] = 0,
          },
        },
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wardrobe:fancy_oak",
    ["sortKey"] = 5170,
    ["categoryId"] = "storage:cabinets-wardrobes",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wardrobe_fancy_oak",
    ["descriptionKey"] = "Tooltip_MoreBuild_WardrobeWood",
    ["recipeId"] = "MoreBuilds.WardrobeWood",
    ["previewSprite"] = "furniture_storage_01_19",
    ["placement"] = {
      ["kind"] = "morebuilds:multi-container",
      ["data"] = {
        ["canBeLockedByPadlock"] = false,
        ["containerType"] = "wardrobe",
        ["eastSprite"] = "furniture_storage_01_23",
        ["eastSprite2"] = "furniture_storage_01_22",
        ["eastTileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = -1,
            ["y"] = 0,
          },
        },
        ["health"] = 250,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "furniture_storage_01_16",
        ["sprite"] = "furniture_storage_01_19",
        ["northSprite2"] = "furniture_storage_01_17",
        ["northTileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = 0,
            ["y"] = -1,
          },
        },
        ["southSprite"] = "furniture_storage_01_20",
        ["southSprite2"] = "furniture_storage_01_21",
        ["southTileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = 0,
            ["y"] = -1,
          },
        },
        ["sprite2"] = "furniture_storage_01_18",
        ["tileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = -1,
            ["y"] = 0,
          },
        },
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wardrobe:dark_fancy",
    ["sortKey"] = 5180,
    ["categoryId"] = "storage:cabinets-wardrobes",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wardrobe_dark_fancy",
    ["descriptionKey"] = "Tooltip_MoreBuild_WardrobeWood",
    ["recipeId"] = "MoreBuilds.WardrobeWood",
    ["previewSprite"] = "furniture_storage_01_27",
    ["placement"] = {
      ["kind"] = "morebuilds:multi-container",
      ["data"] = {
        ["canBeLockedByPadlock"] = false,
        ["containerType"] = "wardrobe",
        ["eastSprite"] = "furniture_storage_01_29",
        ["eastSprite2"] = "furniture_storage_01_28",
        ["eastTileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = -1,
            ["y"] = 0,
          },
        },
        ["health"] = 250,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "furniture_storage_01_24",
        ["sprite"] = "furniture_storage_01_27",
        ["northSprite2"] = "furniture_storage_01_25",
        ["northTileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = 0,
            ["y"] = -1,
          },
        },
        ["southSprite"] = "furniture_storage_01_30",
        ["southSprite2"] = "furniture_storage_01_31",
        ["southTileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = 0,
            ["y"] = -1,
          },
        },
        ["sprite2"] = "furniture_storage_01_26",
        ["tileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = -1,
            ["y"] = 0,
          },
        },
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wardrobe:light_wood",
    ["sortKey"] = 5190,
    ["categoryId"] = "storage:cabinets-wardrobes",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wardrobe_light_wood",
    ["descriptionKey"] = "Tooltip_MoreBuild_WardrobeWood",
    ["recipeId"] = "MoreBuilds.WardrobeWood",
    ["previewSprite"] = "furniture_storage_01_59",
    ["placement"] = {
      ["kind"] = "morebuilds:multi-container",
      ["data"] = {
        ["canBeLockedByPadlock"] = false,
        ["containerType"] = "wardrobe",
        ["eastSprite"] = "furniture_storage_01_63",
        ["eastSprite2"] = "furniture_storage_01_62",
        ["eastTileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = -1,
            ["y"] = 0,
          },
        },
        ["health"] = 250,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "furniture_storage_01_56",
        ["sprite"] = "furniture_storage_01_59",
        ["northSprite2"] = "furniture_storage_01_57",
        ["northTileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = 0,
            ["y"] = -1,
          },
        },
        ["southSprite"] = "furniture_storage_01_60",
        ["southSprite2"] = "furniture_storage_01_61",
        ["southTileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = 0,
            ["y"] = -1,
          },
        },
        ["sprite2"] = "furniture_storage_01_58",
        ["tileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = -1,
            ["y"] = 0,
          },
        },
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_shelf:hardwood",
    ["sortKey"] = 5200,
    ["categoryId"] = "storage:shelves-counters",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_shelf_hardwood",
    ["descriptionKey"] = "Tooltip_MoreBuild_WallShelfWood",
    ["recipeId"] = "MoreBuilds.WallShelfWood",
    ["previewSprite"] = "furniture_shelving_01_2",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["canBeLockedByPadlock"] = false,
        ["containerType"] = "shelves",
        ["eastSprite"] = "furniture_shelving_01_3",
        ["health"] = 100,
        ["healthFromCarpentry"] = true,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "furniture_shelving_01_1",
        ["southSprite"] = "furniture_shelving_01_4",
        ["sprite"] = "furniture_shelving_01_2",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_shelf:lightwood",
    ["sortKey"] = 5210,
    ["categoryId"] = "storage:shelves-counters",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_shelf_lightwood",
    ["descriptionKey"] = "Tooltip_MoreBuild_WallShelfWood",
    ["recipeId"] = "MoreBuilds.WallShelfWood",
    ["previewSprite"] = "furniture_shelving_01_32",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["canBeLockedByPadlock"] = false,
        ["containerType"] = "shelves",
        ["eastSprite"] = "furniture_shelving_01_56",
        ["health"] = 100,
        ["healthFromCarpentry"] = true,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "furniture_shelving_01_33",
        ["southSprite"] = "furniture_shelving_01_57",
        ["sprite"] = "furniture_shelving_01_32",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_shelf:darkwood",
    ["sortKey"] = 5220,
    ["categoryId"] = "storage:shelves-counters",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_shelf_darkwood",
    ["descriptionKey"] = "Tooltip_MoreBuild_WallShelfWood",
    ["recipeId"] = "MoreBuilds.WallShelfWood",
    ["previewSprite"] = "furniture_shelving_01_34",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["canBeLockedByPadlock"] = false,
        ["containerType"] = "shelves",
        ["eastSprite"] = "furniture_shelving_01_58",
        ["health"] = 100,
        ["healthFromCarpentry"] = true,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "furniture_shelving_01_35",
        ["southSprite"] = "furniture_shelving_01_59",
        ["sprite"] = "furniture_shelving_01_34",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_shelf:white",
    ["sortKey"] = 5230,
    ["categoryId"] = "storage:shelves-counters",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_shelf_white",
    ["descriptionKey"] = "Tooltip_MoreBuild_WallShelfWood",
    ["recipeId"] = "MoreBuilds.WallShelfWood",
    ["previewSprite"] = "furniture_shelving_01_36",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["canBeLockedByPadlock"] = false,
        ["containerType"] = "shelves",
        ["eastSprite"] = "furniture_shelving_01_60",
        ["health"] = 100,
        ["healthFromCarpentry"] = true,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "furniture_shelving_01_37",
        ["southSprite"] = "furniture_shelving_01_61",
        ["sprite"] = "furniture_shelving_01_36",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:bookshelf:large_wooden",
    ["sortKey"] = 5290,
    ["categoryId"] = "storage:shelves-counters",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_bookshelf_large_wooden",
    ["descriptionKey"] = "Tooltip_MoreBuild_BookshelfWood",
    ["recipeId"] = "MoreBuilds.BookshelfWood",
    ["previewSprite"] = "furniture_shelving_01_10",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["canBeLockedByPadlock"] = false,
        ["containerType"] = "shelves",
        ["eastSprite"] = "furniture_shelving_01_12",
        ["health"] = 250,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "furniture_shelving_01_9",
        ["southSprite"] = "furniture_shelving_01_11",
        ["sprite"] = "furniture_shelving_01_10",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wardrobe:oak",
    ["sortKey"] = 5300,
    ["categoryId"] = "storage:cabinets-wardrobes",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wardrobe_oak",
    ["descriptionKey"] = "Tooltip_MoreBuild_WardrobeWood",
    ["recipeId"] = "MoreBuilds.WardrobeWood",
    ["previewSprite"] = "furniture_storage_01_37",
    ["placement"] = {
      ["kind"] = "morebuilds:multi-container",
      ["data"] = {
        ["canBeLockedByPadlock"] = false,
        ["containerType"] = "wardrobe",
        ["health"] = 250,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "furniture_storage_01_38",
        ["sprite"] = "furniture_storage_01_37",
        ["northSprite2"] = "furniture_storage_01_39",
        ["northTileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = 1,
            ["y"] = 0,
          },
        },
        ["sprite2"] = "furniture_storage_01_36",
        ["tileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = 0,
            ["y"] = 1,
          },
        },
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:shelving:industrial_metal",
    ["sortKey"] = 5930,
    ["categoryId"] = "storage:shelves-counters",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_shelving_industrial_metal",
    ["descriptionKey"] = "Tooltip_MoreBuild_MetalShelf",
    ["recipeId"] = "MoreBuilds.MetalShelf",
    ["previewSprite"] = "furniture_shelving_01_25",
    ["placement"] = {
      ["kind"] = "morebuilds:multi-container",
      ["data"] = {
        ["containerType"] = "metal_shelves",
        ["health"] = 350,
        ["northSprite"] = "furniture_shelving_01_26",
        ["sprite"] = "furniture_shelving_01_25",
        ["northSprite2"] = "furniture_shelving_01_27",
        ["northTileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = 1,
            ["y"] = 0,
          },
        },
        ["sprite2"] = "furniture_shelving_01_24",
        ["tileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = 0,
            ["y"] = 1,
          },
        },
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:container:metal_chest",
    ["sortKey"] = 5980,
    ["categoryId"] = "storage:containers",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_container_metal_chest",
    ["descriptionKey"] = "Tooltip_MoreBuild_MetalChest",
    ["recipeId"] = "MoreBuilds.MetalChest",
    ["previewSprite"] = "furniture_storage_02_29",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["canBeLockedByPadlock"] = false,
        ["containerType"] = "locker",
        ["eastSprite"] = "furniture_storage_02_31",
        ["health"] = 180,
        ["northSprite"] = "furniture_storage_02_28",
        ["southSprite"] = "furniture_storage_02_30",
        ["sprite"] = "furniture_storage_02_29",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:cabinet:china_glass",
    ["sortKey"] = 5990,
    ["categoryId"] = "storage:cabinets-wardrobes",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_cabinet_china_glass",
    ["descriptionKey"] = "Tooltip_MoreBuild_ChinaCabinetWoodGlass",
    ["recipeId"] = "MoreBuilds.ChinaCabinetWoodGlass",
    ["previewSprite"] = "furniture_storage_02_33",
    ["placement"] = {
      ["kind"] = "morebuilds:multi-container",
      ["data"] = {
        ["canBeLockedByPadlock"] = false,
        ["containerType"] = "dishescabinet",
        ["eastSprite"] = "furniture_storage_02_37",
        ["eastSprite2"] = "furniture_storage_02_36",
        ["eastTileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = 0,
            ["y"] = 1,
          },
        },
        ["health"] = 280,
        ["healthFromCarpentry"] = true,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "furniture_storage_02_34",
        ["sprite"] = "furniture_storage_02_33",
        ["northSprite2"] = "furniture_storage_02_35",
        ["northTileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = 1,
            ["y"] = 0,
          },
        },
        ["southSprite"] = "furniture_storage_02_38",
        ["southSprite2"] = "furniture_storage_02_39",
        ["southTileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = 1,
            ["y"] = 0,
          },
        },
        ["sprite2"] = "furniture_storage_02_32",
        ["tileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = 0,
            ["y"] = 1,
          },
        },
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wardrobe:plain_white",
    ["sortKey"] = 6000,
    ["categoryId"] = "storage:cabinets-wardrobes",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wardrobe_plain_white",
    ["descriptionKey"] = "Tooltip_MoreBuild_WardrobeWood",
    ["recipeId"] = "MoreBuilds.WardrobeWood",
    ["previewSprite"] = "furniture_storage_02_41",
    ["placement"] = {
      ["kind"] = "morebuilds:multi-container",
      ["data"] = {
        ["canBeLockedByPadlock"] = false,
        ["containerType"] = "wardrobe",
        ["eastSprite"] = "furniture_storage_02_45",
        ["eastSprite2"] = "furniture_storage_02_44",
        ["eastTileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = 0,
            ["y"] = 1,
          },
        },
        ["health"] = 250,
        ["healthFromCarpentry"] = true,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "furniture_storage_02_42",
        ["sprite"] = "furniture_storage_02_41",
        ["northSprite2"] = "furniture_storage_02_43",
        ["northTileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = 1,
            ["y"] = 0,
          },
        },
        ["southSprite"] = "furniture_storage_02_46",
        ["southSprite2"] = "furniture_storage_02_47",
        ["southTileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = 1,
            ["y"] = 0,
          },
        },
        ["sprite2"] = "furniture_storage_02_40",
        ["tileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = 0,
            ["y"] = 1,
          },
        },
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:shelf:low",
    ["sortKey"] = 6010,
    ["categoryId"] = "storage:shelves-counters",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_shelf_low",
    ["descriptionKey"] = "Tooltip_MoreBuild_LowShelfWood",
    ["recipeId"] = "MoreBuilds.LowShelfWood",
    ["previewSprite"] = "furniture_shelving_01_20",
    ["placement"] = {
      ["kind"] = "morebuilds:multi-container",
      ["data"] = {
        ["canBeLockedByPadlock"] = false,
        ["containerCapacity"] = 20,
        ["containerType"] = "shelves",
        ["eastSprite"] = "furniture_shelving_01_54",
        ["eastSprite2"] = "furniture_shelving_01_53",
        ["eastSprite3"] = "furniture_shelving_01_52",
        ["eastTileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = 0,
            ["y"] = 1,
          },
          {
            ["x"] = 0,
            ["y"] = 2,
          },
        },
        ["health"] = 150,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "furniture_shelving_01_16",
        ["northSprite2"] = "furniture_shelving_01_17",
        ["northSprite3"] = "furniture_shelving_01_18",
        ["northTileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = 1,
            ["y"] = 0,
          },
          {
            ["x"] = 2,
            ["y"] = 0,
          },
        },
        ["southSprite"] = "furniture_shelving_01_50",
        ["southSprite2"] = "furniture_shelving_01_49",
        ["southSprite3"] = "furniture_shelving_01_48",
        ["southTileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = -1,
            ["y"] = 0,
          },
          {
            ["x"] = -2,
            ["y"] = 0,
          },
        },
        ["sprite"] = "furniture_shelving_01_20",
        ["sprite2"] = "furniture_shelving_01_21",
        ["sprite3"] = "furniture_shelving_01_22",
        ["tileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = 0,
            ["y"] = -1,
          },
          {
            ["x"] = 0,
            ["y"] = -2,
          },
        },
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:shelf:low:wide",
    ["sortKey"] = 6060,
    ["categoryId"] = "storage:shelves-counters",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_shelf_low_wide",
    ["descriptionKey"] = "Tooltip_MoreBuild_WideLowShelfWood",
    ["recipeId"] = "MoreBuilds.WideLowShelfWood",
    ["previewSprite"] = "crafted_05_49",
    ["placement"] = {
      ["kind"] = "morebuilds:multi-container",
      ["data"] = {
        ["canBeLockedByPadlock"] = false,
        ["containerType"] = "shelves",
        ["eastSprite"] = "crafted_05_137",
        ["eastSprite2"] = "crafted_05_136",
        ["eastTileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = -1,
            ["y"] = 0,
          },
        },
        ["health"] = 200,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "crafted_05_52",
        ["sprite"] = "crafted_05_49",
        ["northSprite2"] = "crafted_05_53",
        ["northTileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = 0,
            ["y"] = -1,
          },
        },
        ["southSprite"] = "crafted_05_140",
        ["southSprite2"] = "crafted_05_141",
        ["southTileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = 0,
            ["y"] = -1,
          },
        },
        ["sprite2"] = "crafted_05_48",
        ["tileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = -1,
            ["y"] = 0,
          },
        },
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:tool_cabinet:mobile_metal",
    ["sortKey"] = 6080,
    ["categoryId"] = "storage:cabinets-wardrobes",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_tool_cabinet_mobile_metal",
    ["descriptionKey"] = "Tooltip_MoreBuild_MobileMetalToolCabinet",
    ["recipeId"] = "MoreBuilds.MobileMetalToolCabinet",
    ["previewSprite"] = "location_business_machinery_01_33",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["canBeLockedByPadlock"] = false,
        ["containerType"] = "toolcabinet",
        ["eastSprite"] = "location_business_machinery_01_35",
        ["health"] = 250,
        ["northSprite"] = "location_business_machinery_01_32",
        ["southSprite"] = "location_business_machinery_01_34",
        ["sprite"] = "location_business_machinery_01_33",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:medicine_cabinet:wall",
    ["sortKey"] = 6090,
    ["categoryId"] = "storage:cabinets-wardrobes",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_medicine_cabinet_wall",
    ["descriptionKey"] = "Tooltip_MoreBuild_WallMedicineCabinet",
    ["recipeId"] = "MoreBuilds.WallMedicineCabinet",
    ["previewSprite"] = "fixtures_bathroom_01_29",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["blockAllTheSquare"] = false,
        ["canBeLockedByPadlock"] = false,
        ["containerType"] = "medicine",
        ["eastSprite"] = "fixtures_bathroom_01_38",
        ["health"] = 100,
        ["healthFromCarpentry"] = true,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "fixtures_bathroom_01_28",
        ["southSprite"] = "fixtures_bathroom_01_37",
        ["sprite"] = "fixtures_bathroom_01_29",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:dressing_table:wood_mirror",
    ["sortKey"] = 6100,
    ["categoryId"] = "storage:cabinets-wardrobes",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_dressing_table_wood_mirror",
    ["descriptionKey"] = "Tooltip_MoreBuild_DressingTableWoodGlass",
    ["recipeId"] = "MoreBuilds.DressingTableWoodGlass",
    ["previewSprite"] = "furniture_storage_01_42",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["canBeLockedByPadlock"] = false,
        ["containerType"] = "dresser",
        ["eastSprite"] = "furniture_storage_01_40",
        ["health"] = 180,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "furniture_storage_01_43",
        ["southSprite"] = "furniture_storage_01_41",
        ["sprite"] = "furniture_storage_01_42",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_cabinet:hardwood",
    ["sortKey"] = 6290,
    ["categoryId"] = "storage:cabinets-wardrobes",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_cabinet_hardwood",
    ["descriptionKey"] = "Tooltip_MoreBuild_WallCabinetWood",
    ["recipeId"] = "MoreBuilds.WallCabinetWood",
    ["previewSprite"] = "fixtures_counters_01_23",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["blockAllTheSquare"] = false,
        ["canBeLockedByPadlock"] = false,
        ["containerType"] = "counter",
        ["eastSprite"] = "fixtures_counters_01_20",
        ["health"] = 150,
        ["healthFromCarpentry"] = true,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "fixtures_counters_01_22",
        ["southSprite"] = "fixtures_counters_01_21",
        ["sprite"] = "fixtures_counters_01_23",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_cabinet:metal",
    ["sortKey"] = 6300,
    ["categoryId"] = "storage:cabinets-wardrobes",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_cabinet_metal",
    ["descriptionKey"] = "Tooltip_MoreBuild_WallCabinetMetal",
    ["recipeId"] = "MoreBuilds.WallCabinetMetal",
    ["previewSprite"] = "fixtures_counters_01_31",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["blockAllTheSquare"] = false,
        ["canBeLockedByPadlock"] = false,
        ["containerType"] = "counter",
        ["eastSprite"] = "fixtures_counters_01_28",
        ["health"] = 220,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "fixtures_counters_01_30",
        ["southSprite"] = "fixtures_counters_01_29",
        ["sprite"] = "fixtures_counters_01_31",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_shelf:big_corner",
    ["sortKey"] = 7850,
    ["categoryId"] = "storage:shelves-counters",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_shelf_big_corner",
    ["descriptionKey"] = "Tooltip_MoreBuild_WallShelfWood",
    ["recipeId"] = "MoreBuilds.WallShelfWood",
    ["previewSprite"] = "furniture_shelving_01_15",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["blockAllTheSquare"] = false,
        ["canBeLockedByPadlock"] = false,
        ["containerCapacity"] = 30,
        ["containerType"] = "shelves",
        ["eastSprite"] = "furniture_shelving_01_14",
        ["health"] = 150,
        ["healthFromCarpentry"] = true,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "furniture_shelving_01_8",
        ["southSprite"] = "furniture_shelving_01_13",
        ["sprite"] = "furniture_shelving_01_15",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_shelf:hardwood_corner",
    ["sortKey"] = 7880,
    ["categoryId"] = "storage:shelves-counters",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_shelf_hardwood_corner",
    ["descriptionKey"] = "Tooltip_MoreBuild_WallShelfWood",
    ["recipeId"] = "MoreBuilds.WallShelfWood",
    ["previewSprite"] = "furniture_shelving_01_7",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["blockAllTheSquare"] = false,
        ["canBeLockedByPadlock"] = false,
        ["containerCapacity"] = 15,
        ["containerType"] = "shelves",
        ["eastSprite"] = "furniture_shelving_01_5",
        ["health"] = 100,
        ["healthFromCarpentry"] = true,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "furniture_shelving_01_6",
        ["southSprite"] = "furniture_shelving_01_0",
        ["sprite"] = "furniture_shelving_01_7",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wardrobe:red_oak",
    ["sortKey"] = 7890,
    ["categoryId"] = "storage:cabinets-wardrobes",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wardrobe_red_oak",
    ["descriptionKey"] = "Tooltip_MoreBuild_WardrobeWood",
    ["recipeId"] = "MoreBuilds.WardrobeWood",
    ["previewSprite"] = "furniture_storage_02_21",
    ["placement"] = {
      ["kind"] = "morebuilds:multi-container",
      ["data"] = {
        ["canBeLockedByPadlock"] = false,
        ["containerCapacity"] = 25,
        ["containerType"] = "wardrobe",
        ["health"] = 250,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "furniture_storage_02_22",
        ["sprite"] = "furniture_storage_02_21",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:desk:office_two",
    ["sortKey"] = 8050,
    ["categoryId"] = "storage:cabinets-wardrobes",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_desk_office_two",
    ["descriptionKey"] = "Tooltip_MoreBuild_OfficeDesk",
    ["recipeId"] = "MoreBuilds.OfficeDeskWood",
    ["previewSprite"] = "location_business_office_generic_01_90",
    ["placement"] = {
      ["kind"] = "morebuilds:multi-container",
      ["data"] = {
        ["canBeLockedByPadlock"] = false,
        ["containerCapacity"] = 20,
        ["containerType"] = "desk",
        ["eastSprite"] = "location_business_office_generic_01_101",
        ["health"] = 250,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "location_business_office_generic_01_96",
        ["southSprite"] = "location_business_office_generic_01_91",
        ["sprite"] = "location_business_office_generic_01_90",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:medicine_cabinet:first_aid",
    ["sortKey"] = 8060,
    ["categoryId"] = "storage:cabinets-wardrobes",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_medicine_cabinet_first_aid",
    ["descriptionKey"] = "Tooltip_MoreBuild_WallMedicineCabinet",
    ["recipeId"] = "MoreBuilds.WallMedicineCabinet",
    ["previewSprite"] = "location_community_medical_01_89",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["blockAllTheSquare"] = false,
        ["canBeLockedByPadlock"] = false,
        ["containerCapacity"] = 10,
        ["containerType"] = "medicine",
        ["eastSprite"] = "location_community_medical_01_91",
        ["health"] = 100,
        ["healthFromCarpentry"] = true,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "location_community_medical_01_90",
        ["southSprite"] = "location_community_medical_01_88",
        ["sprite"] = "location_community_medical_01_89",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:desk:red_oak_office:3",
    ["sortKey"] = 8061,
    ["categoryId"] = "storage:cabinets-wardrobes",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_desk_red_oak_office_3",
    ["descriptionKey"] = "Tooltip_MoreBuild_LargeOfficeDesk",
    ["recipeId"] = "MoreBuilds.LargeOfficeDeskWood",
    ["previewSprite"] = "location_business_office_generic_01_171",
    ["placement"] = {
      ["kind"] = "morebuilds:multi-container",
      ["data"] = {
        ["canBeLockedByPadlock"] = false,
        ["containerCapacity"] = 20,
        ["containerType"] = "desk",
        ["eastSprite"] = "location_business_office_generic_01_182",
        ["health"] = 350,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "location_business_office_generic_01_198",
        ["southSprite"] = "location_business_office_generic_01_184",
        ["sprite"] = "location_business_office_generic_01_171",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:desk:red_oak_office:4",
    ["sortKey"] = 8062,
    ["categoryId"] = "storage:cabinets-wardrobes",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_desk_red_oak_office_4",
    ["descriptionKey"] = "Tooltip_MoreBuild_LargeOfficeDesk",
    ["recipeId"] = "MoreBuilds.LargeOfficeDeskWood",
    ["previewSprite"] = "location_business_office_generic_01_203",
    ["placement"] = {
      ["kind"] = "morebuilds:multi-container",
      ["data"] = {
        ["canBeLockedByPadlock"] = false,
        ["containerCapacity"] = 20,
        ["containerType"] = "desk",
        ["eastSprite"] = "location_business_office_generic_01_214",
        ["health"] = 350,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "location_business_office_generic_01_230",
        ["southSprite"] = "location_business_office_generic_01_216",
        ["sprite"] = "location_business_office_generic_01_203",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:bar_wall:wood:left",
    ["sortKey"] = 8063,
    ["categoryId"] = "storage:shelves-counters",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_bar_wall_wood_left",
    ["descriptionKey"] = "Tooltip_MoreBuild_BarWall",
    ["recipeId"] = "MoreBuilds.CounterWood",
    ["previewSprite"] = "location_restaurant_bar_01_37",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["canBeLockedByPadlock"] = false,
        ["containerCapacity"] = 25,
        ["containerType"] = "shelves",
        ["eastSprite"] = "location_restaurant_bar_01_115",
        ["health"] = 250,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "location_restaurant_bar_01_112",
        ["southSprite"] = "location_restaurant_bar_01_29",
        ["sprite"] = "location_restaurant_bar_01_37",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:bar_wall:wood:center",
    ["sortKey"] = 8064,
    ["categoryId"] = "storage:shelves-counters",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_bar_wall_wood_center",
    ["descriptionKey"] = "Tooltip_MoreBuild_BarWall",
    ["recipeId"] = "MoreBuilds.CounterWood",
    ["previewSprite"] = "location_restaurant_bar_01_38",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["canBeLockedByPadlock"] = false,
        ["containerCapacity"] = 25,
        ["containerType"] = "shelves",
        ["eastSprite"] = "location_restaurant_bar_01_116",
        ["health"] = 250,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "location_restaurant_bar_01_113",
        ["southSprite"] = "location_restaurant_bar_01_30",
        ["sprite"] = "location_restaurant_bar_01_38",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:bar_wall:wood:right",
    ["sortKey"] = 8065,
    ["categoryId"] = "storage:shelves-counters",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_bar_wall_wood_right",
    ["descriptionKey"] = "Tooltip_MoreBuild_BarWall",
    ["recipeId"] = "MoreBuilds.CounterWood",
    ["previewSprite"] = "location_restaurant_bar_01_39",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["canBeLockedByPadlock"] = false,
        ["containerCapacity"] = 25,
        ["containerType"] = "shelves",
        ["eastSprite"] = "location_restaurant_bar_01_117",
        ["health"] = 250,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "location_restaurant_bar_01_114",
        ["southSprite"] = "location_restaurant_bar_01_31",
        ["sprite"] = "location_restaurant_bar_01_39",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:bar_wall:dark:left",
    ["sortKey"] = 8066,
    ["categoryId"] = "storage:shelves-counters",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_bar_wall_dark_left",
    ["descriptionKey"] = "Tooltip_MoreBuild_BarWall",
    ["recipeId"] = "MoreBuilds.CounterWood",
    ["previewSprite"] = "location_restaurant_bar_01_72",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["canBeLockedByPadlock"] = false,
        ["containerCapacity"] = 25,
        ["containerType"] = "shelves",
        ["eastSprite"] = "location_restaurant_bar_01_123",
        ["health"] = 250,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "location_restaurant_bar_01_120",
        ["southSprite"] = "location_restaurant_bar_01_64",
        ["sprite"] = "location_restaurant_bar_01_72",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:bar_wall:dark:center",
    ["sortKey"] = 8067,
    ["categoryId"] = "storage:shelves-counters",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_bar_wall_dark_center",
    ["descriptionKey"] = "Tooltip_MoreBuild_BarWall",
    ["recipeId"] = "MoreBuilds.CounterWood",
    ["previewSprite"] = "location_restaurant_bar_01_73",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["canBeLockedByPadlock"] = false,
        ["containerCapacity"] = 25,
        ["containerType"] = "shelves",
        ["eastSprite"] = "location_restaurant_bar_01_124",
        ["health"] = 250,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "location_restaurant_bar_01_121",
        ["southSprite"] = "location_restaurant_bar_01_65",
        ["sprite"] = "location_restaurant_bar_01_73",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:bar_wall:dark:right",
    ["sortKey"] = 8068,
    ["categoryId"] = "storage:shelves-counters",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_bar_wall_dark_right",
    ["descriptionKey"] = "Tooltip_MoreBuild_BarWall",
    ["recipeId"] = "MoreBuilds.CounterWood",
    ["previewSprite"] = "location_restaurant_bar_01_74",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["canBeLockedByPadlock"] = false,
        ["containerCapacity"] = 25,
        ["containerType"] = "shelves",
        ["eastSprite"] = "location_restaurant_bar_01_125",
        ["health"] = 250,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "location_restaurant_bar_01_122",
        ["southSprite"] = "location_restaurant_bar_01_66",
        ["sprite"] = "location_restaurant_bar_01_74",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:desk:medical",
    ["sortKey"] = 8069,
    ["categoryId"] = "storage:cabinets-wardrobes",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_desk_medical",
    ["descriptionKey"] = "Tooltip_MoreBuild_OfficeDesk",
    ["recipeId"] = "MoreBuilds.OfficeDeskWood",
    ["previewSprite"] = "location_community_medical_01_106",
    ["placement"] = {
      ["kind"] = "morebuilds:multi-container",
      ["data"] = {
        ["canBeLockedByPadlock"] = false,
        ["containerCapacity"] = 20,
        ["containerType"] = "desk",
        ["eastSprite"] = "location_community_medical_01_98",
        ["health"] = 250,
        ["healthFromCarpentry"] = true,
        ["northSprite"] = "location_community_medical_01_99",
        ["southSprite"] = "location_community_medical_01_107",
        ["sprite"] = "location_community_medical_01_106",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:dumpster:blue",
    ["sortKey"] = 13781,
    ["categoryId"] = "storage:containers",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_dumpster_blue",
    ["descriptionKey"] = "Tooltip_MoreBuild_MetalDumpster",
    ["recipeId"] = "MoreBuilds.DumpsterMetal",
    ["previewSprite"] = "trashcontainers_01_9",
    ["placement"] = {
      ["kind"] = "morebuilds:multi-container",
      ["data"] = {
        ["canBeLockedByPadlock"] = false,
        ["containerCapacity"] = 30,
        ["containerType"] = "dumpster",
        ["eastSprite"] = "trashcontainers_01_29",
        ["health"] = 350,
        ["northSprite"] = "trashcontainers_01_30",
        ["southSprite"] = "trashcontainers_01_10",
        ["sprite"] = "trashcontainers_01_9",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:dumpster:orange",
    ["sortKey"] = 13783,
    ["categoryId"] = "storage:containers",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_dumpster_orange",
    ["descriptionKey"] = "Tooltip_MoreBuild_MetalDumpster",
    ["recipeId"] = "MoreBuilds.DumpsterMetal",
    ["previewSprite"] = "trashcontainers_01_13",
    ["placement"] = {
      ["kind"] = "morebuilds:multi-container",
      ["data"] = {
        ["canBeLockedByPadlock"] = false,
        ["containerCapacity"] = 30,
        ["containerType"] = "dumpster",
        ["health"] = 350,
        ["northSprite"] = "trashcontainers_01_14",
        ["sprite"] = "trashcontainers_01_13",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
}

for _, definition in ipairs(definitions) do
  definition.sortKey = definition.sortKey + 110000
end

return definitions
