local definitions = {
  {
    ["id"] = "morebuilds:improvised:recycling_bin",
    ["sortKey"] = 4460,
    ["categoryId"] = "utilities:water-sanitation",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_improvised_recycling_bin",
    ["descriptionKey"] = "Tooltip_MoreBuild_TrashMetal",
    ["recipeId"] = "MoreBuilds.TrashPlastic",
    ["previewSprite"] = "trashcontainers_01_0",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "bin",
        ["eastSprite"] = "trashcontainers_01_2",
        ["health"] = 200,
        ["northSprite"] = "trashcontainers_01_1",
        ["southSprite"] = "trashcontainers_01_3",
        ["sprite"] = "trashcontainers_01_0",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:trash:stone:1",
    ["sortKey"] = 4470,
    ["categoryId"] = "utilities:water-sanitation",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_trash_stone_1",
    ["descriptionKey"] = "Tooltip_MoreBuild_TrashStone",
    ["recipeId"] = "MoreBuilds.TrashStone",
    ["previewSprite"] = "location_shop_mall_01_44",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "bin",
        ["health"] = 250,
        ["sprite"] = "location_shop_mall_01_44",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:trash:wood:1",
    ["sortKey"] = 4480,
    ["categoryId"] = "utilities:water-sanitation",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_trash_wood_1",
    ["descriptionKey"] = "Tooltip_MoreBuild_RecyclingWood",
    ["recipeId"] = "MoreBuilds.TrashPlastic",
    ["previewSprite"] = "location_restaurant_pizzawhirled_01_17",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "bin",
        ["health"] = 200,
        ["northSprite"] = "location_restaurant_pizzawhirled_01_18",
        ["sprite"] = "location_restaurant_pizzawhirled_01_17",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:survival:water_pump",
    ["sortKey"] = 5105,
    ["categoryId"] = "utilities:water-sanitation",
    ["nameKey"] = "ContextMenu_MoreBuild_Water_Pump",
    ["descriptionKey"] = "Tooltip_MoreBuild_WaterPump",
    ["recipeId"] = "MoreBuilds.WaterPump",
    ["previewSprite"] = "morebuilds_water_01_1",
    ["placement"] = {
      ["kind"] = "morebuilds:water-pump",
      ["data"] = {
        ["eastSprite"] = "morebuilds_water_01_3",
        ["health"] = 150,
        ["northSprite"] = "morebuilds_water_01_2",
        ["southSprite"] = "morebuilds_water_01_4",
        ["sprite"] = "morebuilds_water_01_1",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:trash:wood:2",
    ["sortKey"] = 4490,
    ["categoryId"] = "utilities:water-sanitation",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_trash_wood_2",
    ["descriptionKey"] = "Tooltip_MoreBuild_RecyclingWood",
    ["recipeId"] = "MoreBuilds.TrashPlastic",
    ["previewSprite"] = "location_restaurant_spiffos_01_30",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "bin",
        ["health"] = 200,
        ["northSprite"] = "location_restaurant_spiffos_01_31",
        ["sprite"] = "location_restaurant_spiffos_01_30",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:trash:wood:3",
    ["sortKey"] = 4500,
    ["categoryId"] = "utilities:water-sanitation",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_trash_wood_3",
    ["descriptionKey"] = "Tooltip_MoreBuild_RecyclingWood",
    ["recipeId"] = "MoreBuilds.TrashPlastic",
    ["previewSprite"] = "location_shop_fossoil_01_32",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "bin",
        ["health"] = 200,
        ["northSprite"] = "location_shop_fossoil_01_33",
        ["sprite"] = "location_shop_fossoil_01_32",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:trash:wood:4",
    ["sortKey"] = 4510,
    ["categoryId"] = "utilities:water-sanitation",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_trash_wood_4",
    ["descriptionKey"] = "Tooltip_MoreBuild_RecyclingWood",
    ["recipeId"] = "MoreBuilds.TrashStonePlastic",
    ["previewSprite"] = "trashcontainers_01_18",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "bin",
        ["health"] = 200,
        ["northSprite"] = "trashcontainers_01_19",
        ["sprite"] = "trashcontainers_01_18",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:trash:wood:5",
    ["sortKey"] = 4520,
    ["categoryId"] = "utilities:water-sanitation",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_trash_wood_5",
    ["descriptionKey"] = "Tooltip_MoreBuild_RecyclingWood",
    ["recipeId"] = "MoreBuilds.TrashPlastic",
    ["previewSprite"] = "trashcontainers_01_20",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "bin",
        ["health"] = 200,
        ["sprite"] = "trashcontainers_01_20",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:trash:metal:1",
    ["sortKey"] = 4530,
    ["categoryId"] = "utilities:water-sanitation",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_trash_metal_1",
    ["descriptionKey"] = "Tooltip_MoreBuild_TrashMetal",
    ["recipeId"] = "MoreBuilds.TrashMetal",
    ["previewSprite"] = "trashcontainers_01_16",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "bin",
        ["health"] = 350,
        ["sprite"] = "trashcontainers_01_16",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:trash:metal:2",
    ["sortKey"] = 4540,
    ["categoryId"] = "utilities:water-sanitation",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_trash_metal_2",
    ["descriptionKey"] = "Tooltip_MoreBuild_TrashMetal",
    ["recipeId"] = "MoreBuilds.TrashMetal",
    ["previewSprite"] = "trashcontainers_01_17",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "bin",
        ["health"] = 350,
        ["sprite"] = "trashcontainers_01_17",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:light_pole:1",
    ["sortKey"] = 5060,
    ["categoryId"] = "utilities:lighting",
    ["nameKey"] = "ContextMenu_MoreBuild_Light_Pole",
    ["descriptionKey"] = "Tooltip_MoreBuild_LightPole",
    ["recipeId"] = "MoreBuilds.LightPole",
    ["previewSprite"] = "lighting_outdoor_01_0",
    ["placement"] = {
      ["kind"] = "morebuilds:light",
      ["data"] = {
        ["sprite"] = "lighting_outdoor_01_0",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:light_pole:2",
    ["sortKey"] = 5070,
    ["categoryId"] = "utilities:lighting",
    ["nameKey"] = "ContextMenu_MoreBuild_Light_Pole",
    ["descriptionKey"] = "Tooltip_MoreBuild_LightPole",
    ["recipeId"] = "MoreBuilds.LightPole",
    ["previewSprite"] = "lighting_outdoor_01_1",
    ["placement"] = {
      ["kind"] = "morebuilds:light",
      ["data"] = {
        ["sprite"] = "lighting_outdoor_01_1",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:light_pole:3",
    ["sortKey"] = 5080,
    ["categoryId"] = "utilities:lighting",
    ["nameKey"] = "ContextMenu_MoreBuild_Light_Pole",
    ["descriptionKey"] = "Tooltip_MoreBuild_LightPole",
    ["recipeId"] = "MoreBuilds.LightPole",
    ["previewSprite"] = "lighting_outdoor_01_2",
    ["placement"] = {
      ["kind"] = "morebuilds:light",
      ["data"] = {
        ["sprite"] = "lighting_outdoor_01_2",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:outdoor_light:emergency_lamp",
    ["sortKey"] = 5090,
    ["categoryId"] = "utilities:lighting",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_outdoor_light_emergency_lamp",
    ["descriptionKey"] = "Tooltip_MoreBuild_OutdoorLight",
    ["recipeId"] = "MoreBuilds.OutdoorLight",
    ["previewSprite"] = "lighting_outdoor_01_49",
    ["placement"] = {
      ["kind"] = "morebuilds:light",
      ["data"] = {
        ["eastSprite"] = "lighting_outdoor_01_51",
        ["northSprite"] = "lighting_outdoor_01_48",
        ["southSprite"] = "lighting_outdoor_01_50",
        ["sprite"] = "lighting_outdoor_01_49",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:survival:water_well",
    ["sortKey"] = 5100,
    ["categoryId"] = "utilities:water-sanitation",
    ["nameKey"] = "ContextMenu_MoreBuild_Water_Well",
    ["descriptionKey"] = "Tooltip_MoreBuild_WaterWell",
    ["recipeId"] = "MoreBuilds.WaterWell",
    ["previewSprite"] = "morebuilds_water_01_0",
    ["placement"] = {
      ["kind"] = "morebuilds:water-well",
      ["data"] = {
        ["health"] = 200,
        ["healthFromCarpentry"] = true,
        ["sprite"] = "morebuilds_water_01_0",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:survival:mini_fridge",
    ["sortKey"] = 5110,
    ["categoryId"] = "utilities:appliances",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_survival_mini_fridge",
    ["descriptionKey"] = "Tooltip_MoreBuild_MiniFridge",
    ["recipeId"] = "MoreBuilds.MiniFridge",
    ["previewSprite"] = "appliances_refrigeration_01_24",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "fridge",
        ["eastSprite"] = "appliances_refrigeration_01_26",
        ["health"] = 350,
        ["northSprite"] = "appliances_refrigeration_01_25",
        ["southSprite"] = "appliances_refrigeration_01_27",
        ["sprite"] = "appliances_refrigeration_01_24",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:survival:barbecue",
    ["sortKey"] = 5120,
    ["categoryId"] = "utilities:appliances",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_survival_barbecue",
    ["descriptionKey"] = "Tooltip_MoreBuild_Barbecue",
    ["recipeId"] = "MoreBuilds.Barbecue",
    ["previewSprite"] = "appliances_cooking_01_35",
    ["placement"] = {
      ["kind"] = "morebuilds:barbecue",
      ["data"] = {
        ["sprite"] = "appliances_cooking_01_35",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:survival:fuel_generator",
    ["sortKey"] = 5130,
    ["categoryId"] = "utilities:appliances",
    ["nameKey"] = "ContextMenu_MoreBuild_Generator_Lectromax",
    ["descriptionKey"] = "Tooltip_MoreBuild_Generator",
    ["recipeId"] = "MoreBuilds.Generator",
    ["previewSprite"] = "appliances_misc_01_0",
    ["placement"] = {
      ["kind"] = "morebuilds:generator",
      ["data"] = {
        ["eastSprite"] = "appliances_misc_01_2",
        ["northSprite"] = "appliances_misc_01_1",
        ["southSprite"] = "appliances_misc_01_3",
        ["sprite"] = "appliances_misc_01_0",
        ["generatorItem"] = "Base.Generator",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:survival:stove",
    ["sortKey"] = 5140,
    ["categoryId"] = "utilities:appliances",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_survival_stove",
    ["descriptionKey"] = "Tooltip_MoreBuild_StoveMetal",
    ["recipeId"] = "MoreBuilds.StoveMetal",
    ["previewSprite"] = "appliances_cooking_01_16",
    ["placement"] = {
      ["kind"] = "morebuilds:fireplace",
      ["data"] = {
        ["eastSprite"] = "appliances_cooking_01_19",
        ["eastWallFacing"] = "W",
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "appliances_cooking_01_16",
        ["northWallFacing"] = "E",
        ["southSprite"] = "appliances_cooking_01_18",
        ["southWallFacing"] = "N",
        ["sprite"] = "appliances_cooking_01_17",
        ["wallFacing"] = "S",
        ["isMoveable"] = true,
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:survival:fireplace",
    ["sortKey"] = 5150,
    ["categoryId"] = "utilities:appliances",
    ["nameKey"] = "ContextMenu_MoreBuild_Fireplace",
    ["descriptionKey"] = "Tooltip_MoreBuild_Fireplace",
    ["recipeId"] = "MoreBuilds.Fireplace",
    ["previewSprite"] = "fixtures_fireplaces_01_0",
    ["placement"] = {
      ["kind"] = "morebuilds:fireplace",
      ["data"] = {
        ["eastSprite"] = "fixtures_fireplaces_01_2",
        ["eastWallFacing"] = "W",
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "fixtures_fireplaces_01_3",
        ["northWallFacing"] = "E",
        ["southSprite"] = "fixtures_fireplaces_01_1",
        ["southWallFacing"] = "N",
        ["sprite"] = "fixtures_fireplaces_01_0",
        ["wallFacing"] = "S",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:table_lamp:gray",
    ["sortKey"] = 5370,
    ["categoryId"] = "utilities:lighting",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_table_lamp_gray",
    ["descriptionKey"] = "Tooltip_MoreBuild_TableLamp",
    ["recipeId"] = "MoreBuilds.TableLamp",
    ["previewSprite"] = "lighting_indoor_02_1",
    ["placement"] = {
      ["kind"] = "morebuilds:table-light",
      ["data"] = {
        ["eastSprite"] = "lighting_indoor_02_3",
        ["northSprite"] = "lighting_indoor_02_2",
        ["southSprite"] = "lighting_indoor_02_0",
        ["sprite"] = "lighting_indoor_02_1",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:table_lamp:red",
    ["sortKey"] = 5380,
    ["categoryId"] = "utilities:lighting",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_table_lamp_red",
    ["descriptionKey"] = "Tooltip_MoreBuild_TableLamp",
    ["recipeId"] = "MoreBuilds.TableLamp",
    ["previewSprite"] = "lighting_indoor_02_5",
    ["placement"] = {
      ["kind"] = "morebuilds:table-light",
      ["data"] = {
        ["eastSprite"] = "lighting_indoor_02_7",
        ["northSprite"] = "lighting_indoor_02_6",
        ["southSprite"] = "lighting_indoor_02_4",
        ["sprite"] = "lighting_indoor_02_5",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:table_lamp:black",
    ["sortKey"] = 5390,
    ["categoryId"] = "utilities:lighting",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_table_lamp_black",
    ["descriptionKey"] = "Tooltip_MoreBuild_TableLamp",
    ["recipeId"] = "MoreBuilds.TableLamp",
    ["previewSprite"] = "lighting_indoor_02_9",
    ["placement"] = {
      ["kind"] = "morebuilds:table-light",
      ["data"] = {
        ["eastSprite"] = "lighting_indoor_02_11",
        ["northSprite"] = "lighting_indoor_02_10",
        ["southSprite"] = "lighting_indoor_02_8",
        ["sprite"] = "lighting_indoor_02_9",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:table_lamp:yellow",
    ["sortKey"] = 5400,
    ["categoryId"] = "utilities:lighting",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_table_lamp_yellow",
    ["descriptionKey"] = "Tooltip_MoreBuild_TableLamp",
    ["recipeId"] = "MoreBuilds.TableLamp",
    ["previewSprite"] = "lighting_indoor_02_13",
    ["placement"] = {
      ["kind"] = "morebuilds:table-light",
      ["data"] = {
        ["eastSprite"] = "lighting_indoor_02_15",
        ["northSprite"] = "lighting_indoor_02_14",
        ["southSprite"] = "lighting_indoor_02_12",
        ["sprite"] = "lighting_indoor_02_13",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:table_lamp:small_red",
    ["sortKey"] = 5410,
    ["categoryId"] = "utilities:lighting",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_table_lamp_small_red",
    ["descriptionKey"] = "Tooltip_MoreBuild_TableLamp",
    ["recipeId"] = "MoreBuilds.TableLamp",
    ["previewSprite"] = "lighting_indoor_02_18",
    ["placement"] = {
      ["kind"] = "morebuilds:table-light",
      ["data"] = {
        ["eastSprite"] = "lighting_indoor_02_17",
        ["northSprite"] = "lighting_indoor_02_19",
        ["southSprite"] = "lighting_indoor_02_16",
        ["sprite"] = "lighting_indoor_02_18",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:table_lamp:small_blue",
    ["sortKey"] = 5420,
    ["categoryId"] = "utilities:lighting",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_table_lamp_small_blue",
    ["descriptionKey"] = "Tooltip_MoreBuild_TableLamp",
    ["recipeId"] = "MoreBuilds.TableLamp",
    ["previewSprite"] = "lighting_indoor_02_22",
    ["placement"] = {
      ["kind"] = "morebuilds:table-light",
      ["data"] = {
        ["eastSprite"] = "lighting_indoor_02_21",
        ["northSprite"] = "lighting_indoor_02_23",
        ["southSprite"] = "lighting_indoor_02_20",
        ["sprite"] = "lighting_indoor_02_22",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:table_lamp:blue",
    ["sortKey"] = 5430,
    ["categoryId"] = "utilities:lighting",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_table_lamp_blue",
    ["descriptionKey"] = "Tooltip_MoreBuild_TableLamp",
    ["recipeId"] = "MoreBuilds.TableLamp",
    ["previewSprite"] = "lighting_indoor_02_25",
    ["placement"] = {
      ["kind"] = "morebuilds:table-light",
      ["data"] = {
        ["eastSprite"] = "lighting_indoor_02_27",
        ["northSprite"] = "lighting_indoor_02_26",
        ["southSprite"] = "lighting_indoor_02_24",
        ["sprite"] = "lighting_indoor_02_25",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:table_lamp:small_white",
    ["sortKey"] = 5440,
    ["categoryId"] = "utilities:lighting",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_table_lamp_small_white",
    ["descriptionKey"] = "Tooltip_MoreBuild_TableLamp",
    ["recipeId"] = "MoreBuilds.TableLamp",
    ["previewSprite"] = "lighting_indoor_02_30",
    ["placement"] = {
      ["kind"] = "morebuilds:table-light",
      ["data"] = {
        ["eastSprite"] = "lighting_indoor_02_29",
        ["northSprite"] = "lighting_indoor_02_31",
        ["southSprite"] = "lighting_indoor_02_28",
        ["sprite"] = "lighting_indoor_02_30",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:table_lamp:green_vintage",
    ["sortKey"] = 5450,
    ["categoryId"] = "utilities:lighting",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_table_lamp_green_vintage",
    ["descriptionKey"] = "Tooltip_MoreBuild_TableLamp",
    ["recipeId"] = "MoreBuilds.TableLamp",
    ["previewSprite"] = "lighting_indoor_02_32",
    ["placement"] = {
      ["kind"] = "morebuilds:table-light",
      ["data"] = {
        ["eastSprite"] = "lighting_indoor_02_33",
        ["northSprite"] = "lighting_indoor_02_34",
        ["southSprite"] = "lighting_indoor_02_35",
        ["sprite"] = "lighting_indoor_02_32",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:table_lamp:blue_vintage",
    ["sortKey"] = 5460,
    ["categoryId"] = "utilities:lighting",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_table_lamp_blue_vintage",
    ["descriptionKey"] = "Tooltip_MoreBuild_TableLamp",
    ["recipeId"] = "MoreBuilds.TableLamp",
    ["previewSprite"] = "lighting_indoor_02_36",
    ["placement"] = {
      ["kind"] = "morebuilds:table-light",
      ["data"] = {
        ["eastSprite"] = "lighting_indoor_02_37",
        ["northSprite"] = "lighting_indoor_02_38",
        ["southSprite"] = "lighting_indoor_02_39",
        ["sprite"] = "lighting_indoor_02_36",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:table_lamp:globe",
    ["sortKey"] = 5470,
    ["categoryId"] = "utilities:lighting",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_table_lamp_globe",
    ["descriptionKey"] = "Tooltip_MoreBuild_TableLamp",
    ["recipeId"] = "MoreBuilds.TableLamp",
    ["previewSprite"] = "lighting_indoor_02_41",
    ["placement"] = {
      ["kind"] = "morebuilds:table-light",
      ["data"] = {
        ["eastSprite"] = "lighting_indoor_02_43",
        ["northSprite"] = "lighting_indoor_02_42",
        ["southSprite"] = "lighting_indoor_02_40",
        ["sprite"] = "lighting_indoor_02_41",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:table_lamp:floral_vintage",
    ["sortKey"] = 5480,
    ["categoryId"] = "utilities:lighting",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_table_lamp_floral_vintage",
    ["descriptionKey"] = "Tooltip_MoreBuild_TableLamp",
    ["recipeId"] = "MoreBuilds.TableLamp",
    ["previewSprite"] = "lighting_indoor_02_57",
    ["placement"] = {
      ["kind"] = "morebuilds:table-light",
      ["data"] = {
        ["eastSprite"] = "lighting_indoor_02_59",
        ["northSprite"] = "lighting_indoor_02_58",
        ["southSprite"] = "lighting_indoor_02_56",
        ["sprite"] = "lighting_indoor_02_57",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:table_lamp:red_gold",
    ["sortKey"] = 5490,
    ["categoryId"] = "utilities:lighting",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_table_lamp_red_gold",
    ["descriptionKey"] = "Tooltip_MoreBuild_TableLamp",
    ["recipeId"] = "MoreBuilds.TableLamp",
    ["previewSprite"] = "lighting_indoor_02_65",
    ["placement"] = {
      ["kind"] = "morebuilds:table-light",
      ["data"] = {
        ["eastSprite"] = "lighting_indoor_02_67",
        ["northSprite"] = "lighting_indoor_02_66",
        ["southSprite"] = "lighting_indoor_02_64",
        ["sprite"] = "lighting_indoor_02_65",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:table_lamp:blue_gold",
    ["sortKey"] = 5500,
    ["categoryId"] = "utilities:lighting",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_table_lamp_blue_gold",
    ["descriptionKey"] = "Tooltip_MoreBuild_TableLamp",
    ["recipeId"] = "MoreBuilds.TableLamp",
    ["previewSprite"] = "lighting_indoor_02_69",
    ["placement"] = {
      ["kind"] = "morebuilds:table-light",
      ["data"] = {
        ["eastSprite"] = "lighting_indoor_02_71",
        ["northSprite"] = "lighting_indoor_02_70",
        ["southSprite"] = "lighting_indoor_02_68",
        ["sprite"] = "lighting_indoor_02_69",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:table_lamp:striped",
    ["sortKey"] = 6110,
    ["categoryId"] = "utilities:lighting",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_table_lamp_striped",
    ["descriptionKey"] = "Tooltip_MoreBuild_TableLamp",
    ["recipeId"] = "MoreBuilds.TableLamp",
    ["previewSprite"] = "lighting_indoor_01_8",
    ["placement"] = {
      ["kind"] = "morebuilds:table-light",
      ["data"] = {
        ["eastSprite"] = "lighting_indoor_01_40",
        ["northSprite"] = "lighting_indoor_01_32",
        ["southSprite"] = "lighting_indoor_01_48",
        ["sprite"] = "lighting_indoor_01_8",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:table_lamp:classic_gray",
    ["sortKey"] = 6120,
    ["categoryId"] = "utilities:lighting",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_table_lamp_classic_gray",
    ["descriptionKey"] = "Tooltip_MoreBuild_TableLamp",
    ["recipeId"] = "MoreBuilds.TableLamp",
    ["previewSprite"] = "lighting_indoor_01_9",
    ["placement"] = {
      ["kind"] = "morebuilds:table-light",
      ["data"] = {
        ["eastSprite"] = "lighting_indoor_01_41",
        ["northSprite"] = "lighting_indoor_01_33",
        ["southSprite"] = "lighting_indoor_01_49",
        ["sprite"] = "lighting_indoor_01_9",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:table_lamp:classic_red",
    ["sortKey"] = 6130,
    ["categoryId"] = "utilities:lighting",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_table_lamp_classic_red",
    ["descriptionKey"] = "Tooltip_MoreBuild_TableLamp",
    ["recipeId"] = "MoreBuilds.TableLamp",
    ["previewSprite"] = "lighting_indoor_01_10",
    ["placement"] = {
      ["kind"] = "morebuilds:table-light",
      ["data"] = {
        ["eastSprite"] = "lighting_indoor_01_42",
        ["northSprite"] = "lighting_indoor_01_34",
        ["southSprite"] = "lighting_indoor_01_50",
        ["sprite"] = "lighting_indoor_01_10",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:table_lamp:tall_gray",
    ["sortKey"] = 6140,
    ["categoryId"] = "utilities:lighting",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_table_lamp_tall_gray",
    ["descriptionKey"] = "Tooltip_MoreBuild_TableLamp",
    ["recipeId"] = "MoreBuilds.TableLamp",
    ["previewSprite"] = "lighting_indoor_01_11",
    ["placement"] = {
      ["kind"] = "morebuilds:table-light",
      ["data"] = {
        ["eastSprite"] = "lighting_indoor_01_43",
        ["northSprite"] = "lighting_indoor_01_35",
        ["southSprite"] = "lighting_indoor_01_51",
        ["sprite"] = "lighting_indoor_01_11",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:table_lamp:classic_blue",
    ["sortKey"] = 6150,
    ["categoryId"] = "utilities:lighting",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_table_lamp_blue",
    ["descriptionKey"] = "Tooltip_MoreBuild_TableLamp",
    ["recipeId"] = "MoreBuilds.TableLamp",
    ["previewSprite"] = "lighting_indoor_01_12",
    ["placement"] = {
      ["kind"] = "morebuilds:table-light",
      ["data"] = {
        ["eastSprite"] = "lighting_indoor_01_44",
        ["northSprite"] = "lighting_indoor_01_36",
        ["southSprite"] = "lighting_indoor_01_52",
        ["sprite"] = "lighting_indoor_01_12",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:table_lamp:classic_white",
    ["sortKey"] = 6160,
    ["categoryId"] = "utilities:lighting",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_table_lamp_classic_white",
    ["descriptionKey"] = "Tooltip_MoreBuild_TableLamp",
    ["recipeId"] = "MoreBuilds.TableLamp",
    ["previewSprite"] = "lighting_indoor_01_13",
    ["placement"] = {
      ["kind"] = "morebuilds:table-light",
      ["data"] = {
        ["eastSprite"] = "lighting_indoor_01_45",
        ["northSprite"] = "lighting_indoor_01_37",
        ["southSprite"] = "lighting_indoor_01_53",
        ["sprite"] = "lighting_indoor_01_13",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:floor_lamp:black",
    ["sortKey"] = 6170,
    ["categoryId"] = "utilities:lighting",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_floor_lamp_black",
    ["descriptionKey"] = "Tooltip_MoreBuild_FloorLamp",
    ["recipeId"] = "MoreBuilds.FloorLamp",
    ["previewSprite"] = "lighting_indoor_01_56",
    ["placement"] = {
      ["kind"] = "morebuilds:light",
      ["data"] = {
        ["sprite"] = "lighting_indoor_01_56",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:floor_lamp:white",
    ["sortKey"] = 6180,
    ["categoryId"] = "utilities:lighting",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_floor_lamp_white",
    ["descriptionKey"] = "Tooltip_MoreBuild_FloorLamp",
    ["recipeId"] = "MoreBuilds.FloorLamp",
    ["previewSprite"] = "lighting_indoor_01_57",
    ["placement"] = {
      ["kind"] = "morebuilds:light",
      ["data"] = {
        ["sprite"] = "lighting_indoor_01_57",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:floor_lamp:brass",
    ["sortKey"] = 6190,
    ["categoryId"] = "utilities:lighting",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_floor_lamp_brass",
    ["descriptionKey"] = "Tooltip_MoreBuild_FloorLamp",
    ["recipeId"] = "MoreBuilds.FloorLamp",
    ["previewSprite"] = "lighting_indoor_01_58",
    ["placement"] = {
      ["kind"] = "morebuilds:light",
      ["data"] = {
        ["sprite"] = "lighting_indoor_01_58",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:floor_lamp:grey_large",
    ["sortKey"] = 6195,
    ["categoryId"] = "utilities:lighting",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_floor_lamp_grey_large",
    ["descriptionKey"] = "Tooltip_MoreBuild_FloorLamp",
    ["recipeId"] = "MoreBuilds.FloorLamp",
    ["previewSprite"] = "lighting_indoor_03_4",
    ["placement"] = {
      ["kind"] = "morebuilds:light",
      ["data"] = {
        ["sprite"] = "lighting_indoor_03_4",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_lamp:pink",
    ["sortKey"] = 6200,
    ["categoryId"] = "utilities:lighting",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_lamp_pink",
    ["descriptionKey"] = "Tooltip_MoreBuild_WallLamp",
    ["recipeId"] = "MoreBuilds.TableLamp",
    ["previewSprite"] = "lighting_indoor_01_16",
    ["placement"] = {
      ["kind"] = "morebuilds:light",
      ["data"] = {
        ["eastSprite"] = "lighting_indoor_01_18",
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "lighting_indoor_01_17",
        ["southSprite"] = "lighting_indoor_01_19",
        ["sprite"] = "lighting_indoor_01_16",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_lamp:dark",
    ["sortKey"] = 6210,
    ["categoryId"] = "utilities:lighting",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_lamp_dark",
    ["descriptionKey"] = "Tooltip_MoreBuild_WallLamp",
    ["recipeId"] = "MoreBuilds.TableLamp",
    ["previewSprite"] = "lighting_indoor_01_20",
    ["placement"] = {
      ["kind"] = "morebuilds:light",
      ["data"] = {
        ["eastSprite"] = "lighting_indoor_01_22",
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "lighting_indoor_01_21",
        ["southSprite"] = "lighting_indoor_01_23",
        ["sprite"] = "lighting_indoor_01_20",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:illuminated_sign:exit",
    ["sortKey"] = 6220,
    ["categoryId"] = "utilities:lighting",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_illuminated_sign_exit",
    ["descriptionKey"] = "Tooltip_MoreBuild_IlluminatedSign",
    ["recipeId"] = "MoreBuilds.SignElectric",
    ["previewSprite"] = "lighting_indoor_01_24",
    ["placement"] = {
      ["kind"] = "morebuilds:light",
      ["data"] = {
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "lighting_indoor_01_25",
        ["sprite"] = "lighting_indoor_01_24",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:outdoor_wall_lamp:round",
    ["sortKey"] = 6230,
    ["categoryId"] = "utilities:lighting",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_outdoor_wall_lamp_round",
    ["descriptionKey"] = "Tooltip_MoreBuild_OutdoorWallLamp",
    ["recipeId"] = "MoreBuilds.OutdoorLight",
    ["previewSprite"] = "lighting_outdoor_01_25",
    ["placement"] = {
      ["kind"] = "morebuilds:light",
      ["data"] = {
        ["eastSprite"] = "lighting_outdoor_01_29",
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "lighting_outdoor_01_24",
        ["southSprite"] = "lighting_outdoor_01_28",
        ["sprite"] = "lighting_outdoor_01_25",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:outdoor_wall_lamp:antique",
    ["sortKey"] = 6240,
    ["categoryId"] = "utilities:lighting",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_outdoor_wall_lamp_antique",
    ["descriptionKey"] = "Tooltip_MoreBuild_OutdoorWallLamp",
    ["recipeId"] = "MoreBuilds.OutdoorLight",
    ["previewSprite"] = "lighting_outdoor_01_27",
    ["placement"] = {
      ["kind"] = "morebuilds:light",
      ["data"] = {
        ["eastSprite"] = "lighting_outdoor_01_31",
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "lighting_outdoor_01_26",
        ["southSprite"] = "lighting_outdoor_01_30",
        ["sprite"] = "lighting_outdoor_01_27",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:outdoor_wall_lamp:modern",
    ["sortKey"] = 6250,
    ["categoryId"] = "utilities:lighting",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_outdoor_wall_lamp_modern",
    ["descriptionKey"] = "Tooltip_MoreBuild_OutdoorWallLamp",
    ["recipeId"] = "MoreBuilds.OutdoorLight",
    ["previewSprite"] = "lighting_outdoor_01_33",
    ["placement"] = {
      ["kind"] = "morebuilds:light",
      ["data"] = {
        ["eastSprite"] = "lighting_outdoor_01_37",
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "lighting_outdoor_01_32",
        ["southSprite"] = "lighting_outdoor_01_36",
        ["sprite"] = "lighting_outdoor_01_33",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:outdoor_wall_lamp:decorative",
    ["sortKey"] = 6260,
    ["categoryId"] = "utilities:lighting",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_outdoor_wall_lamp_decorative",
    ["descriptionKey"] = "Tooltip_MoreBuild_OutdoorWallLamp",
    ["recipeId"] = "MoreBuilds.OutdoorLight",
    ["previewSprite"] = "lighting_outdoor_01_35",
    ["placement"] = {
      ["kind"] = "morebuilds:light",
      ["data"] = {
        ["eastSprite"] = "lighting_outdoor_01_38",
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "lighting_outdoor_01_34",
        ["southSprite"] = "lighting_outdoor_01_39",
        ["sprite"] = "lighting_outdoor_01_35",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:outdoor_wall_lamp:oval",
    ["sortKey"] = 6270,
    ["categoryId"] = "utilities:lighting",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_outdoor_wall_lamp_oval",
    ["descriptionKey"] = "Tooltip_MoreBuild_OutdoorWallLamp",
    ["recipeId"] = "MoreBuilds.OutdoorLight",
    ["previewSprite"] = "lighting_outdoor_01_41",
    ["placement"] = {
      ["kind"] = "morebuilds:light",
      ["data"] = {
        ["eastSprite"] = "lighting_outdoor_01_45",
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "lighting_outdoor_01_40",
        ["southSprite"] = "lighting_outdoor_01_44",
        ["sprite"] = "lighting_outdoor_01_41",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:illuminated_sign:neon_open",
    ["sortKey"] = 6280,
    ["categoryId"] = "utilities:lighting",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_illuminated_sign_neon_open",
    ["descriptionKey"] = "Tooltip_MoreBuild_IlluminatedSign",
    ["recipeId"] = "MoreBuilds.SignElectric",
    ["previewSprite"] = "lighting_outdoor_01_43",
    ["placement"] = {
      ["kind"] = "morebuilds:light",
      ["data"] = {
        ["eastSprite"] = "lighting_outdoor_01_47",
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "lighting_outdoor_01_42",
        ["southSprite"] = "lighting_outdoor_01_46",
        ["sprite"] = "lighting_outdoor_01_43",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_lamp:fluorescent",
    ["sortKey"] = 7180,
    ["categoryId"] = "utilities:lighting",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_lamp_fluorescent",
    ["descriptionKey"] = "Tooltip_MoreBuild_WallLamp",
    ["recipeId"] = "MoreBuilds.TableLamp",
    ["previewSprite"] = "lighting_indoor_02_44",
    ["placement"] = {
      ["kind"] = "morebuilds:light",
      ["data"] = {
        ["eastSprite"] = "lighting_indoor_02_47",
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "lighting_indoor_02_45",
        ["southSprite"] = "lighting_indoor_02_46",
        ["sprite"] = "lighting_indoor_02_44",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_lamp:double_fluorescent",
    ["sortKey"] = 7185,
    ["categoryId"] = "utilities:lighting",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_lamp_double_fluorescent",
    ["descriptionKey"] = "Tooltip_MoreBuild_WallLamp",
    ["recipeId"] = "MoreBuilds.DoubleWallLamp",
    ["previewSprite"] = "lighting_indoor_02_50",
    ["placement"] = {
      ["kind"] = "morebuilds:multi-light",
      ["data"] = {
        ["eastSprite"] = "lighting_indoor_02_55",
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "lighting_indoor_02_50",
        ["southSprite"] = "lighting_indoor_02_52",
        ["sprite"] = "lighting_indoor_02_49",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_lamp:white",
    ["sortKey"] = 7190,
    ["categoryId"] = "utilities:lighting",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_lamp_white",
    ["descriptionKey"] = "Tooltip_MoreBuild_WallLamp",
    ["recipeId"] = "MoreBuilds.TableLamp",
    ["previewSprite"] = "lighting_indoor_02_60",
    ["placement"] = {
      ["kind"] = "morebuilds:light",
      ["data"] = {
        ["eastSprite"] = "lighting_indoor_02_62",
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "lighting_indoor_02_61",
        ["southSprite"] = "lighting_indoor_02_63",
        ["sprite"] = "lighting_indoor_02_60",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_lamp:green_half_sphere",
    ["sortKey"] = 7200,
    ["categoryId"] = "utilities:lighting",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_lamp_green_half_sphere",
    ["descriptionKey"] = "Tooltip_MoreBuild_WallLamp",
    ["recipeId"] = "MoreBuilds.TableLamp",
    ["previewSprite"] = "lighting_indoor_02_72",
    ["placement"] = {
      ["kind"] = "morebuilds:light",
      ["data"] = {
        ["eastSprite"] = "lighting_indoor_02_75",
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "lighting_indoor_02_73",
        ["southSprite"] = "lighting_indoor_02_74",
        ["sprite"] = "lighting_indoor_02_72",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_lamp:half_sphere",
    ["sortKey"] = 7210,
    ["categoryId"] = "utilities:lighting",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_lamp_half_sphere",
    ["descriptionKey"] = "Tooltip_MoreBuild_WallLamp",
    ["recipeId"] = "MoreBuilds.TableLamp",
    ["previewSprite"] = "lighting_indoor_02_76",
    ["placement"] = {
      ["kind"] = "morebuilds:light",
      ["data"] = {
        ["eastSprite"] = "lighting_indoor_02_79",
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "lighting_indoor_02_77",
        ["southSprite"] = "lighting_indoor_02_78",
        ["sprite"] = "lighting_indoor_02_76",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:wall_lamp:bar",
    ["sortKey"] = 7220,
    ["categoryId"] = "utilities:lighting",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_wall_lamp_bar",
    ["descriptionKey"] = "Tooltip_MoreBuild_WallLamp",
    ["recipeId"] = "MoreBuilds.TableLamp",
    ["previewSprite"] = "lighting_indoor_02_80",
    ["placement"] = {
      ["kind"] = "morebuilds:light",
      ["data"] = {
        ["eastSprite"] = "lighting_indoor_02_83",
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "lighting_indoor_02_81",
        ["southSprite"] = "lighting_indoor_02_82",
        ["sprite"] = "lighting_indoor_02_80",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:light_pole:ornate_black",
    ["sortKey"] = 7230,
    ["categoryId"] = "utilities:lighting",
    ["nameKey"] = "ContextMenu_MoreBuild_OrnateBlackLightPole",
    ["descriptionKey"] = "Tooltip_MoreBuild_LightPole",
    ["recipeId"] = "MoreBuilds.LightPole",
    ["previewSprite"] = "lighting_outdoor_01_3",
    ["placement"] = {
      ["kind"] = "morebuilds:light",
      ["data"] = {
        ["sprite"] = "lighting_outdoor_01_3",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:light_pole:ornate_gold",
    ["sortKey"] = 7240,
    ["categoryId"] = "utilities:lighting",
    ["nameKey"] = "ContextMenu_MoreBuild_OrnateGoldLightPole",
    ["descriptionKey"] = "Tooltip_MoreBuild_LightPole",
    ["recipeId"] = "MoreBuilds.LightPole",
    ["previewSprite"] = "lighting_outdoor_01_5",
    ["placement"] = {
      ["kind"] = "morebuilds:light",
      ["data"] = {
        ["sprite"] = "lighting_outdoor_01_5",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:light_pole:ornate_double",
    ["sortKey"] = 7250,
    ["categoryId"] = "utilities:lighting",
    ["nameKey"] = "ContextMenu_MoreBuild_OrnateDoubleLightPole",
    ["descriptionKey"] = "Tooltip_MoreBuild_LightPole",
    ["recipeId"] = "MoreBuilds.LightPole",
    ["previewSprite"] = "lighting_outdoor_01_6",
    ["placement"] = {
      ["kind"] = "morebuilds:light",
      ["data"] = {
        ["eastSprite"] = "lighting_outdoor_01_7",
        ["northSprite"] = "lighting_outdoor_01_7",
        ["southSprite"] = "lighting_outdoor_01_6",
        ["sprite"] = "lighting_outdoor_01_6",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:light_pole:modern_round",
    ["sortKey"] = 7260,
    ["categoryId"] = "utilities:lighting",
    ["nameKey"] = "ContextMenu_MoreBuild_ModernRoundLightPole",
    ["descriptionKey"] = "Tooltip_MoreBuild_LightPole",
    ["recipeId"] = "MoreBuilds.LightPole",
    ["previewSprite"] = "lighting_outdoor_01_8",
    ["placement"] = {
      ["kind"] = "morebuilds:light",
      ["data"] = {
        ["eastSprite"] = "lighting_outdoor_01_10",
        ["northSprite"] = "lighting_outdoor_01_9",
        ["southSprite"] = "lighting_outdoor_01_11",
        ["sprite"] = "lighting_outdoor_01_8",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:survival:fridge_white_top_freezer",
    ["sortKey"] = 5111,
    ["categoryId"] = "utilities:appliances",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_survival_fridge_white_top_freezer",
    ["descriptionKey"] = "Tooltip_MoreBuild_Refrigerator",
    ["recipeId"] = "MoreBuilds.Refrigerator",
    ["previewSprite"] = "appliances_refrigeration_01_0",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "fridge",
        ["eastSprite"] = "appliances_refrigeration_01_2",
        ["health"] = 500,
        ["northSprite"] = "appliances_refrigeration_01_1",
        ["southSprite"] = "appliances_refrigeration_01_3",
        ["sprite"] = "appliances_refrigeration_01_0",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:survival:fridge_blue_bottom_freezer",
    ["sortKey"] = 5112,
    ["categoryId"] = "utilities:appliances",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_survival_fridge_blue_bottom_freezer",
    ["descriptionKey"] = "Tooltip_MoreBuild_Refrigerator",
    ["recipeId"] = "MoreBuilds.Refrigerator",
    ["previewSprite"] = "appliances_refrigeration_01_4",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "fridge",
        ["eastSprite"] = "appliances_refrigeration_01_6",
        ["health"] = 500,
        ["northSprite"] = "appliances_refrigeration_01_5",
        ["southSprite"] = "appliances_refrigeration_01_7",
        ["sprite"] = "appliances_refrigeration_01_4",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:survival:fridge_stainless_steel",
    ["sortKey"] = 5113,
    ["categoryId"] = "utilities:appliances",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_survival_fridge_stainless_steel",
    ["descriptionKey"] = "Tooltip_MoreBuild_Refrigerator",
    ["recipeId"] = "MoreBuilds.Refrigerator",
    ["previewSprite"] = "appliances_refrigeration_01_8",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "fridge",
        ["eastSprite"] = "appliances_refrigeration_01_10",
        ["health"] = 550,
        ["northSprite"] = "appliances_refrigeration_01_9",
        ["southSprite"] = "appliances_refrigeration_01_11",
        ["sprite"] = "appliances_refrigeration_01_8",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:survival:fridge_green_top_freezer",
    ["sortKey"] = 5114,
    ["categoryId"] = "utilities:appliances",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_survival_fridge_green_top_freezer",
    ["descriptionKey"] = "Tooltip_MoreBuild_Refrigerator",
    ["recipeId"] = "MoreBuilds.Refrigerator",
    ["previewSprite"] = "appliances_refrigeration_01_12",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "fridge",
        ["eastSprite"] = "appliances_refrigeration_01_14",
        ["health"] = 500,
        ["northSprite"] = "appliances_refrigeration_01_13",
        ["southSprite"] = "appliances_refrigeration_01_15",
        ["sprite"] = "appliances_refrigeration_01_12",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:survival:fridge_commercial",
    ["sortKey"] = 5115,
    ["categoryId"] = "utilities:appliances",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_survival_fridge_commercial",
    ["descriptionKey"] = "Tooltip_MoreBuild_CommercialRefrigerator",
    ["recipeId"] = "MoreBuilds.CommercialRefrigerator",
    ["previewSprite"] = "appliances_refrigeration_01_22",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "fridge",
        ["eastSprite"] = "appliances_refrigeration_01_36",
        ["health"] = 650,
        ["northSprite"] = "appliances_refrigeration_01_23",
        ["southSprite"] = "appliances_refrigeration_01_37",
        ["sprite"] = "appliances_refrigeration_01_22",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:survival:fridge_standard",
    ["sortKey"] = 5116,
    ["categoryId"] = "utilities:appliances",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_survival_fridge_standard",
    ["descriptionKey"] = "Tooltip_MoreBuild_Refrigerator",
    ["recipeId"] = "MoreBuilds.Refrigerator",
    ["previewSprite"] = "appliances_refrigeration_01_28",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "fridge",
        ["eastSprite"] = "appliances_refrigeration_01_30",
        ["health"] = 500,
        ["northSprite"] = "appliances_refrigeration_01_29",
        ["southSprite"] = "appliances_refrigeration_01_31",
        ["sprite"] = "appliances_refrigeration_01_28",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:survival:fridge_red_top_freezer",
    ["sortKey"] = 5117,
    ["categoryId"] = "utilities:appliances",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_survival_fridge_red_top_freezer",
    ["descriptionKey"] = "Tooltip_MoreBuild_Refrigerator",
    ["recipeId"] = "MoreBuilds.Refrigerator",
    ["previewSprite"] = "appliances_refrigeration_01_32",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "fridge",
        ["eastSprite"] = "appliances_refrigeration_01_34",
        ["health"] = 500,
        ["northSprite"] = "appliances_refrigeration_01_33",
        ["southSprite"] = "appliances_refrigeration_01_35",
        ["sprite"] = "appliances_refrigeration_01_32",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:survival:fridge_white_commercial",
    ["sortKey"] = 5118,
    ["categoryId"] = "utilities:appliances",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_survival_fridge_white_commercial",
    ["descriptionKey"] = "Tooltip_MoreBuild_CommercialRefrigerator",
    ["recipeId"] = "MoreBuilds.CommercialRefrigerator",
    ["previewSprite"] = "appliances_refrigeration_01_40",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "fridge",
        ["eastSprite"] = "appliances_refrigeration_01_42",
        ["health"] = 650,
        ["northSprite"] = "appliances_refrigeration_01_41",
        ["southSprite"] = "appliances_refrigeration_01_43",
        ["sprite"] = "appliances_refrigeration_01_40",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:survival:double_door_refrigerator",
    ["sortKey"] = 5161,
    ["categoryId"] = "utilities:appliances",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_survival_double_door_refrigerator",
    ["descriptionKey"] = "Tooltip_MoreBuild_LargeRefrigerator",
    ["recipeId"] = "MoreBuilds.LargeRefrigerator",
    ["previewSprite"] = "appliances_refrigeration_01_17",
    ["placement"] = {
      ["kind"] = "morebuilds:multi-container",
      ["data"] = {
        ["canBeLockedByPadlock"] = false,
        ["containerType"] = "fridge",
        ["eastSprite"] = "appliances_refrigeration_01_45",
        ["health"] = 700,
        ["northSprite"] = "appliances_refrigeration_01_18",
        ["southSprite"] = "appliances_refrigeration_01_46",
        ["sprite"] = "appliances_refrigeration_01_17",
        ["eastSprite2"] = "appliances_refrigeration_01_44",
        ["eastTileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = 0,
            ["y"] = 1,
          },
        },
        ["northSprite2"] = "appliances_refrigeration_01_19",
        ["northTileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = 1,
            ["y"] = 0,
          },
        },
        ["southSprite2"] = "appliances_refrigeration_01_47",
        ["southTileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = 1,
            ["y"] = 0,
          },
        },
        ["sprite2"] = "appliances_refrigeration_01_16",
        ["tileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = 0,
            ["y"] = 1,
          },
        },
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:survival:ice_cream_freezer",
    ["sortKey"] = 5171,
    ["categoryId"] = "utilities:appliances",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_survival_ice_cream_freezer",
    ["descriptionKey"] = "Tooltip_MoreBuild_IceCreamFreezer",
    ["recipeId"] = "MoreBuilds.Freezer",
    ["previewSprite"] = "appliances_refrigeration_01_21",
    ["placement"] = {
      ["kind"] = "morebuilds:multi-container",
      ["data"] = {
        ["canBeLockedByPadlock"] = false,
        ["containerType"] = "fridge",
        ["health"] = 600,
        ["northSprite"] = "appliances_refrigeration_01_38",
        ["sprite"] = "appliances_refrigeration_01_21",
        ["northSprite2"] = "appliances_refrigeration_01_39",
        ["northTileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = 1,
            ["y"] = 0,
          },
        },
        ["sprite2"] = "appliances_refrigeration_01_20",
        ["tileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = 0,
            ["y"] = 1,
          },
        },
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:survival:chest_freezer",
    ["sortKey"] = 5181,
    ["categoryId"] = "utilities:appliances",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_survival_chest_freezer",
    ["descriptionKey"] = "Tooltip_MoreBuild_ChestFreezer",
    ["recipeId"] = "MoreBuilds.FreezerSmall",
    ["previewSprite"] = "appliances_refrigeration_01_48",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["containerType"] = "fridge",
        ["eastSprite"] = "appliances_refrigeration_01_50",
        ["health"] = 600,
        ["northSprite"] = "appliances_refrigeration_01_49",
        ["southSprite"] = "appliances_refrigeration_01_51",
        ["sprite"] = "appliances_refrigeration_01_48",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:survival:fuel_generator_old",
    ["sortKey"] = 5131,
    ["categoryId"] = "utilities:appliances",
    ["nameKey"] = "ContextMenu_MoreBuild_Generator_Old",
    ["descriptionKey"] = "Tooltip_MoreBuild_Generator",
    ["recipeId"] = "MoreBuilds.Generator",
    ["previewSprite"] = "appliances_misc_01_4",
    ["placement"] = {
      ["kind"] = "morebuilds:generator",
      ["data"] = {
        ["eastSprite"] = "appliances_misc_01_6",
        ["northSprite"] = "appliances_misc_01_5",
        ["southSprite"] = "appliances_misc_01_7",
        ["sprite"] = "appliances_misc_01_4",
        ["generatorItem"] = "Base.Generator_Old",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:survival:fuel_generator_yellow",
    ["sortKey"] = 5132,
    ["categoryId"] = "utilities:appliances",
    ["nameKey"] = "ContextMenu_MoreBuild_Generator_PremiumTechnologies",
    ["descriptionKey"] = "Tooltip_MoreBuild_Generator",
    ["recipeId"] = "MoreBuilds.Generator",
    ["previewSprite"] = "appliances_misc_01_8",
    ["placement"] = {
      ["kind"] = "morebuilds:generator",
      ["data"] = {
        ["eastSprite"] = "appliances_misc_01_10",
        ["northSprite"] = "appliances_misc_01_9",
        ["southSprite"] = "appliances_misc_01_11",
        ["sprite"] = "appliances_misc_01_8",
        ["generatorItem"] = "Base.Generator_Yellow",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:survival:fuel_generator_blue",
    ["sortKey"] = 5133,
    ["categoryId"] = "utilities:appliances",
    ["nameKey"] = "ContextMenu_MoreBuild_Generator_ValuTech",
    ["descriptionKey"] = "Tooltip_MoreBuild_Generator",
    ["recipeId"] = "MoreBuilds.Generator",
    ["previewSprite"] = "appliances_misc_01_13",
    ["placement"] = {
      ["kind"] = "morebuilds:generator",
      ["data"] = {
        ["eastSprite"] = "appliances_misc_01_15",
        ["northSprite"] = "appliances_misc_01_12",
        ["southSprite"] = "appliances_misc_01_14",
        ["sprite"] = "appliances_misc_01_13",
        ["generatorItem"] = "Base.Generator_Blue",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:survival:propane_grill",
    ["sortKey"] = 5122,
    ["categoryId"] = "utilities:appliances",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_survival_propane_grill",
    ["descriptionKey"] = "Tooltip_MoreBuild_PropaneGrill",
    ["recipeId"] = "MoreBuilds.PropaneGrill",
    ["previewSprite"] = "appliances_cooking_01_45",
    ["placement"] = {
      ["kind"] = "morebuilds:barbecue",
      ["data"] = {
        ["eastSprite"] = "appliances_cooking_01_47",
        ["northSprite"] = "appliances_cooking_01_44",
        ["southSprite"] = "appliances_cooking_01_46",
        ["sprite"] = "appliances_cooking_01_45",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:survival:electric_stove_green",
    ["sortKey"] = 5141,
    ["categoryId"] = "utilities:appliances",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_survival_electric_stove_green",
    ["descriptionKey"] = "Tooltip_MoreBuild_ElectricStove",
    ["recipeId"] = "MoreBuilds.ElectricStove",
    ["previewSprite"] = "appliances_cooking_01_0",
    ["placement"] = {
      ["kind"] = "morebuilds:stove",
      ["data"] = {
        ["eastSprite"] = "appliances_cooking_01_2",
        ["northSprite"] = "appliances_cooking_01_1",
        ["southSprite"] = "appliances_cooking_01_3",
        ["sprite"] = "appliances_cooking_01_0",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:survival:electric_stove_gray",
    ["sortKey"] = 5142,
    ["categoryId"] = "utilities:appliances",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_survival_electric_stove_gray",
    ["descriptionKey"] = "Tooltip_MoreBuild_ElectricStove",
    ["recipeId"] = "MoreBuilds.ElectricStove",
    ["previewSprite"] = "appliances_cooking_01_4",
    ["placement"] = {
      ["kind"] = "morebuilds:stove",
      ["data"] = {
        ["eastSprite"] = "appliances_cooking_01_6",
        ["northSprite"] = "appliances_cooking_01_5",
        ["southSprite"] = "appliances_cooking_01_7",
        ["sprite"] = "appliances_cooking_01_4",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:survival:electric_stove_red",
    ["sortKey"] = 5143,
    ["categoryId"] = "utilities:appliances",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_survival_electric_stove_red",
    ["descriptionKey"] = "Tooltip_MoreBuild_ElectricStove",
    ["recipeId"] = "MoreBuilds.ElectricStove",
    ["previewSprite"] = "appliances_cooking_01_8",
    ["placement"] = {
      ["kind"] = "morebuilds:stove",
      ["data"] = {
        ["eastSprite"] = "appliances_cooking_01_10",
        ["northSprite"] = "appliances_cooking_01_9",
        ["southSprite"] = "appliances_cooking_01_11",
        ["sprite"] = "appliances_cooking_01_8",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:survival:electric_stove_modern",
    ["sortKey"] = 5144,
    ["categoryId"] = "utilities:appliances",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_survival_electric_stove_modern",
    ["descriptionKey"] = "Tooltip_MoreBuild_ElectricStove",
    ["recipeId"] = "MoreBuilds.ElectricStove",
    ["previewSprite"] = "appliances_cooking_01_12",
    ["placement"] = {
      ["kind"] = "morebuilds:stove",
      ["data"] = {
        ["eastSprite"] = "appliances_cooking_01_14",
        ["northSprite"] = "appliances_cooking_01_13",
        ["southSprite"] = "appliances_cooking_01_15",
        ["sprite"] = "appliances_cooking_01_12",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:survival:industrial_stove",
    ["sortKey"] = 5145,
    ["categoryId"] = "utilities:appliances",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_survival_industrial_stove",
    ["descriptionKey"] = "Tooltip_MoreBuild_IndustrialStove",
    ["recipeId"] = "MoreBuilds.IndustrialStove",
    ["previewSprite"] = "appliances_cooking_01_20",
    ["placement"] = {
      ["kind"] = "morebuilds:stove",
      ["data"] = {
        ["eastSprite"] = "appliances_cooking_01_22",
        ["northSprite"] = "appliances_cooking_01_21",
        ["southSprite"] = "appliances_cooking_01_23",
        ["sprite"] = "appliances_cooking_01_20",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:survival:large_modern_stove",
    ["sortKey"] = 5146,
    ["categoryId"] = "utilities:appliances",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_survival_large_modern_stove",
    ["descriptionKey"] = "Tooltip_MoreBuild_LargeModernStove",
    ["recipeId"] = "MoreBuilds.LargeModernStove",
    ["previewSprite"] = "appliances_cooking_01_40",
    ["placement"] = {
      ["kind"] = "morebuilds:multi-stove",
      ["data"] = {
        ["eastSprite"] = "appliances_cooking_01_48",
        ["northSprite"] = "appliances_cooking_01_42",
        ["southSprite"] = "appliances_cooking_01_50",
        ["sprite"] = "appliances_cooking_01_40",
        ["eastSprite2"] = "appliances_cooking_01_49",
        ["eastTileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = 0,
            ["y"] = -1,
          },
        },
        ["northSprite2"] = "appliances_cooking_01_43",
        ["northTileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = 1,
            ["y"] = 0,
          },
        },
        ["southSprite2"] = "appliances_cooking_01_51",
        ["southTileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = 1,
            ["y"] = 0,
          },
        },
        ["sprite2"] = "appliances_cooking_01_41",
        ["tileOffsets"] = {
          {
            ["x"] = 0,
            ["y"] = 0,
          },
          {
            ["x"] = 0,
            ["y"] = -1,
          },
        },
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:survival:commercial_fryer",
    ["sortKey"] = 5147,
    ["categoryId"] = "utilities:appliances",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_survival_commercial_fryer",
    ["descriptionKey"] = "Tooltip_MoreBuild_CommercialFryer",
    ["recipeId"] = "MoreBuilds.IndustrialStove",
    ["previewSprite"] = "appliances_cooking_01_52",
    ["placement"] = {
      ["kind"] = "morebuilds:stove",
      ["data"] = {
        ["eastSprite"] = "appliances_cooking_01_54",
        ["northSprite"] = "appliances_cooking_01_53",
        ["southSprite"] = "appliances_cooking_01_55",
        ["sprite"] = "appliances_cooking_01_52",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:survival:commercial_bake_oven",
    ["sortKey"] = 5148,
    ["categoryId"] = "utilities:appliances",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_survival_commercial_bake_oven",
    ["descriptionKey"] = "Tooltip_MoreBuild_CommercialBakeOven",
    ["recipeId"] = "MoreBuilds.CommercialBakeOven",
    ["previewSprite"] = "appliances_cooking_01_64",
    ["placement"] = {
      ["kind"] = "morebuilds:furniture",
      ["data"] = {
        ["eastSprite"] = "appliances_cooking_01_66",
        ["health"] = 500,
        ["northSprite"] = "appliances_cooking_01_65",
        ["southSprite"] = "appliances_cooking_01_67",
        ["sprite"] = "appliances_cooking_01_64",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:survival:microwave_white",
    ["sortKey"] = 5189,
    ["categoryId"] = "utilities:appliances",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_survival_microwave_white",
    ["descriptionKey"] = "Tooltip_MoreBuild_Microwave",
    ["recipeId"] = "MoreBuilds.Microwave",
    ["previewSprite"] = "appliances_cooking_01_24",
    ["placement"] = {
      ["kind"] = "morebuilds:stove",
      ["data"] = {
        ["eastSprite"] = "appliances_cooking_01_26",
        ["northSprite"] = "appliances_cooking_01_25",
        ["southSprite"] = "appliances_cooking_01_27",
        ["sprite"] = "appliances_cooking_01_24",
        ["tableTop"] = true,
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:survival:microwave_chrome",
    ["sortKey"] = 5191,
    ["categoryId"] = "utilities:appliances",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_survival_microwave_chrome",
    ["descriptionKey"] = "Tooltip_MoreBuild_Microwave",
    ["recipeId"] = "MoreBuilds.Microwave",
    ["previewSprite"] = "appliances_cooking_01_29",
    ["placement"] = {
      ["kind"] = "morebuilds:stove",
      ["data"] = {
        ["eastSprite"] = "appliances_cooking_01_30",
        ["northSprite"] = "appliances_cooking_01_28",
        ["southSprite"] = "appliances_cooking_01_31",
        ["sprite"] = "appliances_cooking_01_29",
        ["tableTop"] = true,
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:table_appliance:toaster",
    ["sortKey"] = 5192,
    ["categoryId"] = "utilities:appliances",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_table_appliance_toaster",
    ["descriptionKey"] = "Tooltip_MoreBuild_Toaster",
    ["recipeId"] = "MoreBuilds.Toaster",
    ["previewSprite"] = "appliances_cooking_01_32",
    ["placement"] = {
      ["kind"] = "morebuilds:table-decoration",
      ["data"] = {
        ["eastSprite"] = "appliances_cooking_01_33",
        ["health"] = 50,
        ["northSprite"] = "appliances_cooking_01_33",
        ["southSprite"] = "appliances_cooking_01_32",
        ["sprite"] = "appliances_cooking_01_32",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:table_appliance:coffee_maker",
    ["sortKey"] = 5193,
    ["categoryId"] = "utilities:appliances",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_table_appliance_coffee_maker",
    ["descriptionKey"] = "Tooltip_MoreBuild_CoffeeMaker",
    ["recipeId"] = "MoreBuilds.CoffeeMaker",
    ["previewSprite"] = "appliances_cooking_01_57",
    ["placement"] = {
      ["kind"] = "morebuilds:table-decoration",
      ["data"] = {
        ["eastSprite"] = "appliances_cooking_01_58",
        ["health"] = 50,
        ["northSprite"] = "appliances_cooking_01_56",
        ["southSprite"] = "appliances_cooking_01_59",
        ["sprite"] = "appliances_cooking_01_57",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:table_appliance:espresso_machine",
    ["sortKey"] = 5194,
    ["categoryId"] = "utilities:appliances",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_table_appliance_espresso_machine",
    ["descriptionKey"] = "Tooltip_MoreBuild_EspressoMachine",
    ["recipeId"] = "MoreBuilds.EspressoMachine",
    ["previewSprite"] = "appliances_cooking_01_60",
    ["placement"] = {
      ["kind"] = "morebuilds:table-decoration",
      ["data"] = {
        ["eastSprite"] = "appliances_cooking_01_63",
        ["health"] = 50,
        ["northSprite"] = "appliances_cooking_01_61",
        ["southSprite"] = "appliances_cooking_01_62",
        ["sprite"] = "appliances_cooking_01_60",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:survival:extractor_hood",
    ["sortKey"] = 5196,
    ["categoryId"] = "utilities:appliances",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_survival_extractor_hood",
    ["descriptionKey"] = "Tooltip_MoreBuild_ExtractorHood",
    ["recipeId"] = "MoreBuilds.ExtractorHood",
    ["previewSprite"] = "appliances_cooking_01_68",
    ["placement"] = {
      ["kind"] = "morebuilds:wall-decoration",
      ["data"] = {
        ["eastSprite"] = "appliances_cooking_01_71",
        ["health"] = 100,
        ["needToBeAgainstWall"] = true,
        ["northSprite"] = "appliances_cooking_01_69",
        ["southSprite"] = "appliances_cooking_01_70",
        ["sprite"] = "appliances_cooking_01_68",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:survival:dishwasher_brown",
    ["sortKey"] = 5197,
    ["categoryId"] = "utilities:appliances",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_survival_dishwasher_brown",
    ["descriptionKey"] = "Tooltip_MoreBuild_Dishwasher",
    ["recipeId"] = "MoreBuilds.Dishwasher",
    ["previewSprite"] = "appliances_cooking_01_73",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["canBeLockedByPadlock"] = false,
        ["containerCapacity"] = 10,
        ["containerType"] = "dishwasher",
        ["eastSprite"] = "appliances_cooking_01_75",
        ["health"] = 400,
        ["northSprite"] = "appliances_cooking_01_72",
        ["placeBeforeCountertop"] = true,
        ["southSprite"] = "appliances_cooking_01_74",
        ["sprite"] = "appliances_cooking_01_73",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
  {
    ["id"] = "morebuilds:survival:dishwasher_metal",
    ["sortKey"] = 5198,
    ["categoryId"] = "utilities:appliances",
    ["nameKey"] = "ContextMenu_MoreBuild_Name_survival_dishwasher_metal",
    ["descriptionKey"] = "Tooltip_MoreBuild_Dishwasher",
    ["recipeId"] = "MoreBuilds.Dishwasher",
    ["previewSprite"] = "appliances_cooking_01_77",
    ["placement"] = {
      ["kind"] = "morebuilds:container",
      ["data"] = {
        ["canBeLockedByPadlock"] = false,
        ["containerCapacity"] = 10,
        ["containerType"] = "dishwasher",
        ["eastSprite"] = "appliances_cooking_01_79",
        ["health"] = 400,
        ["northSprite"] = "appliances_cooking_01_76",
        ["placeBeforeCountertop"] = true,
        ["southSprite"] = "appliances_cooking_01_78",
        ["sprite"] = "appliances_cooking_01_77",
      },
    },
    ["salvagePolicy"] = "recipe-inputs",
  },
}

for _, definition in ipairs(definitions) do
  definition.sortKey = definition.sortKey + 120000
end

return definitions
