return {
  groups = {
    { id = 'structure', nameKey = 'UI_MoreBuild_Category_Structure', sortKey = 100 },
    { id = 'furniture', nameKey = 'UI_MoreBuild_Category_Furniture', sortKey = 200 },
    { id = 'storage', nameKey = 'UI_MoreBuild_Category_Storage', sortKey = 300 },
    { id = 'utilities', nameKey = 'UI_MoreBuild_Category_Utilities', sortKey = 400 },
    { id = 'outdoors', nameKey = 'UI_MoreBuild_Category_Outdoors', sortKey = 500 },
    { id = 'decorations', nameKey = 'UI_MoreBuild_Category_Decorations', sortKey = 600 },
  },
  categories = {
    { id = 'structure:walls', groupId = 'structure', nameKey = 'UI_MoreBuild_Subcategory_Walls', sortKey = 100 },
    { id = 'structure:window-walls', groupId = 'structure', nameKey = 'UI_MoreBuild_Subcategory_WindowWalls', sortKey = 110 },
    { id = 'structure:doors', groupId = 'structure', nameKey = 'UI_MoreBuild_Subcategory_Doors', sortKey = 200 },
    { id = 'structure:door-frames', groupId = 'structure', nameKey = 'UI_MoreBuild_Subcategory_DoorFrames', sortKey = 210 },
    { id = 'structure:windows', groupId = 'structure', nameKey = 'UI_MoreBuild_Subcategory_Windows', sortKey = 220 },
    { id = 'structure:window-frames', groupId = 'structure', nameKey = 'UI_MoreBuild_Subcategory_WindowFrames', sortKey = 230 },
    { id = 'structure:floors', groupId = 'structure', nameKey = 'UI_MoreBuild_Subcategory_Floors', sortKey = 300 },
    { id = 'structure:fences', groupId = 'structure', nameKey = 'UI_MoreBuild_Subcategory_Fences', sortKey = 400 },
    { id = 'structure:posts-pillars', groupId = 'structure', nameKey = 'UI_MoreBuild_Subcategory_PostsPillars', sortKey = 410 },
    { id = 'structure:stairs', groupId = 'structure', nameKey = 'UI_MoreBuild_Subcategory_Stairs', sortKey = 500 },
    { id = 'furniture:seating', groupId = 'furniture', nameKey = 'UI_MoreBuild_Subcategory_Seating', sortKey = 100 },
    { id = 'furniture:tables', groupId = 'furniture', nameKey = 'UI_MoreBuild_Subcategory_Tables', sortKey = 200 },
    { id = 'furniture:bedroom-leisure', groupId = 'furniture', nameKey = 'UI_MoreBuild_Subcategory_BedroomLeisure', sortKey = 300 },
    { id = 'storage:shelves-counters', groupId = 'storage', nameKey = 'UI_MoreBuild_Subcategory_ShelvesCounters', sortKey = 100 },
    { id = 'storage:cabinets-wardrobes', groupId = 'storage', nameKey = 'UI_MoreBuild_Subcategory_CabinetsWardrobes', sortKey = 200 },
    { id = 'storage:containers', groupId = 'storage', nameKey = 'UI_MoreBuild_Subcategory_Containers', sortKey = 300 },
    { id = 'utilities:lighting', groupId = 'utilities', nameKey = 'UI_MoreBuild_Subcategory_Lighting', sortKey = 100 },
    { id = 'utilities:appliances', groupId = 'utilities', nameKey = 'UI_MoreBuild_Subcategory_Appliances', sortKey = 200 },
    { id = 'utilities:water-sanitation', groupId = 'utilities', nameKey = 'UI_MoreBuild_Subcategory_WaterSanitation', sortKey = 300 },
    { id = 'outdoors:garden', groupId = 'outdoors', nameKey = 'UI_MoreBuild_Subcategory_Garden', sortKey = 100 },
    { id = 'outdoors:street', groupId = 'outdoors', nameKey = 'UI_MoreBuild_Subcategory_StreetFeatures', sortKey = 200 },
    { id = 'outdoors:furnishings', groupId = 'outdoors', nameKey = 'UI_MoreBuild_Subcategory_OutdoorFurnishings', sortKey = 300 },
    { id = 'decorations:wall-decor', groupId = 'decorations', nameKey = 'UI_MoreBuild_Subcategory_WallDecor', sortKey = 100 },
    { id = 'decorations:objects', groupId = 'decorations', nameKey = 'UI_MoreBuild_Subcategory_DecorativeObjects', sortKey = 200 },
  },
}
